'use client';

import { useEffect, useState, useCallback } from 'react';
import { useRouter } from 'next/navigation';
import { Input, Select, Button, Badge } from '@/components/ui';

interface ExerciseWithProfile {
  id: string;
  name: { en: string; ar: string };
  slug: string;
  archetype: string | null;
  hasProfile: boolean;
  profile: {
    id: string;
    archetype: string;
    isAutoGenerated: boolean;
    allowedAxes: string[];
  } | null;
}

interface ArchetypeInfo {
  code: string;
  allowedAxes: string[];
  priorityOrder: string[];
}

const ARCHETYPE_LABELS: Record<string, string> = {
  weighted_strength: 'Weighted Strength',
  bodyweight_dynamic: 'Bodyweight Dynamic',
  isometric_hold: 'Isometric Hold',
  mobility_rom: 'Mobility / ROM',
  motor_control: 'Motor Control',
};

const ARCHETYPE_BADGE: Record<string, 'primary' | 'purple' | 'teal' | 'default'> = {
  weighted_strength: 'primary',
  bodyweight_dynamic: 'purple',
  isometric_hold: 'teal',
  mobility_rom: 'default',
  motor_control: 'default',
};

export default function ExerciseProgressionPage() {
  const router = useRouter();
  const [exercises, setExercises] = useState<ExerciseWithProfile[]>([]);
  const [archetypes, setArchetypes] = useState<ArchetypeInfo[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [filterArchetype, setFilterArchetype] = useState('');
  const [filterStatus, setFilterStatus] = useState('');
  const [bulkArchetype, setBulkArchetype] = useState('');
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set());
  const [saving, setSaving] = useState(false);

  const fetchData = useCallback(async () => {
    setLoading(true);
    try {
      const [exRes, archRes] = await Promise.all([
        fetch(`/api/admin/exercise-progression/exercises${search ? `?search=${encodeURIComponent(search)}` : ''}`),
        fetch('/api/admin/exercise-progression/archetypes'),
      ]);
      const exData = await exRes.json();
      const archData = await archRes.json();
      if (exData.success) setExercises(exData.data);
      if (archData.success) setArchetypes(archData.data);
    } catch (error) {
      console.error('Error fetching data:', error);
    } finally {
      setLoading(false);
    }
  }, [search]);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  const handleSetArchetype = async (exerciseId: string, archetype: string) => {
    try {
      const res = await fetch(`/api/admin/exercise-progression/${exerciseId}/archetype`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ archetype }),
      });
      const data = await res.json();
      if (data.success) fetchData();
      else alert(data.error || 'Failed to set archetype');
    } catch (error) {
      console.error('Error setting archetype:', error);
    }
  };

  const handleBulkGenerate = async () => {
    if (!bulkArchetype || selectedIds.size === 0) return;
    setSaving(true);
    try {
      const res = await fetch('/api/admin/exercise-progression/bulk-generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ exerciseIds: Array.from(selectedIds), archetype: bulkArchetype }),
      });
      const data = await res.json();
      if (data.success) {
        setSelectedIds(new Set());
        setBulkArchetype('');
        fetchData();
      } else {
        alert(data.error || 'Failed to bulk generate');
      }
    } catch (error) {
      console.error('Error in bulk generate:', error);
    } finally {
      setSaving(false);
    }
  };

  const toggleSelect = (id: string) => {
    setSelectedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  };

  const toggleSelectAll = () => {
    if (selectedIds.size === filtered.length) {
      setSelectedIds(new Set());
    } else {
      setSelectedIds(new Set(filtered.map((e) => e.id)));
    }
  };

  const filtered = exercises.filter((ex) => {
    if (filterArchetype && ex.archetype !== filterArchetype && ex.profile?.archetype !== filterArchetype) return false;
    if (filterStatus === 'has_profile' && !ex.hasProfile) return false;
    if (filterStatus === 'no_profile' && ex.hasProfile) return false;
    return true;
  });

  const stats = {
    total: exercises.length,
    withProfile: exercises.filter((e) => e.hasProfile).length,
    withoutProfile: exercises.filter((e) => !e.hasProfile).length,
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-900">Exercise Progression</h1>
        <p className="text-gray-600 mt-1">
          Manage scientific progression profiles for exercises.
          This is the single source of truth for how each exercise progresses.
        </p>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-3 gap-4">
        <div className="bg-white rounded-lg border p-4">
          <p className="text-sm text-gray-500">Total Exercises</p>
          <p className="text-2xl font-bold">{stats.total}</p>
        </div>
        <div className="bg-white rounded-lg border p-4">
          <p className="text-sm text-gray-500">With Profile</p>
          <p className="text-2xl font-bold text-green-600">{stats.withProfile}</p>
        </div>
        <div className="bg-white rounded-lg border p-4">
          <p className="text-sm text-gray-500">Missing Profile</p>
          <p className="text-2xl font-bold text-orange-600">{stats.withoutProfile}</p>
        </div>
      </div>

      {/* Filters */}
      <div className="bg-white rounded-lg border p-4">
        <div className="flex gap-4 items-end flex-wrap">
          <div className="flex-1 min-w-[200px]">
            <label className="block text-sm font-medium text-gray-700 mb-1">Search</label>
            <Input
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              placeholder="Search by slug..."
            />
          </div>
          <div className="w-48">
            <label className="block text-sm font-medium text-gray-700 mb-1">Archetype</label>
            <Select
              value={filterArchetype}
              onChange={(e) => setFilterArchetype(e.target.value)}
              options={[
                { value: '', label: 'All Archetypes' },
                ...Object.entries(ARCHETYPE_LABELS).map(([k, v]) => ({ value: k, label: v })),
              ]}
            />
          </div>
          <div className="w-48">
            <label className="block text-sm font-medium text-gray-700 mb-1">Profile Status</label>
            <Select
              value={filterStatus}
              onChange={(e) => setFilterStatus(e.target.value)}
              options={[
                { value: '', label: 'All' },
                { value: 'has_profile', label: 'Has Profile' },
                { value: 'no_profile', label: 'Missing Profile' },
              ]}
            />
          </div>
        </div>
      </div>

      {/* Bulk Actions */}
      {selectedIds.size > 0 && (
        <div className="bg-blue-50 rounded-lg border border-blue-200 p-4 flex items-center gap-4">
          <span className="text-sm font-medium text-blue-800">
            {selectedIds.size} exercise(s) selected
          </span>
          <Select
            value={bulkArchetype}
            onChange={(e) => setBulkArchetype(e.target.value)}
            options={[
              { value: '', label: 'Select Archetype...' },
              ...Object.entries(ARCHETYPE_LABELS).map(([k, v]) => ({ value: k, label: v })),
            ]}
          />
          <Button
            onClick={handleBulkGenerate}
            disabled={!bulkArchetype || saving}
            loading={saving}
            size="sm"
          >
            Generate Profiles
          </Button>
        </div>
      )}

      {/* Table */}
      <div className="bg-white rounded-lg shadow-sm border overflow-hidden">
        {loading ? (
          <div className="p-8 text-center text-gray-500">Loading...</div>
        ) : filtered.length === 0 ? (
          <div className="p-8 text-center text-gray-500">No exercises found.</div>
        ) : (
          <table className="w-full">
            <thead className="bg-gray-50 border-b">
              <tr>
                <th className="px-4 py-3 text-left">
                  <input
                    type="checkbox"
                    checked={selectedIds.size === filtered.length && filtered.length > 0}
                    onChange={toggleSelectAll}
                    className="h-4 w-4 rounded border-gray-300"
                  />
                </th>
                <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Exercise</th>
                <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Archetype</th>
                <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Profile</th>
                <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Axes</th>
                <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-200">
              {filtered.map((ex) => (
                <tr key={ex.id} className="hover:bg-gray-50">
                  <td className="px-4 py-3">
                    <input
                      type="checkbox"
                      checked={selectedIds.has(ex.id)}
                      onChange={() => toggleSelect(ex.id)}
                      className="h-4 w-4 rounded border-gray-300"
                    />
                  </td>
                  <td className="px-4 py-3">
                    <p className="font-medium text-gray-900">{ex.name.en}</p>
                    <p className="text-xs text-gray-500">{ex.slug}</p>
                  </td>
                  <td className="px-4 py-3">
                    {ex.hasProfile ? (
                      <Badge variant={ARCHETYPE_BADGE[ex.profile!.archetype] || 'default'}>
                        {ARCHETYPE_LABELS[ex.profile!.archetype] || ex.profile!.archetype}
                      </Badge>
                    ) : ex.archetype ? (
                      <span className="text-xs text-gray-400">{ARCHETYPE_LABELS[ex.archetype] || ex.archetype}</span>
                    ) : (
                      <select
                        className="text-xs border rounded px-2 py-1"
                        defaultValue=""
                        onChange={(e) => {
                          if (e.target.value) handleSetArchetype(ex.id, e.target.value);
                        }}
                      >
                        <option value="">Assign...</option>
                        {Object.entries(ARCHETYPE_LABELS).map(([k, v]) => (
                          <option key={k} value={k}>{v}</option>
                        ))}
                      </select>
                    )}
                  </td>
                  <td className="px-4 py-3">
                    {ex.hasProfile ? (
                      <Badge variant={ex.profile!.isAutoGenerated ? 'default' : 'primary'}>
                        {ex.profile!.isAutoGenerated ? 'Auto' : 'Custom'}
                      </Badge>
                    ) : (
                      <span className="text-xs text-orange-500 font-medium">Missing</span>
                    )}
                  </td>
                  <td className="px-4 py-3">
                    {ex.profile?.allowedAxes ? (
                      <div className="flex gap-1 flex-wrap">
                        {(ex.profile.allowedAxes as string[]).map((axis) => (
                          <span key={axis} className="text-xs bg-gray-100 text-gray-600 px-1.5 py-0.5 rounded">
                            {axis}
                          </span>
                        ))}
                      </div>
                    ) : (
                      <span className="text-xs text-gray-400">—</span>
                    )}
                  </td>
                  <td className="px-4 py-3 text-right">
                    <button
                      onClick={() => router.push(`/admin/exercise-progression/${ex.id}`)}
                      className="text-blue-600 hover:text-blue-800 text-sm font-medium"
                    >
                      {ex.hasProfile ? 'Configure' : 'Setup'}
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  );
}
