'use client';

import { useEffect, useState, useCallback } from 'react';
import { useRouter } from 'next/navigation';
import { toast } from 'sonner';
import { Button, Badge, Select, Checkbox } from '@/components/ui';
import { DataTable, FilterBar, PageHeader, StatusBadge, type DataTableColumn } from '@/components/common';

const ARCHETYPE_LABELS: Record<string, string> = {
  weighted_strength: 'Weighted Strength',
  bodyweight_dynamic: 'Bodyweight Dynamic',
  isometric_hold: 'Isometric Hold',
  mobility_rom: 'Mobility / ROM',
  motor_control: 'Motor Control',
};

const ARCHETYPE_COLORS: Record<string, 'primary' | 'purple' | 'teal' | 'default'> = {
  weighted_strength: 'primary',
  bodyweight_dynamic: 'purple',
  isometric_hold: 'teal',
  mobility_rom: 'default',
  motor_control: 'default',
};

const ARCHETYPE_OPTIONS = [
  { value: '', label: 'All Archetypes' },
  ...Object.entries(ARCHETYPE_LABELS).map(([value, label]) => ({ value, label })),
];

const PROFILE_STATUS_OPTIONS = [
  { value: '', label: 'All profile statuses' },
  { value: 'has_profile', label: 'Has Profile' },
  { value: 'no_profile', label: 'Missing Profile' },
];

interface ExerciseWithProfile {
  id: string;
  name: { en: string; ar: string };
  slug: string;
  archetype: string | null;
  hasProfile: boolean;
  profile: {
    id: string;
    archetype: string;
    isAutoGenerated: boolean;
    allowedAxes: string[];
  } | null;
}

export default function ExerciseProgressionPage() {
  const router = useRouter();
  const [exercises, setExercises] = useState<ExerciseWithProfile[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [filterArchetype, setFilterArchetype] = useState('');
  const [filterStatus, setFilterStatus] = useState('');
  const [bulkArchetype, setBulkArchetype] = useState('');
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set());
  const [saving, setSaving] = useState(false);

  const fetchData = useCallback(async () => {
    setLoading(true);
    try {
      const url = `/api/admin/exercise-progression/exercises${search ? `?search=${encodeURIComponent(search)}` : ''}`;
      const res = await fetch(url);
      const data = await res.json();
      if (data.success) setExercises(data.data);
    } catch (error) {
      console.error('Error fetching data:', error);
    } finally {
      setLoading(false);
    }
  }, [search]);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  const handleSetArchetype = async (exerciseId: string, archetype: string) => {
    try {
      const res = await fetch(`/api/admin/exercise-progression/${exerciseId}/archetype`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ archetype }),
      });
      const data = await res.json();
      if (data.success) {
        toast.success('Archetype updated');
        fetchData();
      } else {
        toast.error(data.error || 'Failed to set archetype');
      }
    } catch (error) {
      console.error('Error setting archetype:', error);
    }
  };

  const handleBulkGenerate = async () => {
    if (!bulkArchetype || selectedIds.size === 0) return;
    setSaving(true);
    try {
      const res = await fetch('/api/admin/exercise-progression/bulk-generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ exerciseIds: Array.from(selectedIds), archetype: bulkArchetype }),
      });
      const data = await res.json();
      if (data.success) {
        setSelectedIds(new Set());
        setBulkArchetype('');
        toast.success('Progression profiles generated');
        fetchData();
      } else {
        toast.error(data.error || 'Failed to bulk generate');
      }
    } catch (error) {
      console.error('Error in bulk generate:', error);
    } finally {
      setSaving(false);
    }
  };

  const toggleSelect = (id: string) => {
    setSelectedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  };

  const filtered = exercises.filter((ex) => {
    if (filterArchetype && ex.profile?.archetype !== filterArchetype) return false;
    if (filterStatus === 'has_profile' && !ex.hasProfile) return false;
    if (filterStatus === 'no_profile' && ex.hasProfile) return false;
    return true;
  });

  const toggleSelectAll = () => {
    if (selectedIds.size === filtered.length) {
      setSelectedIds(new Set());
    } else {
      setSelectedIds(new Set(filtered.map((e) => e.id)));
    }
  };

  const stats = {
    total: exercises.length,
    withProfile: exercises.filter((e) => e.hasProfile).length,
    withoutProfile: exercises.filter((e) => !e.hasProfile).length,
  };

  const allFilteredSelected = filtered.length > 0 && selectedIds.size === filtered.length;

  const columns: DataTableColumn<ExerciseWithProfile>[] = [
    {
      key: 'select',
      header: <Checkbox checked={allFilteredSelected} onCheckedChange={toggleSelectAll} aria-label="Select all exercises" />,
      cell: (exercise) => (
        <Checkbox
          checked={selectedIds.has(exercise.id)}
          onCheckedChange={() => toggleSelect(exercise.id)}
          aria-label={`Select ${exercise.name?.en || exercise.slug}`}
        />
      ),
      className: 'w-10',
      headerClassName: 'w-10',
    },
    {
      key: 'exercise',
      header: 'Exercise',
      cell: (exercise) => (
        <div className="min-w-[240px]">
          <p className="font-medium">{exercise.name?.en || exercise.slug}</p>
          <p className="text-xs text-muted-foreground">{exercise.slug}</p>
        </div>
      ),
    },
    {
      key: 'archetype',
      header: 'Archetype',
      cell: (exercise) =>
        exercise.hasProfile && exercise.profile ? (
          <Badge variant={ARCHETYPE_COLORS[exercise.profile.archetype] || 'secondary'}>
            {ARCHETYPE_LABELS[exercise.profile.archetype] || exercise.profile.archetype}
          </Badge>
        ) : exercise.archetype ? (
          <span className="text-xs text-muted-foreground">{ARCHETYPE_LABELS[exercise.archetype] || exercise.archetype}</span>
        ) : (
          <Select
            value=""
            onChange={(event) => {
              if (event.target.value) handleSetArchetype(exercise.id, event.target.value);
            }}
            options={[{ value: '', label: 'Assign...' }, ...Object.entries(ARCHETYPE_LABELS).map(([value, label]) => ({ value, label }))]}
            className="h-8 text-xs"
          />
        ),
    },
    {
      key: 'profile',
      header: 'Profile',
      cell: (exercise) =>
        exercise.hasProfile ? (
          <StatusBadge status={exercise.profile?.isAutoGenerated ? 'auto' : 'custom'} />
        ) : (
          <StatusBadge status="pending" label="Missing" />
        ),
    },
    {
      key: 'axes',
      header: 'Axes',
      cell: (exercise) =>
        exercise.profile?.allowedAxes ? (
          <div className="flex flex-wrap gap-1">
            {exercise.profile.allowedAxes.map((axis) => (
              <Badge key={axis} variant="secondary" size="sm">
                {axis}
              </Badge>
            ))}
          </div>
        ) : (
          <span className="text-xs text-muted-foreground">-</span>
        ),
    },
    {
      key: 'actions',
      header: <span className="sr-only">Actions</span>,
      headerClassName: 'text-right',
      className: 'text-right',
      cell: (exercise) => (
        <Button
          type="button"
          variant="ghost"
          size="sm"
          onClick={() => router.push(`/admin/exercise-progression/${exercise.id}`)}
        >
          {exercise.hasProfile ? 'Configure' : 'Setup'}
        </Button>
      ),
    },
  ];

  return (
    <div className="space-y-6">
      <PageHeader
        title="Exercise Progression"
        description="Manage scientific progression profiles and the single source of truth for exercise progression."
      />

      {/* Stats */}
      <div className="grid grid-cols-3 gap-4">
        <div className="rounded-xl border bg-card p-4 shadow-sm">
          <p className="text-sm text-muted-foreground">Total Exercises</p>
          <p className="text-2xl font-bold">{stats.total}</p>
        </div>
        <div className="rounded-xl border bg-card p-4 shadow-sm">
          <p className="text-sm text-muted-foreground">With Profile</p>
          <p className="text-2xl font-bold text-success">{stats.withProfile}</p>
        </div>
        <div className="rounded-xl border bg-card p-4 shadow-sm">
          <p className="text-sm text-muted-foreground">Missing Profile</p>
          <p className="text-2xl font-bold text-warning">{stats.withoutProfile}</p>
        </div>
      </div>

      <FilterBar
        searchValue={search}
        searchPlaceholder="Search by slug..."
        onSearchChange={setSearch}
        selects={[
          { id: 'archetype', value: filterArchetype, onChange: setFilterArchetype, options: ARCHETYPE_OPTIONS },
          { id: 'status', value: filterStatus, onChange: setFilterStatus, options: PROFILE_STATUS_OPTIONS },
        ]}
        onReset={() => {
          setSearch('');
          setFilterArchetype('');
          setFilterStatus('');
        }}
      />

      {/* Bulk Actions */}
      {selectedIds.size > 0 && (
        <div className="flex flex-wrap items-center gap-4 rounded-xl border bg-card p-4 shadow-sm">
          <span className="text-sm font-medium">
            {selectedIds.size} exercise(s) selected
          </span>
          <Select
            value={bulkArchetype}
            onChange={(e) => setBulkArchetype(e.target.value)}
            options={[{ value: '', label: 'Select Archetype...' }, ...Object.entries(ARCHETYPE_LABELS).map(([value, label]) => ({ value, label }))]}
            className="w-56"
          />
          <Button
            onClick={handleBulkGenerate}
            disabled={!bulkArchetype || saving}
            size="sm"
          >
            {saving ? 'Generating...' : 'Generate Profiles'}
          </Button>
        </div>
      )}

      <DataTable
        columns={columns}
        data={filtered}
        getRowKey={(exercise) => exercise.id}
        loading={loading}
        emptyTitle="No exercises found"
        emptyDescription="Adjust search or filters to find progression profiles."
      />
    </div>
  );
}
