# Generates injectable markdown stats for UI/UX docs (WS-7).
# Usage: .\scripts\generate-docs-stats.ps1 [-OutputPath <path>]

param(
    [string]$OutputPath = (Join-Path $PSScriptRoot "..\..\Docs\02-Roadmaps-And-Plans\UI-UX\generated\Docs-Stats-Snapshot.md")
)

$ErrorActionPreference = "Stop"
$androidPoc = Split-Path $PSScriptRoot -Parent
Set-Location $androidPoc

function Get-StringKeysFromXml {
    param([string]$Path)
    $content = Get-Content -LiteralPath $Path -Raw -Encoding UTF8
    [regex]::Matches($content, '<string name="([^"]+)"') |
        ForEach-Object { $_.Groups[1].Value }
}

$enXml = "core\resources\src\commonMain\composeResources\values\strings.xml"
$arXml = "core\resources\src\commonMain\composeResources\values-ar\strings.xml"

$enKeys = [System.Collections.Generic.HashSet[string]]::new([string[]](Get-StringKeysFromXml $enXml))
$arKeys = [System.Collections.Generic.HashSet[string]]::new([string[]](Get-StringKeysFromXml $arXml))

$missingInAr = @($enKeys | Where-Object { -not $arKeys.Contains($_) } | Sort-Object)
$missingInEn = @($arKeys | Where-Object { -not $enKeys.Contains($_) } | Sort-Object)
$matched = ($enKeys.Count -eq $arKeys.Count) -and ($missingInAr.Count -eq 0) -and ($missingInEn.Count -eq 0)
$matchLabel = if ($matched) { "matched" } else { "MISMATCH" }

$kmpModules = @(
    ":shared",
    ":core:resources",
    ":core:designsystem",
    ":core:network",
    ":core:data",
    ":core:training-engine",
    ":feature:explore",
    ":feature:home",
    ":feature:train",
    ":feature:reports",
    ":feature:library",
    ":feature:account",
    ":feature:shell"
)

$testCounts = [ordered]@{}
$testTotal = 0
foreach ($module in $kmpModules) {
    $gradlePath = $module.TrimStart(":") -replace ":", "\"
    $roots = @(
        (Join-Path $gradlePath "src\commonTest"),
        (Join-Path $gradlePath "src\androidUnitTest")
    )
    $count = 0
    foreach ($root in $roots) {
        if (Test-Path $root) {
            $testFiles = Get-ChildItem -Path $root -Recurse -Filter "*Test.kt" -File -ErrorAction SilentlyContinue
            foreach ($testFile in $testFiles) {
                $count += ([regex]::Matches((Get-Content -LiteralPath $testFile.FullName -Raw -Encoding UTF8), '@Test\b')).Count
            }
        }
    }
    $testCounts[$module] = $count
    $testTotal += $count
}

$dsComponentsDir = "core\designsystem\src\commonMain\kotlin\com\movit\designsystem\components"
$movitComponentFiles = @(Get-ChildItem -Path $dsComponentsDir -Filter "Movit*.kt" -File -ErrorAction SilentlyContinue)
$movitComposableCount = 0
foreach ($ktFile in $movitComponentFiles) {
    $text = Get-Content -LiteralPath $ktFile.FullName -Raw -Encoding UTF8
    $movitComposableCount += ([regex]::Matches($text, '@Composable[\s\S]*?fun\s+Movit\w*')).Count
}

$featureKotlin = Get-ChildItem -Path "feature" -Recurse -Filter "*.kt" |
    Where-Object { $_.FullName -match '\\src\\commonMain\\' }
$lifecycleAware = 0
$legacyCollect = 0
foreach ($file in $featureKotlin) {
    $text = Get-Content -LiteralPath $file.FullName -Raw -Encoding UTF8
    $lifecycleAware += ([regex]::Matches($text, 'collectAsStateWithLifecycle\s*\(')).Count
    $legacyCollect += ([regex]::Matches($text, '(?<![\w])collectAsState\s*\(')).Count
}

$generatedAt = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("<!-- docs:stats:start -->")
[void]$sb.AppendLine("<!-- Generated by android-poc/scripts/generate-docs-stats.ps1. Do not edit manually. -->")
[void]$sb.AppendLine("<!-- Regenerate: cd android-poc; .\gradlew.bat docsStats -->")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("# Docs Stats Snapshot")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("Last generated: **$generatedAt** (from ``android-poc``)")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("## i18n keys (core:resources)")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("| Metric | Value |")
[void]$sb.AppendLine("|--------|-------|")
[void]$sb.AppendLine("| ``values/strings.xml`` (en) | **$($enKeys.Count)** |")
[void]$sb.AppendLine("| ``values-ar/strings.xml`` (ar) | **$($arKeys.Count)** |")
[void]$sb.AppendLine("| ar/en parity | **$matchLabel** |")

if (-not $matched) {
    [void]$sb.AppendLine("")
    if ($missingInAr.Count -gt 0) {
        [void]$sb.AppendLine("- missing in ar: $($missingInAr -join ', ')")
    }
    if ($missingInEn.Count -gt 0) {
        [void]$sb.AppendLine("- missing in en: $($missingInEn -join ', ')")
    }
}

[void]$sb.AppendLine("")
[void]$sb.AppendLine("## Unit tests (KMP, @Test in commonTest + androidUnitTest)")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("| Module | Count |")
[void]$sb.AppendLine("|--------|-------|")

foreach ($entry in $testCounts.GetEnumerator()) {
    if ($entry.Value -gt 0) {
        [void]$sb.AppendLine("| ``$($entry.Key)`` | $($entry.Value) |")
    }
}
[void]$sb.AppendLine("| **KMP total** | **$testTotal** |")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("> Legacy ``:app`` tests are excluded. Run Gradle ``testDebugUnitTest`` for full CI verification.")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("## Design System (core:designsystem)")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("| Metric | Value |")
[void]$sb.AppendLine("|--------|-------|")
[void]$sb.AppendLine("| ``Movit*.kt`` files in ``components/`` | **$($movitComponentFiles.Count)** |")
[void]$sb.AppendLine("| ``@Composable fun Movit*`` in ``components/`` | **$movitComposableCount** |")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("## State collection (feature routes)")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("| Metric | Value |")
[void]$sb.AppendLine("|--------|-------|")
[void]$sb.AppendLine("| ``collectAsStateWithLifecycle()`` | **$lifecycleAware** |")
[void]$sb.AppendLine("| ``collectAsState()`` | **$legacyCollect** |")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("> Page completion percentages: canonical source is [Page-Scorecards.md](../Page-Scorecards.md).")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("<!-- docs:stats:end -->")

$outputDir = Split-Path $OutputPath -Parent
if (-not (Test-Path $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
}

$content = $sb.ToString()
[System.IO.File]::WriteAllText($OutputPath, $content, [System.Text.UTF8Encoding]::new($false))

Write-Host "Wrote docs stats to: $OutputPath"
Write-Host "  en/ar keys: $($enKeys.Count)/$($arKeys.Count) matched=$matched"
Write-Host "  KMP tests: $testTotal"
Write-Host "  Movit component files: $($movitComponentFiles.Count); composables: $movitComposableCount"
