package com.trainingvalidator.poc.assessment.models

import com.trainingvalidator.poc.training.models.LocalizedText

/**
 * Recommendation - Actionable training recommendation based on assessment results.
 * 
 * Generated by the Prescription layer of the AssessmentEngine.
 * Follows the Corrective Exercise Continuum (NASM):
 * 1. Inhibit (foam rolling)
 * 2. Lengthen (stretching)
 * 3. Activate (isolated strengthening)
 * 4. Integrate (compound movement)
 */
data class Recommendation(
    val priority: Int,  // 1 = highest
    val phase: CorrectionPhase,
    val targetRegion: BodyRegion,
    val description: LocalizedText,
    val exerciseSlugs: List<String> = emptyList()
)

enum class CorrectionPhase(val labelAr: String, val labelEn: String) {
    INHIBIT("تثبيط", "Inhibit"),
    LENGTHEN("إطالة", "Lengthen"),
    ACTIVATE("تنشيط", "Activate"),
    INTEGRATE("دمج", "Integrate");

    fun getLabel(language: String = "en"): String =
        if (language == "ar") labelAr else labelEn
}
