package com.movit.resources

// JVM/unit-test fallback for Arabic when compose resources are unavailable.
internal val movitArabicStrings: Map<String, String> = mapOf(
    "program_flow_list_title" to "البرامج",
    "program_flow_loading" to "جاري تحميل البرامج…",
    "program_flow_empty_title" to "لا توجد برامج بعد",
    "program_flow_empty_message" to "تحقق من الاتصال وحاول مرة أخرى.",
    "program_flow_weeks_days" to "%1\$d أسابيع · %2\$d أيام/أسبوع",
    "program_flow_week_title" to "الأسبوع %1\$d",
    "program_flow_open_today" to "فتح جلسة اليوم",
    "program_flow_view_week_report" to "عرض تقرير الأسبوع",
    "program_flow_week_report_title" to "تقرير الأسبوع %1\$d",
    "program_flow_week_report_fallback" to "التقرير الأسبوعي",
    "program_flow_metric_sessions" to "الجلسات",
    "program_flow_metric_form" to "متوسط الأداء",
    "program_flow_metric_reps" to "التكرارات",
    "program_flow_daily_form" to "درجات الأداء اليومية",
    "program_flow_share_report" to "مشاركة التقرير",
    "program_flow_share_coming_soon" to "مشاركة التقرير قريباً.",
    "program_flow_status_done" to "مكتمل",
    "program_flow_status_today" to "اليوم",
    "program_flow_status_planned" to "مجدول",
    "program_flow_status_rest" to "يوم راحة",
    "program_flow_a11y_day" to "اليوم %1\$d، %2\$s. %3\$s. %4\$s",
    "program_flow_a11y_chart" to "مخطط درجات الأداء اليومية",
    "program_flow_load_failed" to "تعذّر تحميل البرامج.",
    "program_flow_program_not_found" to "البرنامج غير موجود.",
    "program_not_found" to "البرنامج غير موجود.",
    "program_no_upcoming_session" to "لم يُعثر على جلسة قادمة لهذا البرنامج.",
    "program_sign_in_to_enroll" to "سجّل الدخول للاشتراك في برنامج.",
    "program_sign_in_to_save_edits" to "سجّل الدخول لحفظ تعديلات البرنامج.",
    "program_started" to "بدأ",
    "program_started_today" to "بدأ اليوم",
    "program_synced_today" to "تمت المزامنة اليوم",
    "program_week_offline_download_action" to "تحميل الأسبوع للاستخدام دون اتصال",
    "program_week_offline_downloading" to "جاري تحميل الأسبوع…",
    "program_week_offline_ready" to "جاهز دون اتصال ✓",
    "program_week_offline_sign_in_required" to "سجّل الدخول لتحميل هذا الأسبوع للتدريب دون اتصال.",
    "program_week_offline_enroll_first" to "ابدأ البرنامج قبل التحميل للاستخدام دون اتصال.",
    "program_week_offline_program_not_loaded" to "بيانات البرنامج غير محمّلة بعد. اتصل بالإنترنت وحاول مرة أخرى.",
    "program_week_offline_week_unavailable" to "هذا الأسبوع غير متاح في البرنامج بعد.",
    "program_week_offline_download_failed" to "تعذّر تحميل هذا الأسبوع. تحقق من الاتصال وحاول مرة أخرى.",
    "billing_load_plans_failed" to "تعذّر تحميل الخطط.",
    "billing_load_status_failed" to "تعذّر تحميل حالة الاشتراك.",
    "billing_empty_status_response" to "استجابة الحالة فارغة.",
    "billing_checkout_failed" to "فشل إتمام الدفع.",
    "billing_empty_checkout_response" to "استجابة الدفع فارغة.",
    "billing_checkout_lookup_failed" to "فشل البحث عن عملية الدفع.",
    "billing_purchase_verification_failed" to "فشل التحقق من الشراء.",
    "billing_empty_verification_response" to "استجابة التحقق فارغة.",
    "billing_cancel_failed" to "فشل الإلغاء.",
    "billing_empty_cancel_response" to "استجابة الإلغاء فارغة.",
    "program_flow_active_badge" to "نشط",
    "program_flow_chip_all" to "الكل",
    "program_flow_search" to "ابحث عن البرامج",
    "program_flow_list_count" to "%1\$d برامج",
    "program_flow_list_count_filtered" to "%1\$d من %2\$d برامج",
    "program_flow_day_short" to "اليوم %1\$d",
    "program_flow_week_subtitle" to "%1\$d تمارين · %2\$d راحة",
    "program_flow_day_today_detail" to "اليوم · %1\$d تمارين · %2\$d د",
    "program_flow_day_completed" to "مكتمل",
    "program_flow_report_hero_eyebrow" to "ملخص الأسبوع %1\$d",
    "program_flow_report_hero_title" to "أسبوع رائع!",
    "program_flow_report_hero_subtitle" to "أكملت %1\$d من %2\$d جلسات مخططة.",
    "report_detail_done" to "تم",
    "report_detail_preview_personal_best" to "أفضل إنجاز شخصي",
    "report_detail_preview_insight_title" to "ثبات ممتاز في العمق",
    "report_detail_preview_insight_message" to "خط الورك بقي تحت مستوى الركبة في 95% من التكرارات.",
    "report_detail_preview_joint_knees" to "الركبتان",
    "report_detail_preview_joint_hips" to "الوركان",
    "report_detail_preview_joint_spine" to "العمود الفقري",
    "report_detail_preview_tip1_title" to "شدّ العضلات الأساسية مبكراً",
    "report_detail_preview_tip1_message" to "أثناء النزول، فعّل العضلات الأساسية قبل ميل الورك بـ 0.5 ثانية لحماية أسفل الظهر.",
    "report_detail_preview_tip2_title" to "حافظ على محاذاة الركبتين مع أصابع القدم",
    "report_detail_preview_tip2_message" to "انحراف طفيف للداخل في المجموعة 4 — ركّز على دفع الركبتين للخارج.",
    "report_detail_preview_fatigue_message" to "انخفض الأداء 6% من المجموعة 1 إلى 4 — ضمن المعدل الطبيعي.",
    "program_edit_day_sync_required" to "اتصل بالإنترنت وزامن هذا اليوم قبل تعديله.",
    "program_edit_enroll_first" to "ابدأ هذا البرنامج أولاً قبل تعديل جلساته.",
    "program_edit_day_no_sessions" to "لا توجد جلسات قابلة للتعديل في هذا اليوم.",
)
