'use client';

import { useEffect, useState, useCallback } from 'react';
import { useParams, useRouter } from 'next/navigation';
import {
  Input,
  Select,
  Label,
  Button,
  Card,
  Badge,
} from '@/components/ui';

const ARCHETYPE_OPTIONS = [
  { value: 'weighted_strength', label: 'Weighted Strength' },
  { value: 'bodyweight_dynamic', label: 'Bodyweight Dynamic' },
  { value: 'isometric_hold', label: 'Isometric Hold' },
  { value: 'mobility_rom', label: 'Mobility ROM' },
  { value: 'motor_control', label: 'Motor Control' },
];

const ARCHETYPE_DESCRIPTIONS: Record<string, string> = {
  weighted_strength: 'Progressive overload with external load. Priority: reps → load → sets.',
  bodyweight_dynamic: 'Bodyweight-only. Priority: reps → difficulty ladder.',
  isometric_hold: 'Static holds. Priority: duration → difficulty ladder.',
  mobility_rom: 'Range of motion focus. Priority: reps → duration. Higher streak requirement.',
  motor_control: 'Balance & coordination. Priority: reps → difficulty. Strict quality gate.',
};

const ALL_AXES = ['reps', 'load', 'duration', 'sets', 'difficulty'];

interface AxisConfig {
  default: number;
  floor: number;
  cap: number;
  step: number;
}

interface QualityGate {
  minFormScore: number;
  minCompletionRate: number;
  minROM?: number;
  minSymmetry?: number;
  minStability?: number;
}

interface PromotionPolicy {
  requiredStreakSessions: number;
}

interface RegressionPolicy {
  maxFormScore: number;
}

interface ValidationResult {
  valid: boolean;
  errors: string[];
}

interface Profile {
  id: string;
  exerciseId: string;
  archetype: string;
  allowedAxes: string[];
  priorityOrder: string[];
  repAxis: AxisConfig | null;
  loadAxis: AxisConfig | null;
  durationAxis: AxisConfig | null;
  setAxis: AxisConfig | null;
  difficultyLadder: string[] | null;
  qualityGate: QualityGate;
  promotionPolicy: PromotionPolicy;
  regressionPolicy: RegressionPolicy;
  isAutoGenerated: boolean;
  validation?: ValidationResult;
  exercise: { id: string; name: { en: string; ar: string }; slug: string };
}

const defaultAxis = (): AxisConfig => ({ default: 0, floor: 0, cap: 0, step: 1 });

function normalizeQualityGate(q: unknown): QualityGate {
  if (q && typeof q === 'object' && 'minFormScore' in q) {
    const g = q as QualityGate;
    return {
      minFormScore: Number(g.minFormScore) || 70,
      minCompletionRate: Number(g.minCompletionRate) || 85,
      ...(g.minROM != null ? { minROM: Number(g.minROM) } : {}),
      ...(g.minSymmetry != null ? { minSymmetry: Number(g.minSymmetry) } : {}),
      ...(g.minStability != null ? { minStability: Number(g.minStability) } : {}),
    };
  }
  return { minFormScore: 70, minCompletionRate: 85 };
}

function normalizePromotionPolicy(p: unknown): PromotionPolicy {
  if (
    p &&
    typeof p === 'object' &&
    'requiredStreakSessions' in p &&
    typeof (p as PromotionPolicy).requiredStreakSessions === 'number'
  ) {
    return p as PromotionPolicy;
  }
  return { requiredStreakSessions: 2 };
}

function normalizeRegressionPolicy(p: unknown): RegressionPolicy {
  if (
    p &&
    typeof p === 'object' &&
    'maxFormScore' in p &&
    typeof (p as RegressionPolicy).maxFormScore === 'number'
  ) {
    return p as RegressionPolicy;
  }
  return { maxFormScore: 55 };
}

export default function ExerciseProgressionDetailPage() {
  const params = useParams();
  const router = useRouter();
  const exerciseId = params.exerciseId as string;

  const [profile, setProfile] = useState<Profile | null>(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [archetype, setArchetype] = useState('');

  const [allowedAxes, setAllowedAxes] = useState<string[]>([]);
  const [priorityOrder, setPriorityOrder] = useState<string[]>([]);
  const [repAxis, setRepAxis] = useState<AxisConfig | null>(null);
  const [loadAxis, setLoadAxis] = useState<AxisConfig | null>(null);
  const [durationAxis, setDurationAxis] = useState<AxisConfig | null>(null);
  const [setAxis, setSetAxis] = useState<AxisConfig | null>(null);
  const [difficultyLadder, setDifficultyLadder] = useState<string[]>([]);
  const [qualityGate, setQualityGate] = useState<QualityGate>({ minFormScore: 70, minCompletionRate: 85 });
  const [promotionPolicy, setPromotionPolicy] = useState<PromotionPolicy>({ requiredStreakSessions: 2 });
  const [regressionPolicy, setRegressionPolicy] = useState<RegressionPolicy>({ maxFormScore: 55 });
  const [validation, setValidation] = useState<ValidationResult | null>(null);

  const fetchProfile = useCallback(async () => {
    setLoading(true);
    try {
      const res = await fetch(`/api/admin/exercise-progression/${exerciseId}`);
      const data = await res.json();
      if (data.success && data.data) {
        const p = data.data as Profile;
        setProfile(p);
        setArchetype(p.archetype);
        setAllowedAxes(p.allowedAxes || []);
        setPriorityOrder(p.priorityOrder || []);
        setRepAxis(p.repAxis);
        setLoadAxis(p.loadAxis);
        setDurationAxis(p.durationAxis);
        setSetAxis(p.setAxis);
        setDifficultyLadder(Array.isArray(p.difficultyLadder) ? p.difficultyLadder : []);
        setQualityGate(normalizeQualityGate(p.qualityGate));
        setPromotionPolicy(normalizePromotionPolicy(p.promotionPolicy));
        setRegressionPolicy(normalizeRegressionPolicy(p.regressionPolicy));
        if (p.validation) setValidation(p.validation);
      }
    } catch (error) {
      console.error('Error fetching profile:', error);
    } finally {
      setLoading(false);
    }
  }, [exerciseId]);

  useEffect(() => {
    fetchProfile();
  }, [fetchProfile]);

  const handleSetArchetype = async (newArchetype: string) => {
    if (!newArchetype) return;
    setSaving(true);
    try {
      const res = await fetch(`/api/admin/exercise-progression/${exerciseId}/archetype`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ archetype: newArchetype }),
      });
      const data = await res.json();
      if (data.success) {
        setArchetype(newArchetype);
        fetchProfile();
      }
    } catch (error) {
      console.error('Error setting archetype:', error);
    } finally {
      setSaving(false);
    }
  };

  const handleRegenerate = async () => {
    if (!archetype) return;
    if (!confirm('This will reset the profile to archetype defaults. Continue?')) return;
    setSaving(true);
    try {
      const res = await fetch(`/api/admin/exercise-progression/${exerciseId}/generate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ archetype }),
      });
      const data = await res.json();
      if (data.success) fetchProfile();
    } catch (error) {
      console.error('Error regenerating profile:', error);
    } finally {
      setSaving(false);
    }
  };

  const handleSave = async () => {
    setSaving(true);
    try {
      const payload: Record<string, unknown> = {
        allowedAxes,
        priorityOrder,
        qualityGate,
        promotionPolicy,
        regressionPolicy,
      };
      if (allowedAxes.includes('reps')) payload.repAxis = repAxis;
      if (allowedAxes.includes('load')) payload.loadAxis = loadAxis;
      if (allowedAxes.includes('duration')) payload.durationAxis = durationAxis;
      if (allowedAxes.includes('sets')) payload.setAxis = setAxis;
      if (allowedAxes.includes('difficulty') && difficultyLadder.length > 0) {
        payload.difficultyLadder = difficultyLadder;
      }

      const res = await fetch(`/api/admin/exercise-progression/${exerciseId}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      });
      const data = await res.json();
      if (data.success) {
        fetchProfile();
      } else {
        alert(data.error || 'Failed to save profile');
      }
    } catch (error) {
      console.error('Error saving profile:', error);
      alert('Failed to save profile');
    } finally {
      setSaving(false);
    }
  };

  const toggleAxis = (axis: string) => {
    setAllowedAxes((prev) => {
      const next = prev.includes(axis)
        ? prev.filter((a) => a !== axis)
        : [...prev, axis];
      setPriorityOrder((po) => po.filter((a) => next.includes(a)).concat(next.filter((a) => !po.includes(a))));
      return next;
    });
    if (!allowedAxes.includes(axis)) {
      if (axis === 'reps' && !repAxis) setRepAxis(defaultAxis());
      if (axis === 'load' && !loadAxis) setLoadAxis(defaultAxis());
      if (axis === 'duration' && !durationAxis) setDurationAxis(defaultAxis());
      if (axis === 'sets' && !setAxis) setSetAxis(defaultAxis());
      if (axis === 'difficulty' && difficultyLadder.length === 0) setDifficultyLadder(['beginner', 'intermediate', 'advanced']);
    }
  };

  const movePriority = (idx: number, dir: -1 | 1) => {
    const newIdx = idx + dir;
    if (newIdx < 0 || newIdx >= priorityOrder.length) return;
    setPriorityOrder((prev) => {
      const next = [...prev];
      [next[idx], next[newIdx]] = [next[newIdx], next[idx]];
      return next;
    });
  };

  const updateAxisField = (
    setter: React.Dispatch<React.SetStateAction<AxisConfig | null>>,
    field: keyof AxisConfig,
    value: number,
  ) => {
    setter((prev) => prev ? { ...prev, [field]: value } : { ...defaultAxis(), [field]: value });
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="animate-spin h-8 w-8 border-4 border-blue-600 border-t-transparent rounded-full" />
      </div>
    );
  }

  const renderAxisConfig = (
    label: string,
    config: AxisConfig | null,
    setter: React.Dispatch<React.SetStateAction<AxisConfig | null>>,
    unit?: string,
  ) => {
    if (!config) return null;
    const u = unit ? ` (${unit})` : '';
    return (
      <div className="p-4 bg-gray-50 rounded-lg space-y-3">
        <h4 className="text-sm font-semibold text-gray-700">{label}{u}</h4>
        <div className="grid grid-cols-4 gap-3">
          <div>
            <Label>Default</Label>
            <Input type="number" step="any" value={config.default} onChange={(e) => updateAxisField(setter, 'default', Number(e.target.value))} />
          </div>
          <div>
            <Label>Floor</Label>
            <Input type="number" step="any" value={config.floor} onChange={(e) => updateAxisField(setter, 'floor', Number(e.target.value))} />
          </div>
          <div>
            <Label>Cap</Label>
            <Input type="number" step="any" value={config.cap} onChange={(e) => updateAxisField(setter, 'cap', Number(e.target.value))} />
          </div>
          <div>
            <Label>Step</Label>
            <Input type="number" step="any" value={config.step} onChange={(e) => updateAxisField(setter, 'step', Number(e.target.value))} />
          </div>
        </div>
      </div>
    );
  };

  return (
    <div className="space-y-6 max-w-4xl">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <button onClick={() => router.back()} className="text-sm text-gray-500 hover:text-gray-700 mb-2 inline-block">
            &larr; Back to list
          </button>
          <h1 className="text-2xl font-bold text-gray-900">
            {profile?.exercise?.name?.en || 'Exercise Progression Profile'}
          </h1>
          <p className="text-gray-500 text-sm" dir="rtl">{profile?.exercise?.name?.ar || ''}</p>
        </div>
        <div className="flex gap-2 items-center">
          {profile && (
            <Badge variant={profile.isAutoGenerated ? 'primary' : 'default'}>
              {profile.isAutoGenerated ? 'Auto Generated' : 'Custom'}
            </Badge>
          )}
          {validation && !validation.valid && (
            <Badge variant="default">
              {validation.errors.length} issue(s)
            </Badge>
          )}
        </div>
      </div>

      {/* Validation Warnings */}
      {validation && !validation.valid && (
        <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
          <h3 className="text-sm font-semibold text-yellow-800 mb-2">Validation Issues</h3>
          <ul className="text-sm text-yellow-700 list-disc list-inside space-y-1">
            {validation.errors.map((err, i) => (
              <li key={i}>{err}</li>
            ))}
          </ul>
        </div>
      )}

      {/* Archetype Section */}
      <Card className="p-5 space-y-4">
        <h2 className="text-lg font-semibold text-gray-900">Archetype</h2>
        <div className="grid grid-cols-2 gap-4">
          <div>
            <Label>Exercise Archetype</Label>
            <Select
              value={archetype}
              onChange={(e) => handleSetArchetype(e.target.value)}
              options={ARCHETYPE_OPTIONS}
            />
          </div>
          <div className="flex items-end">
            <Button variant="outline" onClick={handleRegenerate} disabled={saving || !archetype}>
              Regenerate Defaults
            </Button>
          </div>
        </div>
        {archetype && (
          <p className="text-sm text-gray-600 bg-gray-50 p-3 rounded-lg">
            {ARCHETYPE_DESCRIPTIONS[archetype]}
          </p>
        )}
      </Card>

      {!profile ? (
        <Card className="p-8 text-center text-gray-500">
          <p>No profile found. Select an archetype above to generate a default profile.</p>
        </Card>
      ) : (
        <>
          {/* Axes Configuration */}
          <Card className="p-5 space-y-4">
            <h2 className="text-lg font-semibold text-gray-900">Progression Axes</h2>
            <p className="text-sm text-gray-500">Select which axes are active and set their priority order.</p>

            <div className="flex gap-3 flex-wrap">
              {ALL_AXES.map((axis) => (
                <label key={axis} className="flex items-center gap-2 px-3 py-1.5 border rounded-lg cursor-pointer hover:bg-gray-50">
                  <input
                    type="checkbox"
                    checked={allowedAxes.includes(axis)}
                    onChange={() => toggleAxis(axis)}
                    className="h-4 w-4 rounded border-gray-300 text-blue-600"
                  />
                  <span className="text-sm font-medium capitalize">{axis}</span>
                </label>
              ))}
            </div>

            {/* Priority Order */}
            {priorityOrder.length > 1 && (
              <div>
                <Label>Priority Order (first axis gets promoted first)</Label>
                <div className="space-y-1 mt-2">
                  {priorityOrder.map((axis, idx) => (
                    <div key={axis} className="flex items-center gap-2 px-3 py-2 bg-gray-50 rounded">
                      <span className="text-sm text-gray-400 w-6">{idx + 1}.</span>
                      <span className="text-sm font-medium capitalize flex-1">{axis}</span>
                      <button
                        onClick={() => movePriority(idx, -1)}
                        disabled={idx === 0}
                        className="text-gray-600 hover:text-gray-800 disabled:opacity-30 text-xs"
                      >
                        ▲
                      </button>
                      <button
                        onClick={() => movePriority(idx, 1)}
                        disabled={idx === priorityOrder.length - 1}
                        className="text-gray-600 hover:text-gray-800 disabled:opacity-30 text-xs"
                      >
                        ▼
                      </button>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </Card>

          {/* Axis Configs */}
          <Card className="p-5 space-y-4">
            <h2 className="text-lg font-semibold text-gray-900">Axis Configurations</h2>
            <p className="text-sm text-gray-500">Default starting value, floor (min), cap (max), and step increment for each axis.</p>

            {allowedAxes.includes('reps') && renderAxisConfig('Reps', repAxis, setRepAxis, 'reps')}
            {allowedAxes.includes('load') && renderAxisConfig('Load', loadAxis, setLoadAxis, 'kg')}
            {allowedAxes.includes('duration') && renderAxisConfig('Duration', durationAxis, setDurationAxis, 'seconds')}
            {allowedAxes.includes('sets') && renderAxisConfig('Sets', setAxis, setSetAxis, 'sets')}

            {allowedAxes.includes('difficulty') && (
              <div className="p-4 bg-gray-50 rounded-lg space-y-3">
                <h4 className="text-sm font-semibold text-gray-700">Difficulty Ladder</h4>
                <p className="text-xs text-gray-500">Ordered list of difficulty codes — user advances from first to last.</p>
                <div className="space-y-2">
                  {difficultyLadder.map((step, idx) => (
                    <div key={idx} className="flex items-center gap-2">
                      <span className="text-sm text-gray-400 w-6">{idx + 1}.</span>
                      <Input
                        value={step}
                        onChange={(e) => setDifficultyLadder((prev) => prev.map((s, i) => (i === idx ? e.target.value : s)))}
                        placeholder="e.g. beginner"
                      />
                      <Button
                        variant="ghost"
                        size="sm"
                        className="text-red-500 shrink-0"
                        onClick={() => setDifficultyLadder((prev) => prev.filter((_, i) => i !== idx))}
                      >
                        &times;
                      </Button>
                    </div>
                  ))}
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => setDifficultyLadder((prev) => [...prev, ''])}
                  >
                    Add Step
                  </Button>
                </div>
              </div>
            )}

            {allowedAxes.length === 0 && (
              <p className="text-sm text-orange-500">No axes selected. Enable at least one axis above.</p>
            )}
          </Card>

          {/* Quality Gate */}
          <Card className="p-5 space-y-4">
            <h2 className="text-lg font-semibold text-gray-900">Quality Gate</h2>
            <p className="text-sm text-gray-500">
              Minimum quality thresholds that must be met before any promotion is allowed.
              All active conditions must pass simultaneously.
            </p>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <Label>Min Form Score (%)</Label>
                <Input
                  type="number"
                  min={0}
                  max={100}
                  value={qualityGate.minFormScore}
                  onChange={(e) => setQualityGate((p) => ({ ...p, minFormScore: Number(e.target.value) }))}
                />
              </div>
              <div>
                <Label>Min Completion Rate (%)</Label>
                <Input
                  type="number"
                  min={0}
                  max={100}
                  value={qualityGate.minCompletionRate}
                  onChange={(e) => setQualityGate((p) => ({ ...p, minCompletionRate: Number(e.target.value) }))}
                />
              </div>
              <div>
                <Label>Min ROM (%, optional)</Label>
                <Input
                  type="number"
                  min={0}
                  max={100}
                  value={qualityGate.minROM ?? ''}
                  onChange={(e) => setQualityGate((p) => ({
                    ...p,
                    minROM: e.target.value ? Number(e.target.value) : undefined,
                  }))}
                  placeholder="Leave empty to skip"
                />
              </div>
              <div>
                <Label>Min Symmetry (%, optional)</Label>
                <Input
                  type="number"
                  min={0}
                  max={100}
                  value={qualityGate.minSymmetry ?? ''}
                  onChange={(e) => setQualityGate((p) => ({
                    ...p,
                    minSymmetry: e.target.value ? Number(e.target.value) : undefined,
                  }))}
                  placeholder="Leave empty to skip"
                />
              </div>
              <div>
                <Label>Min Stability (%, optional)</Label>
                <Input
                  type="number"
                  min={0}
                  max={100}
                  value={qualityGate.minStability ?? ''}
                  onChange={(e) => setQualityGate((p) => ({
                    ...p,
                    minStability: e.target.value ? Number(e.target.value) : undefined,
                  }))}
                  placeholder="Leave empty to skip"
                />
              </div>
            </div>
          </Card>

          {/* Promotion & Regression Policies */}
          <div className="grid grid-cols-2 gap-6">
            <Card className="p-5 space-y-4">
              <h2 className="text-lg font-semibold text-green-700">Promotion Policy</h2>
              <p className="text-sm text-gray-500">
                How many consecutive qualifying sessions are needed before promoting.
              </p>
              <div>
                <Label>Required Streak Sessions</Label>
                <Input
                  type="number"
                  min={1}
                  max={10}
                  value={promotionPolicy.requiredStreakSessions}
                  onChange={(e) => setPromotionPolicy({ requiredStreakSessions: Number(e.target.value) })}
                />
                <p className="text-xs text-gray-400 mt-1">
                  User must pass the quality gate for this many sessions in a row.
                </p>
              </div>
            </Card>

            <Card className="p-5 space-y-4">
              <h2 className="text-lg font-semibold text-red-700">Regression Policy</h2>
              <p className="text-sm text-gray-500">
                When form drops below this threshold, the engine automatically reduces the current axis.
              </p>
              <div>
                <Label>Max Form Score for Regression (%)</Label>
                <Input
                  type="number"
                  min={0}
                  max={100}
                  value={regressionPolicy.maxFormScore}
                  onChange={(e) => setRegressionPolicy({ maxFormScore: Number(e.target.value) })}
                />
                <p className="text-xs text-gray-400 mt-1">
                  If avg form score drops below this, the engine regresses the current axis value.
                </p>
              </div>
            </Card>
          </div>

          {/* Save */}
          <div className="flex justify-end gap-3 pb-8">
            <Button variant="outline" onClick={() => router.back()}>Cancel</Button>
            <Button onClick={handleSave} loading={saving}>Save Profile</Button>
          </div>
        </>
      )}
    </div>
  );
}
