'use client';

import { useEffect, useState, useCallback } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { Input, Select, Button, Card, Badge } from '@/components/ui';

interface AxisConfig {
  default: number;
  floor: number;
  cap: number;
  step: number;
}

interface ProfileData {
  id: string;
  exerciseId: string;
  archetype: string;
  allowedAxes: string[];
  priorityOrder: string[];
  repAxis: AxisConfig | null;
  loadAxis: AxisConfig | null;
  durationAxis: AxisConfig | null;
  setAxis: AxisConfig | null;
  difficultyLadder: string[] | null;
  qualityGate: { minFormScore: number; minCompletionRate: number; minROM?: number; minSymmetry?: number; minStability?: number };
  promotionPolicy: { requiredStreakSessions: number };
  regressionPolicy: { maxFormScore: number };
  isAutoGenerated: boolean;
  exercise: { id: string; name: { en: string; ar: string }; slug: string };
  validation: { valid: boolean; errors: string[] };
}

const ARCHETYPE_LABELS: Record<string, string> = {
  weighted_strength: 'Weighted Strength',
  bodyweight_dynamic: 'Bodyweight Dynamic',
  isometric_hold: 'Isometric Hold',
  mobility_rom: 'Mobility / ROM',
  motor_control: 'Motor Control',
};

const AXIS_LABELS: Record<string, string> = {
  reps: 'Reps',
  load: 'Load (kg)',
  duration: 'Duration (s)',
  sets: 'Sets',
  difficulty: 'Difficulty',
};

const ALL_AXES = ['reps', 'load', 'duration', 'sets', 'difficulty'];

export default function ExerciseProgressionDetailPage() {
  const params = useParams();
  const router = useRouter();
  const exerciseId = params.exerciseId as string;

  const [profile, setProfile] = useState<ProfileData | null>(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [selectedArchetype, setSelectedArchetype] = useState('');

  // Editable state
  const [allowedAxes, setAllowedAxes] = useState<string[]>([]);
  const [priorityOrder, setPriorityOrder] = useState<string[]>([]);
  const [repAxis, setRepAxis] = useState<AxisConfig>({ default: 8, floor: 5, cap: 12, step: 1 });
  const [loadAxis, setLoadAxis] = useState<AxisConfig>({ default: 0, floor: 0, cap: 200, step: 2.5 });
  const [durationAxis, setDurationAxis] = useState<AxisConfig>({ default: 15, floor: 5, cap: 45, step: 5 });
  const [setAxis, setSetAxis] = useState<AxisConfig>({ default: 3, floor: 2, cap: 5, step: 1 });
  const [difficultyLadder, setDifficultyLadder] = useState('beginner, intermediate, advanced');
  const [qualityGate, setQualityGate] = useState({ minFormScore: 70, minCompletionRate: 85, minROM: 0, minSymmetry: 0, minStability: 0 });
  const [promotionStreak, setPromotionStreak] = useState(2);
  const [regressionMaxScore, setRegressionMaxScore] = useState(55);

  const fetchProfile = useCallback(async () => {
    setLoading(true);
    try {
      const res = await fetch(`/api/admin/exercise-progression/${exerciseId}`);
      const data = await res.json();
      if (data.success && data.data) {
        setProfile(data.data);
        populateForm(data.data);
      }
    } catch (error) {
      console.error('Error fetching profile:', error);
    } finally {
      setLoading(false);
    }
  }, [exerciseId]);

  useEffect(() => { fetchProfile(); }, [fetchProfile]);

  function populateForm(p: ProfileData) {
    setSelectedArchetype(p.archetype);
    setAllowedAxes(p.allowedAxes || []);
    setPriorityOrder(p.priorityOrder || []);
    if (p.repAxis) setRepAxis(p.repAxis);
    if (p.loadAxis) setLoadAxis(p.loadAxis);
    if (p.durationAxis) setDurationAxis(p.durationAxis);
    if (p.setAxis) setSetAxis(p.setAxis);
    if (p.difficultyLadder) setDifficultyLadder(p.difficultyLadder.join(', '));
    if (p.qualityGate) {
      setQualityGate({
        minFormScore: p.qualityGate.minFormScore ?? 70,
        minCompletionRate: p.qualityGate.minCompletionRate ?? 85,
        minROM: p.qualityGate.minROM ?? 0,
        minSymmetry: p.qualityGate.minSymmetry ?? 0,
        minStability: p.qualityGate.minStability ?? 0,
      });
    }
    if (p.promotionPolicy) setPromotionStreak(p.promotionPolicy.requiredStreakSessions ?? 2);
    if (p.regressionPolicy) setRegressionMaxScore(p.regressionPolicy.maxFormScore ?? 55);
  }

  const handleGenerate = async () => {
    if (!selectedArchetype) return;
    setSaving(true);
    try {
      const res = await fetch(`/api/admin/exercise-progression/${exerciseId}/generate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ archetype: selectedArchetype }),
      });
      const data = await res.json();
      if (data.success) fetchProfile();
      else alert(data.error || 'Failed to generate profile');
    } catch (error) {
      console.error('Error generating profile:', error);
    } finally {
      setSaving(false);
    }
  };

  const handleSave = async () => {
    setSaving(true);
    try {
      const ladderArr = difficultyLadder.split(',').map((s) => s.trim()).filter(Boolean);
      const body: Record<string, unknown> = {
        allowedAxes,
        priorityOrder,
        qualityGate: {
          minFormScore: qualityGate.minFormScore,
          minCompletionRate: qualityGate.minCompletionRate,
          ...(qualityGate.minROM ? { minROM: qualityGate.minROM } : {}),
          ...(qualityGate.minSymmetry ? { minSymmetry: qualityGate.minSymmetry } : {}),
          ...(qualityGate.minStability ? { minStability: qualityGate.minStability } : {}),
        },
        promotionPolicy: { requiredStreakSessions: promotionStreak },
        regressionPolicy: { maxFormScore: regressionMaxScore },
      };

      if (allowedAxes.includes('reps')) body.repAxis = repAxis;
      if (allowedAxes.includes('load')) body.loadAxis = loadAxis;
      if (allowedAxes.includes('duration')) body.durationAxis = durationAxis;
      if (allowedAxes.includes('sets')) body.setAxis = setAxis;
      if (allowedAxes.includes('difficulty') && ladderArr.length > 0) body.difficultyLadder = ladderArr;

      const res = await fetch(`/api/admin/exercise-progression/${exerciseId}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      });
      const data = await res.json();
      if (data.success) {
        setProfile(data.data);
        populateForm(data.data);
      } else {
        alert(data.error || 'Failed to save');
      }
    } catch (error) {
      console.error('Error saving profile:', error);
    } finally {
      setSaving(false);
    }
  };

  const toggleAxis = (axis: string) => {
    setAllowedAxes((prev) => {
      const next = prev.includes(axis) ? prev.filter((a) => a !== axis) : [...prev, axis];
      setPriorityOrder((po) => po.filter((a) => next.includes(a)).concat(next.filter((a) => !po.includes(a))));
      return next;
    });
  };

  const moveAxisPriority = (axis: string, direction: 'up' | 'down') => {
    setPriorityOrder((prev) => {
      const idx = prev.indexOf(axis);
      if (idx === -1) return prev;
      const newIdx = direction === 'up' ? idx - 1 : idx + 1;
      if (newIdx < 0 || newIdx >= prev.length) return prev;
      const next = [...prev];
      [next[idx], next[newIdx]] = [next[newIdx], next[idx]];
      return next;
    });
  };

  function AxisConfigEditor({ label, value, onChange }: { label: string; value: AxisConfig; onChange: (v: AxisConfig) => void }) {
    return (
      <div className="grid grid-cols-4 gap-3">
        <div>
          <label className="block text-xs text-gray-500 mb-1">Default</label>
          <Input type="number" value={value.default} onChange={(e) => onChange({ ...value, default: Number(e.target.value) })} />
        </div>
        <div>
          <label className="block text-xs text-gray-500 mb-1">Floor</label>
          <Input type="number" value={value.floor} onChange={(e) => onChange({ ...value, floor: Number(e.target.value) })} />
        </div>
        <div>
          <label className="block text-xs text-gray-500 mb-1">Cap</label>
          <Input type="number" value={value.cap} onChange={(e) => onChange({ ...value, cap: Number(e.target.value) })} />
        </div>
        <div>
          <label className="block text-xs text-gray-500 mb-1">Step</label>
          <Input type="number" step="0.5" value={value.step} onChange={(e) => onChange({ ...value, step: Number(e.target.value) })} />
        </div>
      </div>
    );
  }

  if (loading) {
    return <div className="p-8 text-center text-gray-500">Loading...</div>;
  }

  return (
    <div className="space-y-6 max-w-4xl">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <button onClick={() => router.push('/admin/exercise-progression')} className="text-sm text-blue-600 hover:underline mb-1 block">
            &larr; Back to Exercise Progression
          </button>
          <h1 className="text-2xl font-bold text-gray-900">
            {profile?.exercise?.name?.en || 'Exercise Progression Profile'}
          </h1>
          {profile?.exercise?.slug && (
            <p className="text-sm text-gray-500 mt-0.5">{profile.exercise.slug}</p>
          )}
        </div>
        {profile && (
          <Badge variant={profile.isAutoGenerated ? 'default' : 'primary'}>
            {profile.isAutoGenerated ? 'Auto-Generated' : 'Customized'}
          </Badge>
        )}
      </div>

      {/* No Profile — Generate */}
      {!profile && (
        <Card className="p-6 space-y-4">
          <h2 className="text-lg font-semibold">No progression profile exists yet</h2>
          <p className="text-sm text-gray-600">
            Select an archetype to generate scientific defaults. You can customize them afterward.
          </p>
          <div className="flex gap-3 items-end">
            <div className="flex-1">
              <label className="block text-sm font-medium text-gray-700 mb-1">Archetype</label>
              <Select
                value={selectedArchetype}
                onChange={(e) => setSelectedArchetype(e.target.value)}
                options={[
                  { value: '', label: 'Select Archetype...' },
                  ...Object.entries(ARCHETYPE_LABELS).map(([k, v]) => ({ value: k, label: v })),
                ]}
              />
            </div>
            <Button onClick={handleGenerate} disabled={!selectedArchetype || saving} loading={saving}>
              Generate Defaults
            </Button>
          </div>
        </Card>
      )}

      {/* Profile Editor */}
      {profile && (
        <>
          {/* Validation */}
          {profile.validation && !profile.validation.valid && (
            <div className="bg-orange-50 border border-orange-200 rounded-lg p-4">
              <p className="text-sm font-medium text-orange-800">Validation Issues:</p>
              <ul className="text-sm text-orange-700 mt-1 list-disc list-inside">
                {profile.validation.errors.map((err, i) => <li key={i}>{err}</li>)}
              </ul>
            </div>
          )}

          {/* Archetype & Regenerate */}
          <Card className="p-4 space-y-3">
            <h3 className="text-sm font-semibold text-gray-700">Archetype</h3>
            <div className="flex gap-3 items-end">
              <div className="flex-1">
                <Select
                  value={selectedArchetype}
                  onChange={(e) => setSelectedArchetype(e.target.value)}
                  options={Object.entries(ARCHETYPE_LABELS).map(([k, v]) => ({ value: k, label: v }))}
                />
              </div>
              <Button variant="outline" onClick={handleGenerate} disabled={saving} size="sm">
                Regenerate Defaults
              </Button>
            </div>
          </Card>

          {/* Allowed Axes */}
          <Card className="p-4 space-y-3">
            <h3 className="text-sm font-semibold text-gray-700">Allowed Axes</h3>
            <div className="flex gap-3 flex-wrap">
              {ALL_AXES.map((axis) => (
                <label key={axis} className="flex items-center gap-2 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={allowedAxes.includes(axis)}
                    onChange={() => toggleAxis(axis)}
                    className="h-4 w-4 rounded border-gray-300 text-blue-600"
                  />
                  <span className="text-sm">{AXIS_LABELS[axis]}</span>
                </label>
              ))}
            </div>
          </Card>

          {/* Priority Order */}
          <Card className="p-4 space-y-3">
            <h3 className="text-sm font-semibold text-gray-700">Priority Order (first axis tried on promotion)</h3>
            <div className="space-y-2">
              {priorityOrder.map((axis, idx) => (
                <div key={axis} className="flex items-center gap-3 bg-gray-50 rounded-lg px-3 py-2">
                  <span className="text-sm font-medium text-gray-500 w-6">{idx + 1}.</span>
                  <span className="text-sm flex-1">{AXIS_LABELS[axis] || axis}</span>
                  <button
                    onClick={() => moveAxisPriority(axis, 'up')}
                    disabled={idx === 0}
                    className="text-gray-400 hover:text-gray-600 disabled:opacity-30 text-xs"
                  >
                    ▲
                  </button>
                  <button
                    onClick={() => moveAxisPriority(axis, 'down')}
                    disabled={idx === priorityOrder.length - 1}
                    className="text-gray-400 hover:text-gray-600 disabled:opacity-30 text-xs"
                  >
                    ▼
                  </button>
                </div>
              ))}
            </div>
          </Card>

          {/* Axis Configs */}
          {allowedAxes.includes('reps') && (
            <Card className="p-4 space-y-3">
              <h3 className="text-sm font-semibold text-gray-700">Reps Axis</h3>
              <AxisConfigEditor label="Reps" value={repAxis} onChange={setRepAxis} />
            </Card>
          )}

          {allowedAxes.includes('load') && (
            <Card className="p-4 space-y-3">
              <h3 className="text-sm font-semibold text-gray-700">Load Axis (kg)</h3>
              <AxisConfigEditor label="Load" value={loadAxis} onChange={setLoadAxis} />
            </Card>
          )}

          {allowedAxes.includes('duration') && (
            <Card className="p-4 space-y-3">
              <h3 className="text-sm font-semibold text-gray-700">Duration Axis (seconds)</h3>
              <AxisConfigEditor label="Duration" value={durationAxis} onChange={setDurationAxis} />
            </Card>
          )}

          {allowedAxes.includes('sets') && (
            <Card className="p-4 space-y-3">
              <h3 className="text-sm font-semibold text-gray-700">Sets Axis</h3>
              <AxisConfigEditor label="Sets" value={setAxis} onChange={setSetAxis} />
            </Card>
          )}

          {allowedAxes.includes('difficulty') && (
            <Card className="p-4 space-y-3">
              <h3 className="text-sm font-semibold text-gray-700">Difficulty Ladder</h3>
              <p className="text-xs text-gray-500">Comma-separated list of difficulty codes, ordered easiest to hardest</p>
              <Input
                value={difficultyLadder}
                onChange={(e) => setDifficultyLadder(e.target.value)}
                placeholder="beginner, intermediate, advanced"
              />
            </Card>
          )}

          {/* Quality Gate */}
          <Card className="p-4 space-y-3">
            <h3 className="text-sm font-semibold text-gray-700">Quality Gate (Eligibility Thresholds)</h3>
            <p className="text-xs text-gray-500">Minimum metrics needed to qualify for promotion</p>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-xs text-gray-500 mb-1">Min Form Score</label>
                <Input type="number" value={qualityGate.minFormScore} onChange={(e) => setQualityGate({ ...qualityGate, minFormScore: Number(e.target.value) })} />
              </div>
              <div>
                <label className="block text-xs text-gray-500 mb-1">Min Completion Rate</label>
                <Input type="number" value={qualityGate.minCompletionRate} onChange={(e) => setQualityGate({ ...qualityGate, minCompletionRate: Number(e.target.value) })} />
              </div>
              <div>
                <label className="block text-xs text-gray-500 mb-1">Min ROM (0 = disabled)</label>
                <Input type="number" value={qualityGate.minROM} onChange={(e) => setQualityGate({ ...qualityGate, minROM: Number(e.target.value) })} />
              </div>
              <div>
                <label className="block text-xs text-gray-500 mb-1">Min Stability (0 = disabled)</label>
                <Input type="number" value={qualityGate.minStability} onChange={(e) => setQualityGate({ ...qualityGate, minStability: Number(e.target.value) })} />
              </div>
            </div>
          </Card>

          {/* Promotion Policy */}
          <Card className="p-4 space-y-3">
            <h3 className="text-sm font-semibold text-gray-700">Promotion Policy</h3>
            <div>
              <label className="block text-xs text-gray-500 mb-1">Required consecutive qualifying sessions</label>
              <Input type="number" min={1} max={10} value={promotionStreak} onChange={(e) => setPromotionStreak(Number(e.target.value))} />
            </div>
          </Card>

          {/* Regression Policy */}
          <Card className="p-4 space-y-3">
            <h3 className="text-sm font-semibold text-gray-700">Regression Policy</h3>
            <div>
              <label className="block text-xs text-gray-500 mb-1">Trigger regression when form score falls below</label>
              <Input type="number" value={regressionMaxScore} onChange={(e) => setRegressionMaxScore(Number(e.target.value))} />
            </div>
          </Card>

          {/* Save */}
          <div className="flex justify-end gap-3 pt-2">
            <Button variant="outline" onClick={() => router.push('/admin/exercise-progression')}>
              Cancel
            </Button>
            <Button onClick={handleSave} loading={saving}>
              Save Changes
            </Button>
          </div>
        </>
      )}
    </div>
  );
}
