'use client';

import { useEffect, useState, useCallback } from 'react';
import { useParams, useRouter } from 'next/navigation';
import {
  Input,
  Select,
  Label,
  Button,
  Card,
  Badge,
} from '@/components/ui';

const ARCHETYPE_OPTIONS = [
  { value: 'weighted_strength', label: 'Weighted Strength' },
  { value: 'bodyweight_dynamic', label: 'Bodyweight Dynamic' },
  { value: 'isometric_hold', label: 'Isometric Hold' },
  { value: 'mobility_rom', label: 'Mobility ROM' },
  { value: 'motor_control', label: 'Motor Control' },
];

const ARCHETYPE_DESCRIPTIONS: Record<string, string> = {
  weighted_strength: 'Exercises using external load (barbell, dumbbell). Primary progression: weight increase. Quality gate: Form Score >= 75%.',
  bodyweight_dynamic: 'Dynamic exercises using body weight only. Primary progression: reps. Quality gate: Form Score >= 80%.',
  isometric_hold: 'Static hold exercises. Primary progression: duration. Quality gate: Form Score >= 85%.',
  mobility_rom: 'Flexibility and range of motion work. Primary progression: ROM improvement. Quality gate: Symmetry >= 80%.',
  motor_control: 'Balance, coordination, and stability drills. Primary progression: form quality. Quality gate: Stability >= 80%.',
};

const METRIC_OPTIONS = [
  { value: 'avgFormScore', label: 'Avg Form Score' },
  { value: 'avgROM', label: 'Avg ROM' },
  { value: 'avgSymmetry', label: 'Avg Symmetry' },
  { value: 'avgStability', label: 'Avg Stability' },
  { value: 'completionRate', label: 'Completion Rate' },
];

const OPERATOR_OPTIONS = [
  { value: '>=', label: '>=' },
  { value: '<=', label: '<=' },
  { value: '>', label: '>' },
  { value: '<', label: '<' },
];

const WINDOW_OPTIONS = [
  { value: 'last_session', label: 'Last Session' },
  { value: 'last_2_sessions', label: 'Last 2 Sessions' },
  { value: 'last_week', label: 'Last Week' },
];

const ACTION_TYPE_OPTIONS = [
  { value: 'increase_weight', label: 'Increase Weight' },
  { value: 'decrease_weight', label: 'Decrease Weight' },
  { value: 'increase_reps', label: 'Increase Reps' },
  { value: 'decrease_reps', label: 'Decrease Reps' },
  { value: 'increase_duration', label: 'Increase Duration' },
  { value: 'decrease_duration', label: 'Decrease Duration' },
  { value: 'increase_sets', label: 'Increase Sets' },
];

interface Condition {
  metric: string;
  operator: string;
  value: number;
  window: string;
}

interface ActionConfig {
  type: string;
  amount: number;
}

interface RuleConfig {
  conditions: Condition[];
  action: ActionConfig;
}

interface Profile {
  id: string;
  exerciseId: string;
  archetype: string;
  repRange: { min: number; max: number } | null;
  weightBounds: { min: number; max: number; step: number } | null;
  durationBounds: { min: number; max: number; step: number } | null;
  qualityGate: { metric: string; threshold: number };
  promotionRule: RuleConfig;
  regressionRule: RuleConfig;
  difficultyLadder: string[] | null;
  isAutoGenerated: boolean;
  exercise: { id: string; name: { en: string; ar: string }; slug: string };
}

export default function ExerciseProgressionDetailPage() {
  const params = useParams();
  const router = useRouter();
  const exerciseId = params.exerciseId as string;

  const [profile, setProfile] = useState<Profile | null>(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [archetype, setArchetype] = useState('');

  // Form state
  const [repRange, setRepRange] = useState({ min: 0, max: 0 });
  const [weightBounds, setWeightBounds] = useState({ min: 0, max: 0, step: 0 });
  const [durationBounds, setDurationBounds] = useState({ min: 0, max: 0, step: 0 });
  const [qualityGate, setQualityGate] = useState({ metric: 'avgFormScore', threshold: 75 });
  const [promotionRule, setPromotionRule] = useState<RuleConfig>({
    conditions: [{ metric: 'avgFormScore', operator: '>=', value: 75, window: 'last_2_sessions' }],
    action: { type: 'increase_weight', amount: 2.5 },
  });
  const [regressionRule, setRegressionRule] = useState<RuleConfig>({
    conditions: [{ metric: 'avgFormScore', operator: '<', value: 60, window: 'last_2_sessions' }],
    action: { type: 'decrease_weight', amount: 2.5 },
  });
  const [difficultyLadder, setDifficultyLadder] = useState<string[]>([]);
  const [showRepRange, setShowRepRange] = useState(false);
  const [showWeightBounds, setShowWeightBounds] = useState(false);
  const [showDurationBounds, setShowDurationBounds] = useState(false);
  const [showDifficultyLadder, setShowDifficultyLadder] = useState(false);

  const fetchProfile = useCallback(async () => {
    setLoading(true);
    try {
      const res = await fetch(`/api/admin/exercise-progression/${exerciseId}`);
      const data = await res.json();
      if (data.success && data.data) {
        const p = data.data as Profile;
        setProfile(p);
        setArchetype(p.archetype);
        loadFormFromProfile(p);
      }
    } catch (error) {
      console.error('Error fetching profile:', error);
    } finally {
      setLoading(false);
    }
  }, [exerciseId]);

  const loadFormFromProfile = (p: Profile) => {
    if (p.repRange) {
      setRepRange(p.repRange);
      setShowRepRange(true);
    }
    if (p.weightBounds) {
      setWeightBounds(p.weightBounds);
      setShowWeightBounds(true);
    }
    if (p.durationBounds) {
      setDurationBounds(p.durationBounds);
      setShowDurationBounds(true);
    }
    setQualityGate(p.qualityGate);
    setPromotionRule(p.promotionRule);
    setRegressionRule(p.regressionRule);
    if (p.difficultyLadder && p.difficultyLadder.length > 0) {
      setDifficultyLadder(p.difficultyLadder);
      setShowDifficultyLadder(true);
    }
  };

  useEffect(() => {
    fetchProfile();
  }, [fetchProfile]);

  const handleSetArchetype = async (newArchetype: string) => {
    if (!newArchetype) return;
    setSaving(true);
    try {
      const res = await fetch(`/api/admin/exercise-progression/${exerciseId}/archetype`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ archetype: newArchetype }),
      });
      const data = await res.json();
      if (data.success) {
        setArchetype(newArchetype);
        fetchProfile();
      }
    } catch (error) {
      console.error('Error setting archetype:', error);
    } finally {
      setSaving(false);
    }
  };

  const handleRegenerate = async () => {
    if (!archetype) return;
    if (!confirm('This will reset the profile to default values for this archetype. Continue?')) return;
    setSaving(true);
    try {
      const res = await fetch(`/api/admin/exercise-progression/${exerciseId}/generate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ archetype }),
      });
      const data = await res.json();
      if (data.success) {
        fetchProfile();
      }
    } catch (error) {
      console.error('Error regenerating profile:', error);
    } finally {
      setSaving(false);
    }
  };

  const handleSave = async () => {
    setSaving(true);
    try {
      const payload: Record<string, unknown> = {
        qualityGate,
        promotionRule,
        regressionRule,
      };
      if (showRepRange) payload.repRange = repRange;
      if (showWeightBounds) payload.weightBounds = weightBounds;
      if (showDurationBounds) payload.durationBounds = durationBounds;
      if (showDifficultyLadder && difficultyLadder.length > 0) payload.difficultyLadder = difficultyLadder;

      const res = await fetch(`/api/admin/exercise-progression/${exerciseId}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      });
      const data = await res.json();
      if (data.success) {
        fetchProfile();
      } else {
        alert(data.error || 'Failed to save profile');
      }
    } catch (error) {
      console.error('Error saving profile:', error);
      alert('Failed to save profile');
    } finally {
      setSaving(false);
    }
  };

  const updatePromotionCondition = (index: number, updates: Partial<Condition>) => {
    setPromotionRule((prev) => ({
      ...prev,
      conditions: prev.conditions.map((c, i) => (i === index ? { ...c, ...updates } : c)),
    }));
  };

  const updateRegressionCondition = (index: number, updates: Partial<Condition>) => {
    setRegressionRule((prev) => ({
      ...prev,
      conditions: prev.conditions.map((c, i) => (i === index ? { ...c, ...updates } : c)),
    }));
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="animate-spin h-8 w-8 border-4 border-blue-600 border-t-transparent rounded-full" />
      </div>
    );
  }

  return (
    <div className="space-y-6 max-w-4xl">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <button onClick={() => router.back()} className="text-sm text-gray-500 hover:text-gray-700 mb-2 inline-block">
            &larr; Back to list
          </button>
          <h1 className="text-2xl font-bold text-gray-900">
            {profile?.exercise?.name?.en || 'Exercise Progression Profile'}
          </h1>
          <p className="text-gray-500 text-sm" dir="rtl">{profile?.exercise?.name?.ar || ''}</p>
        </div>
        <div className="flex gap-2">
          {profile && (
            <Badge variant={profile.isAutoGenerated ? 'primary' : 'default'}>
              {profile.isAutoGenerated ? 'Auto Generated' : 'Custom'}
            </Badge>
          )}
        </div>
      </div>

      {/* Archetype Section */}
      <Card className="p-5 space-y-4">
        <h2 className="text-lg font-semibold text-gray-900">Archetype</h2>
        <div className="grid grid-cols-2 gap-4">
          <div>
            <Label>Exercise Archetype</Label>
            <Select
              value={archetype}
              onChange={(e) => handleSetArchetype(e.target.value)}
              options={ARCHETYPE_OPTIONS}
            />
          </div>
          <div className="flex items-end">
            <Button variant="outline" onClick={handleRegenerate} disabled={saving || !archetype}>
              Regenerate Defaults
            </Button>
          </div>
        </div>
        {archetype && (
          <p className="text-sm text-gray-600 bg-gray-50 p-3 rounded-lg">
            {ARCHETYPE_DESCRIPTIONS[archetype]}
          </p>
        )}
      </Card>

      {!profile ? (
        <Card className="p-8 text-center text-gray-500">
          <p>No profile found. Select an archetype above to generate a default profile.</p>
        </Card>
      ) : (
        <>
          {/* Bounds Section */}
          <Card className="p-5 space-y-4">
            <h2 className="text-lg font-semibold text-gray-900">Bounds & Limits</h2>

            {/* Rep Range */}
            <div>
              <label className="flex items-center gap-2 mb-2">
                <input
                  type="checkbox"
                  checked={showRepRange}
                  onChange={(e) => setShowRepRange(e.target.checked)}
                  className="h-4 w-4 rounded border-gray-300 text-blue-600"
                />
                <span className="text-sm font-medium text-gray-700">Rep Range</span>
              </label>
              {showRepRange && (
                <div className="grid grid-cols-2 gap-4 ml-6">
                  <div>
                    <Label>Min Reps</Label>
                    <Input type="number" value={repRange.min} onChange={(e) => setRepRange((p) => ({ ...p, min: Number(e.target.value) }))} />
                  </div>
                  <div>
                    <Label>Max Reps</Label>
                    <Input type="number" value={repRange.max} onChange={(e) => setRepRange((p) => ({ ...p, max: Number(e.target.value) }))} />
                  </div>
                </div>
              )}
            </div>

            {/* Weight Bounds */}
            <div>
              <label className="flex items-center gap-2 mb-2">
                <input
                  type="checkbox"
                  checked={showWeightBounds}
                  onChange={(e) => setShowWeightBounds(e.target.checked)}
                  className="h-4 w-4 rounded border-gray-300 text-blue-600"
                />
                <span className="text-sm font-medium text-gray-700">Weight Bounds (kg)</span>
              </label>
              {showWeightBounds && (
                <div className="grid grid-cols-3 gap-4 ml-6">
                  <div>
                    <Label>Min</Label>
                    <Input type="number" value={weightBounds.min} onChange={(e) => setWeightBounds((p) => ({ ...p, min: Number(e.target.value) }))} />
                  </div>
                  <div>
                    <Label>Max</Label>
                    <Input type="number" value={weightBounds.max} onChange={(e) => setWeightBounds((p) => ({ ...p, max: Number(e.target.value) }))} />
                  </div>
                  <div>
                    <Label>Step</Label>
                    <Input type="number" step="0.5" value={weightBounds.step} onChange={(e) => setWeightBounds((p) => ({ ...p, step: Number(e.target.value) }))} />
                  </div>
                </div>
              )}
            </div>

            {/* Duration Bounds */}
            <div>
              <label className="flex items-center gap-2 mb-2">
                <input
                  type="checkbox"
                  checked={showDurationBounds}
                  onChange={(e) => setShowDurationBounds(e.target.checked)}
                  className="h-4 w-4 rounded border-gray-300 text-blue-600"
                />
                <span className="text-sm font-medium text-gray-700">Duration Bounds (seconds)</span>
              </label>
              {showDurationBounds && (
                <div className="grid grid-cols-3 gap-4 ml-6">
                  <div>
                    <Label>Min</Label>
                    <Input type="number" value={durationBounds.min} onChange={(e) => setDurationBounds((p) => ({ ...p, min: Number(e.target.value) }))} />
                  </div>
                  <div>
                    <Label>Max</Label>
                    <Input type="number" value={durationBounds.max} onChange={(e) => setDurationBounds((p) => ({ ...p, max: Number(e.target.value) }))} />
                  </div>
                  <div>
                    <Label>Step</Label>
                    <Input type="number" value={durationBounds.step} onChange={(e) => setDurationBounds((p) => ({ ...p, step: Number(e.target.value) }))} />
                  </div>
                </div>
              )}
            </div>
          </Card>

          {/* Quality Gate */}
          <Card className="p-5 space-y-4">
            <h2 className="text-lg font-semibold text-gray-900">Quality Gate</h2>
            <p className="text-sm text-gray-500">Minimum quality threshold that must be met before any quantity progression is allowed.</p>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <Label>Metric</Label>
                <Select value={qualityGate.metric} onChange={(e) => setQualityGate((p) => ({ ...p, metric: e.target.value }))} options={METRIC_OPTIONS} />
              </div>
              <div>
                <Label>Threshold (%)</Label>
                <Input type="number" min={0} max={100} value={qualityGate.threshold} onChange={(e) => setQualityGate((p) => ({ ...p, threshold: Number(e.target.value) }))} />
              </div>
            </div>
          </Card>

          {/* Promotion Rule */}
          <Card className="p-5 space-y-4">
            <div className="flex items-center justify-between">
              <div>
                <h2 className="text-lg font-semibold text-green-700">Promotion Rule</h2>
                <p className="text-sm text-gray-500">When to increase difficulty (all conditions must be met)</p>
              </div>
              <Button
                variant="outline"
                size="sm"
                onClick={() => setPromotionRule((prev) => ({
                  ...prev,
                  conditions: [...prev.conditions, { metric: 'avgFormScore', operator: '>=', value: 75, window: 'last_2_sessions' }],
                }))}
              >
                Add Condition
              </Button>
            </div>

            {promotionRule.conditions.map((cond, idx) => (
              <div key={idx} className="flex items-end gap-3 p-3 bg-green-50 rounded-lg">
                <div className="flex-1">
                  <Label>Metric</Label>
                  <Select value={cond.metric} onChange={(e) => updatePromotionCondition(idx, { metric: e.target.value })} options={METRIC_OPTIONS} />
                </div>
                <div className="w-24">
                  <Label>Op</Label>
                  <Select value={cond.operator} onChange={(e) => updatePromotionCondition(idx, { operator: e.target.value })} options={OPERATOR_OPTIONS} />
                </div>
                <div className="w-28">
                  <Label>Value</Label>
                  <Input type="number" value={cond.value} onChange={(e) => updatePromotionCondition(idx, { value: Number(e.target.value) })} />
                </div>
                <div className="flex-1">
                  <Label>Window</Label>
                  <Select value={cond.window} onChange={(e) => updatePromotionCondition(idx, { window: e.target.value })} options={WINDOW_OPTIONS} />
                </div>
                {promotionRule.conditions.length > 1 && (
                  <Button
                    variant="ghost"
                    size="sm"
                    className="text-red-500 shrink-0"
                    onClick={() => setPromotionRule((prev) => ({
                      ...prev,
                      conditions: prev.conditions.filter((_, i) => i !== idx),
                    }))}
                  >
                    Remove
                  </Button>
                )}
              </div>
            ))}

            <div className="grid grid-cols-2 gap-4">
              <div>
                <Label>Action Type</Label>
                <Select
                  value={promotionRule.action.type}
                  onChange={(e) => setPromotionRule((prev) => ({ ...prev, action: { ...prev.action, type: e.target.value } }))}
                  options={ACTION_TYPE_OPTIONS}
                />
              </div>
              <div>
                <Label>Amount</Label>
                <Input
                  type="number"
                  step="0.5"
                  value={promotionRule.action.amount}
                  onChange={(e) => setPromotionRule((prev) => ({ ...prev, action: { ...prev.action, amount: Number(e.target.value) } }))}
                />
              </div>
            </div>
          </Card>

          {/* Regression Rule */}
          <Card className="p-5 space-y-4">
            <div className="flex items-center justify-between">
              <div>
                <h2 className="text-lg font-semibold text-red-700">Regression Rule</h2>
                <p className="text-sm text-gray-500">When to decrease difficulty (safety deload)</p>
              </div>
              <Button
                variant="outline"
                size="sm"
                onClick={() => setRegressionRule((prev) => ({
                  ...prev,
                  conditions: [...prev.conditions, { metric: 'avgFormScore', operator: '<', value: 60, window: 'last_2_sessions' }],
                }))}
              >
                Add Condition
              </Button>
            </div>

            {regressionRule.conditions.map((cond, idx) => (
              <div key={idx} className="flex items-end gap-3 p-3 bg-red-50 rounded-lg">
                <div className="flex-1">
                  <Label>Metric</Label>
                  <Select value={cond.metric} onChange={(e) => updateRegressionCondition(idx, { metric: e.target.value })} options={METRIC_OPTIONS} />
                </div>
                <div className="w-24">
                  <Label>Op</Label>
                  <Select value={cond.operator} onChange={(e) => updateRegressionCondition(idx, { operator: e.target.value })} options={OPERATOR_OPTIONS} />
                </div>
                <div className="w-28">
                  <Label>Value</Label>
                  <Input type="number" value={cond.value} onChange={(e) => updateRegressionCondition(idx, { value: Number(e.target.value) })} />
                </div>
                <div className="flex-1">
                  <Label>Window</Label>
                  <Select value={cond.window} onChange={(e) => updateRegressionCondition(idx, { window: e.target.value })} options={WINDOW_OPTIONS} />
                </div>
                {regressionRule.conditions.length > 1 && (
                  <Button
                    variant="ghost"
                    size="sm"
                    className="text-red-500 shrink-0"
                    onClick={() => setRegressionRule((prev) => ({
                      ...prev,
                      conditions: prev.conditions.filter((_, i) => i !== idx),
                    }))}
                  >
                    Remove
                  </Button>
                )}
              </div>
            ))}

            <div className="grid grid-cols-2 gap-4">
              <div>
                <Label>Action Type</Label>
                <Select
                  value={regressionRule.action.type}
                  onChange={(e) => setRegressionRule((prev) => ({ ...prev, action: { ...prev.action, type: e.target.value } }))}
                  options={ACTION_TYPE_OPTIONS}
                />
              </div>
              <div>
                <Label>Amount</Label>
                <Input
                  type="number"
                  step="0.5"
                  value={regressionRule.action.amount}
                  onChange={(e) => setRegressionRule((prev) => ({ ...prev, action: { ...prev.action, amount: Number(e.target.value) } }))}
                />
              </div>
            </div>
          </Card>

          {/* Difficulty Ladder */}
          <Card className="p-5 space-y-4">
            <label className="flex items-center gap-2">
              <input
                type="checkbox"
                checked={showDifficultyLadder}
                onChange={(e) => setShowDifficultyLadder(e.target.checked)}
                className="h-4 w-4 rounded border-gray-300 text-blue-600"
              />
              <h2 className="text-lg font-semibold text-gray-900">Difficulty Ladder</h2>
            </label>
            <p className="text-sm text-gray-500">Ordered list of difficulty variations (for bodyweight/motor control)</p>

            {showDifficultyLadder && (
              <div className="space-y-2">
                {difficultyLadder.map((step, idx) => (
                  <div key={idx} className="flex items-center gap-2">
                    <span className="text-sm text-gray-400 w-6">{idx + 1}.</span>
                    <Input
                      value={step}
                      onChange={(e) => setDifficultyLadder((prev) => prev.map((s, i) => (i === idx ? e.target.value : s)))}
                      placeholder="e.g. assisted, standard, elevated"
                    />
                    <Button
                      variant="ghost"
                      size="sm"
                      className="text-red-500 shrink-0"
                      onClick={() => setDifficultyLadder((prev) => prev.filter((_, i) => i !== idx))}
                    >
                      &times;
                    </Button>
                  </div>
                ))}
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => setDifficultyLadder((prev) => [...prev, ''])}
                >
                  Add Step
                </Button>
              </div>
            )}
          </Card>

          {/* Save */}
          <div className="flex justify-end gap-3 pb-8">
            <Button variant="outline" onClick={() => router.back()}>Cancel</Button>
            <Button onClick={handleSave} loading={saving}>Save Profile</Button>
          </div>
        </>
      )}
    </div>
  );
}
