export const analyticsTerms = {
  totalUsers: 'All non-deleted mobile users in the platform.',
  newUsers: 'Users created during the selected period.',
  activeUsers: 'Users who recorded at least one workout execution in the selected period.',
  proUsers: 'Users currently marked as Pro.',
  revenue: 'Subscription revenue plus paid booking revenue in the selected period.',
  arpu: 'Average Revenue Per User. Subscription revenue divided by active subscriptions.',
  workoutExecutions: 'Completed workout executions uploaded by users in the selected period.',
  totalReps: 'All repetitions detected during workout executions.',
  invalidReps: 'Repetitions marked unsafe or invalid by the movement engine.',
  avgFormScore: 'Average movement quality score from execution metrics. Higher means cleaner technique.',
  formScore: 'Movement quality score calculated from pose, alignment, stability, and exercise rules.',
  rom: 'Range of Motion. Measures how much of the expected movement range was achieved.',
  symmetry: 'Left/right balance and consistency for bilateral movements.',
  stability: 'How controlled and steady the movement was during the exercise.',
  fatigueIndex: 'Estimated decline in movement quality or speed during the workout execution.',
  assessment: 'Body scan or movement assessment used to classify level and readiness.',
  northStar: 'Primary product-success metric: users who complete 3 correct workout executions in their first 7 days.',
  activation: 'The path from signup to first meaningful value: profile, safety, assessment, plan, and first workout.',
  retention: 'How many users return and keep training after signup.',
  dau: 'Daily Active Users. Users active in the last 1 day.',
  wau: 'Weekly Active Users. Users active in the last 7 days.',
  mau: 'Monthly Active Users. Users active in the last 30 days.',
  stickiness: 'Relationship between DAU, WAU, and MAU. Higher means users return more often.',
  cohort: 'A group of users who signed up during the same week, tracked over time.',
  churnSignals: 'Users who have not trained for a defined number of days.',
  dangerRepRate: 'Percentage of reps flagged as dangerous or invalid.',
  highRiskExecutions: 'Workout executions where danger reps exceed a safety threshold.',
  safetyScore: 'Assessment-domain score that reflects movement safety.',
  executionContexts: 'Where workout executions came from: free, program, assessment, explore, or quick start.',
  averageMetrics: 'Averages for core training quality signals: form score, ROM, symmetry, stability, and fatigue.',
  mrr: 'Monthly Recurring Revenue estimated from active monthly subscriptions.',
  checkoutFunnel: 'How users move through payment: started, paid, failed, or cancelled.',
  conversionRate: 'Percentage of users who move from one funnel step to the next.',
  completionRate: 'Percentage of enrolled users or planned workouts that reached the defined completion condition.',
  progression: 'Training parameter changes applied by the progression engine.',
  qualityGate: 'Minimum movement-quality conditions required before increasing difficulty.',
  activeRules: 'Progression rules currently enabled in the system.',
  knownInjuries: 'Injury notes collected from training profiles. Used as a risk signal, not a diagnosis.',
  contentCoverage: 'How complete and useful the exercise, workout template, program, message, and camera-position catalog is.',
};

export type AnalyticsTermKey = keyof typeof analyticsTerms;
