// casl.types.ts

// These should match the string values in the database permissions
export type Action = 'manage' | 'read' | 'create' | 'update' | 'delete';

export type Subject =
    | 'Admin'
    | 'Role'
    | 'User'
    | 'Exercise'
    | 'Workout'
    | 'Program'
    | 'ProgramMap'
    | 'Recipe'
    | 'MealPlan'
    | 'TrainingProvider'
    | 'Muscle'
    | 'Equipment'
    | 'Level'
    | 'AssessmentTemplate'
    | 'Reassessment'
    | 'ProgressionRule'
    | 'ExerciseProgressionProfile'
    | 'Config'
    | 'System'
    | 'ReportOverview'
    | 'ReportUsers'
    | 'ReportActivation'
    | 'ReportRetention'
    | 'ReportTraining'
    | 'ReportProgram'
    | 'ReportLevel'
    | 'ReportAssessment'
    | 'ReportProgression'
    | 'ReportRevenue'
    | 'ReportBooking'
    | 'ReportSafety'
    | 'ReportContent'
    | 'Attribute'
    | 'PosePosition'
    | 'FeedbackMessage'
    | 'Upload'
    | 'DoctorWorkTime'
    | 'CloseTime'
    | 'Booking'
    | 'BookingReport'
    | 'Plan'
    | 'Subscription'
    | 'all'; // 'all' is a special subject for wildcards
