package com.movit.resources

// JVM/unit-test fallback for Arabic when compose resources are unavailable.
internal val movitArabicStrings: Map<String, String> = mapOf(
    "program_flow_list_title" to "البرامج",
    "program_flow_loading" to "جاري تحميل البرامج…",
    "program_flow_empty_title" to "لا توجد برامج بعد",
    "program_flow_empty_message" to "تحقق من الاتصال وحاول مرة أخرى.",
    "program_flow_weeks_days" to "%1\$d أسابيع · %2\$d أيام/أسبوع",
    "program_flow_week_title" to "الأسبوع %1\$d",
    "program_flow_open_today" to "فتح جلسة اليوم",
    "program_flow_view_week_report" to "عرض تقرير الأسبوع",
    "program_flow_week_report_title" to "تقرير الأسبوع %1\$d",
    "program_flow_week_report_fallback" to "التقرير الأسبوعي",
    "program_flow_metric_sessions" to "الجلسات",
    "program_flow_metric_form" to "متوسط الأداء",
    "program_flow_metric_reps" to "التكرارات",
    "program_flow_daily_form" to "درجات الأداء اليومية",
    "program_flow_share_report" to "مشاركة التقرير",
    "program_flow_share_coming_soon" to "مشاركة التقرير قريباً.",
    "program_flow_status_done" to "مكتمل",
    "program_flow_status_today" to "اليوم",
    "program_flow_status_planned" to "مجدول",
    "program_flow_status_rest" to "يوم راحة",
    "program_flow_a11y_day" to "اليوم %1\$d، %2\$s. %3\$s. %4\$s",
    "program_flow_a11y_chart" to "مخطط درجات الأداء اليومية",
    "program_flow_load_failed" to "تعذّر تحميل البرامج.",
    "program_flow_program_not_found" to "البرنامج غير موجود.",
    "program_flow_active_badge" to "نشط",
    "program_flow_chip_all" to "الكل",
    "program_flow_day_short" to "اليوم %1\$d",
    "program_flow_week_subtitle" to "%1\$d تمارين · %2\$d راحة",
    "program_flow_day_today_detail" to "اليوم · %1\$d تمارين · %2\$d د",
    "program_flow_day_completed" to "مكتمل",
    "program_flow_report_hero_eyebrow" to "ملخص الأسبوع %1\$d",
    "program_flow_report_hero_title" to "أسبوع رائع!",
    "program_flow_report_hero_subtitle" to "أكملت %1\$d من %2\$d جلسات مخططة.",
    "report_detail_preview_personal_best" to "أفضل إنجاز شخصي",
    "report_detail_preview_insight_title" to "ثبات ممتاز في العمق",
    "report_detail_preview_insight_message" to "خط الورك بقي تحت مستوى الركبة في 95% من التكرارات.",
    "report_detail_preview_joint_knees" to "الركبتان",
    "report_detail_preview_joint_hips" to "الوركان",
    "report_detail_preview_joint_spine" to "العمود الفقري",
    "report_detail_preview_tip1_title" to "شدّ العضلات الأساسية مبكراً",
    "report_detail_preview_tip1_message" to "أثناء النزول، فعّل العضلات الأساسية قبل ميل الورك بـ 0.5 ثانية لحماية أسفل الظهر.",
    "report_detail_preview_tip2_title" to "حافظ على محاذاة الركبتين مع أصابع القدم",
    "report_detail_preview_tip2_message" to "انحراف طفيف للداخل في المجموعة 4 — ركّز على دفع الركبتين للخارج.",
    "report_detail_preview_fatigue_message" to "انخفض الأداء 6% من المجموعة 1 إلى 4 — ضمن المعدل الطبيعي.",
)
