package com.movit.resources

// Generated from composeResources/values/strings.xml — do not edit manually.
internal val movitEnglishStrings: Map<String, String> = mapOf(
    "nav_home" to "Home",
    "nav_train" to "Train",
    "nav_explore" to "Explore",
    "nav_reports" to "Reports",
    "nav_account" to "Account",
    "profile_title" to "Account",
    "profile_subtitle" to "Account settings and subscription.",
    "profile_signed_in" to "Signed in",
    "profile_sign_in_prompt" to "Sign in to sync your data",
    "profile_language" to "Language",
    "profile_language_en" to "English",
    "profile_language_ar" to "Arabic",
    "profile_subscription" to "Subscription",
    "profile_pro_active" to "Pro — reports unlocked",
    "profile_free_plan" to "Free — upgrade for coach reports",
    "dest_home_subtitle" to "Your daily training dashboard.",
    "dest_train_subtitle" to "Your program and today\\'s plan.",
    "dest_explore_subtitle" to "Browse workouts, exercises and programs.",
    "dest_reports_subtitle" to "Session history and performance insights.",
    "home_loading" to "Loading your dashboard…",
    "home_view_level" to "View level",
    "home_plan_adjusted" to "Training plan adjusted",
    "home_active_program" to "Active program",
    "home_program" to "Program",
    "home_todays_plan" to "Today\\'s plan",
    "home_today" to "Today",
    "home_body_scan" to "Body scan",
    "home_body_scan_subtitle" to "Measure mobility &amp; posture to unlock your personalized level.",
    "home_start_scan" to "Start scan",
    "home_no_program" to "No active program",
    "home_no_program_message" to "Browse guided plans on Train or explore free workouts.",
    "home_browse_programs" to "Browse programs",
    "home_your_journey" to "Your journey",
    "home_progress" to "Progress",
    "home_view_plan" to "View plan",
    "home_recent_activity" to "Recent activity",
    "home_insights" to "Insights",
    "home_all_reports" to "All reports",
    "home_quick_actions" to "Quick actions",
    "home_metric_this_week" to "This week",
    "home_metric_form_avg" to "Form avg",
    "home_metric_streak" to "Day streak",
    "home_your_level" to "Your level",
    "home_level_title" to "Level %1\$d%2\$s",
    "home_level_code_suffix" to " · %1\$s",
    "home_body_score_pts" to "Body score %1\$d · %2\$d pts to next level",
    "home_body_score_only" to "Body score %1\$d",
    "home_current_plan" to "CURRENT PLAN",
    "home_active_program_fallback" to "Active program",
    "home_week_progress" to "Week %1\$d of %2\$d · %3\$d/%4\$d workouts this week",
    "home_view_program" to "View program",
    "home_todays_workout" to "Today\\'s workout",
    "home_exercises_count" to "%1\$d exercises",
    "home_min_est" to "~%1\$d min",
    "home_dash" to "—",
    "home_completed_today" to "Completed today",
    "home_workout_progress" to "Workout %1\$d of %2\$d today",
    "home_ready_to_start" to "Ready to start",
    "home_start_workout" to "Start workout",
    "home_week_day_label" to "WEEK %1\$d · DAY %2\$d",
    "home_active_recovery" to "Active recovery",
    "home_rest_day" to "Rest day",
    "home_recovery_subtitle" to "Recovery keeps your plan on track.",
    "home_rest" to "Rest",
    "home_no_workout" to "No workout",
    "home_take_it_easy" to "Take it easy today",
    "home_view_train" to "View Train",
    "home_your_plan_label" to "YOUR PLAN",
    "home_program_complete" to "Program complete",
    "home_program_complete_subtitle" to "Time to reassess and unlock your next level.",
    "home_complete" to "Complete",
    "home_great_work" to "Great work finishing the program",
    "home_start_reassessment" to "Start reassessment",
    "home_start_body_scan" to "Start with a body scan",
    "home_unlock_level" to "Unlock a personalized training level.",
    "home_assessment" to "Assessment",
    "home_required_before_plan" to "Required before your first plan",
    "home_plan_timeline" to "Plan timeline",
    "home_week_in_progress" to "Week %1\$d of %2\$d in progress",
    "home_reassessment_due" to "Reassessment due",
    "home_soon" to "Soon",
    "home_last_session" to "Last session",
    "home_greeting_morning" to "Good morning",
    "home_greeting_afternoon" to "Good afternoon",
    "home_greeting_evening" to "Good evening",
    "home_greeting_active" to "Ready for today\\'s session?",
    "home_greeting_rest" to "Rest day — recover and come back stronger.",
    "home_greeting_no_plan" to "Let\\'s find your next workout.",
    "home_greeting_no_assessment" to "Start with a body scan to get your plan.",
    "home_greeting_program_complete" to "Program complete — time to reassess.",
    "home_greeting_reassessment" to "Reassessment due — let\\'s recalibrate.",
    "home_greeting_default" to "Let\\'s get moving.",
    "home_quick_explore" to "Explore",
    "home_quick_explore_sub" to "Browse workouts and exercises",
    "home_quick_reports" to "Reports",
    "home_quick_reports_sub" to "Review your progress",
    "home_activity_form" to "%1\$s · %2\$d%% form",
    "home_activity_reps" to "%1\$d reps · %2\$s",
    "home_action_unavailable" to "Action not available yet.",
    "home_program_week_subtitle" to "Week %1\$d of %2\$d · %3\$d/%4\$d workouts this week",
    "home_level_named" to "Level %1\$d · %2\$s",
    "home_body_score_pts_next" to "Body score %1\$d · %2\$d pts to next level",
    "home_min_total" to "%1\$d min",
    "home_report_reps" to "%1\$d reps",
    "home_today_caps" to "TODAY",
    "home_weekly_overview" to "Weekly overview",
    "home_weekly_completion" to "Week progress",
    "home_active_minutes" to "Active minutes",
    "home_timeline_summary" to "%1\$d completed · %2\$d active · %3\$d upcoming",
    "home_a11y_level_card" to "Open level profile",
    "home_a11y_explore_action" to "Explore workouts and exercises",
    "home_a11y_reports_action" to "Open training reports",
    "home_a11y_start_workout" to "Start today\\'s workout",
    "home_a11y_view_program" to "View active program",
    "home_a11y_body_scan" to "Start body scan assessment",
    "train_title" to "Train",
    "train_loading" to "Loading your training plan…",
    "train_browse_programs" to "Browse all programs",
    "train_active_program" to "Active program",
    "train_week_day_position" to "Week %1\$d of %2\$d · Day %3\$d",
    "train_active_plan" to "Active plan",
    "train_workouts_this_week" to "%1\$d workouts this week",
    "train_day_streak" to "%1\$d day streak",
    "train_no_active_program" to "No active program",
    "train_zero_exercises" to "0 exercises",
    "train_explore_programs" to "Explore programs",
    "train_program_complete" to "Program complete",
    "train_program_complete_sub" to "Review your journey and choose the next step.",
    "train_view_report" to "View report",
    "train_active_recovery" to "Active recovery",
    "train_recovery_day" to "Recovery day",
    "train_rest_in_program" to "Rest day in %1\$s.",
    "train_recover_today" to "Recover today and come back stronger.",
    "train_no_workout" to "No workout",
    "train_recovery" to "Recovery",
    "train_explore_recovery" to "Explore recovery",
    "train_training" to "Training",
    "train_start_session" to "Start session",
    "train_completed" to "Completed",
    "train_workout_n_of_m" to "Workout %1\$d of %2\$d today",
    "train_ready" to "Ready",
    "train_todays_workout" to "Today\\'s workout",
    "train_view_summary" to "View summary",
    "train_this_week" to "This week",
    "train_week_title" to "Week %1\$d",
    "train_day_short" to "D%1\$d",
    "train_readiness" to "Readiness",
    "train_latest_report" to "Latest report",
    "train_last_workout" to "Last completed workout",
    "train_metric_form" to "Form",
    "train_metric_reps" to "Reps",
    "train_metric_streak" to "Streak",
    "train_metric_minutes" to "Minutes",
    "train_program_fallback" to "Program",
    "train_guided_plan" to "A guided %1\$d-week plan matched to your level.",
    "train_featured" to "Featured",
    "train_weeks" to "%1\$d weeks",
    "train_work_complete" to "Today\\'s work is complete",
    "train_current_day" to "Your current training day",
    "train_week_day_sub" to "Week %1\$d · Day %2\$d",
    "train_status_recovery" to "Recovery",
    "train_find_plan" to "Find your plan",
    "train_subtitle_active" to "Your active program and today\\'s sessions.",
    "train_subtitle_complete_today" to "Today\\'s training is complete.",
    "train_subtitle_rest_named" to "Rest day in %1\$s.",
    "train_subtitle_rest" to "Take it easy today.",
    "train_subtitle_program_complete" to "Review your results and choose the next step.",
    "train_subtitle_no_assessment" to "Complete your assessment to generate a plan.",
    "train_subtitle_reassessment" to "A reassessment is due before the next program.",
    "train_subtitle_no_plan" to "Explore programs that match your level.",
    "train_ready_msg_active" to "Your plan is synced and ready for today\\'s work.",
    "train_ready_msg_rest" to "Recovery is part of the plan. Keep it easy today.",
    "train_ready_msg_complete" to "Today\\'s work is complete. Review your form when ready.",
    "train_ready_msg_program_done" to "Program finished. Your next step is ready.",
    "train_ready_msg_no_plan" to "Start with a plan or assessment to personalize training.",
    "train_guide_active" to "Start with the first incomplete session.",
    "train_guide_rest" to "Light mobility and sleep help recovery.",
    "train_guide_complete" to "Open reports to review form and progress.",
    "train_guide_program_done" to "Reassess or move to the next plan.",
    "train_guide_no_plan" to "Choose a program or finish your assessment.",
    "train_quick_explore_sub" to "Find workouts and programs",
    "train_quick_reports_sub" to "Review form and progress",
    "train_quick_tune" to "Tune",
    "train_quick_tune_sub" to "Adjust training preferences",
    "train_featured_programs" to "Featured programs",
    "train_featured_subtitle" to "Start with a guided plan matched to your level.",
    "train_browse_card_sub" to "Explore guided plans matched to your level and goals.",
    "train_browse_metadata" to "Programs · Workouts · Exercises",
    "train_prefs_later" to "Training preferences arrive in a later phase.",
    "train_exercises_count" to "%1\$d exercises",
    "train_quick_explore" to "Explore",
    "train_quick_reports" to "Reports",
    "train_streak_short" to "%1\$dd",
    "train_focus_program" to "Program",
    "train_focus_progress" to "Progress",
    "train_dest_subtitle" to "Your program and today\\'s plan.",
    "reports_title" to "Reports",
    "reports_subtitle" to "Performance &amp; progress",
    "reports_loading" to "Loading your metrics…",
    "reports_pro_title" to "Reports are a Pro feature",
    "reports_pro_message" to "Upgrade to unlock detailed analytics, trends, and export.",
    "reports_upgrade" to "Upgrade",
    "reports_empty_title" to "No reports yet",
    "reports_empty_message" to "Complete your first workout to unlock performance insights.",
    "reports_start_training" to "Start training",
    "reports_tab_overview" to "Overview",
    "reports_tab_exercises" to "Exercises",
    "reports_tab_trends" to "Trends",
    "reports_key_numbers" to "Key numbers",
    "reports_form_journey" to "Form score journey",
    "reports_weekly_breakdown" to "Weekly breakdown",
    "reports_by_exercise" to "By exercise",
    "reports_volume_trend" to "Volume trend",
    "reports_kpi_days" to "Days trained",
    "reports_kpi_reps" to "Total reps",
    "reports_kpi_volume" to "Volume (kg)",
    "reports_kpi_time" to "Training time",
    "reports_form_improving" to "Form improving",
    "reports_form_avg_message" to "Average form score %1\$d%% across tracked sessions.",
    "reports_sessions" to "%1\$d sessions",
    "reports_fatigue_label" to "FATIGUE INDEX",
    "reports_fatigue_elevated" to "Elevated",
    "reports_fatigue_moderate" to "Moderate",
    "reports_period_default" to "Last 30 days",
    "reports_week_short" to "W%1\$d",
    "reports_improvement_rate" to "Improvement rate",
    "reports_improvement_since_week_one" to "%1\$s%% since Week 1",
    "reports_attendance_trend" to "Weekly attendance",
    "reports_loading_sub" to "Pull down to refresh anytime.",
    "reports_athlete_fallback" to "Athlete",
    "explore_title" to "Explore",
    "explore_subtitle" to "Workouts, exercises and programs in one place.",
    "explore_loading" to "Loading Movit library…",
    "explore_no_results" to "No results",
    "explore_try_filter" to "Try a different search or filter.",
    "explore_clear_filters" to "Clear filters",
    "explore_best_start" to "Best place to start",
    "explore_recommended" to "Recommended",
    "explore_see_all" to "See all",
    "explore_smart_pick" to "Smart pick",
    "explore_open_workout" to "Open workout",
    "explore_target_muscle" to "Train a target muscle",
    "explore_workouts" to "Workouts",
    "explore_popular" to "Popular movements",
    "explore_exercises" to "Exercises",
    "explore_guided_paths" to "Guided paths",
    "explore_programs" to "Programs",
    "explore_open" to "Open",
    "explore_search_placeholder" to "Search workouts or exercises…",
    "explore_filter_all" to "All",
    "explore_filter_exercises" to "Exercises",
    "explore_filter_workouts" to "Workouts",
    "explore_filter_programs" to "Programs",
    "explore_item_workout" to "Workout template",
    "explore_item_exercise" to "Exercise",
    "explore_item_program" to "Program",
    "explore_load_error" to "Unable to load explore content.",
    "explore_muscles_count" to "%1\$d muscles",
    "explore_workout_intro" to "Choose a ready session by goal, muscle group, level or time. This is the fastest path for users who know what they want to train today.",
    "explore_filter_button" to "Filter library",
    "explore_workout_filter_beginner" to "Beginner",
    "explore_workout_filter_intermediate" to "Intermediate",
    "explore_workout_filter_advanced" to "Advanced",
    "explore_workout_filter_short" to "Under 20 min",
    "explore_results_summary" to "%1\$d workouts • %2\$d exercises",
    "library_back_explore" to "Explore",
    "library_items_count" to "%1\$d items",
    "library_loading_exercises" to "Loading exercises…",
    "library_loading_workouts" to "Loading workouts…",
    "library_search_exercises" to "Search exercises, muscles, category…",
    "library_search_workouts" to "Search muscle, workout, time…",
    "library_result_exercises" to "Showing %1\$d of %2\$d exercises",
    "library_result_workouts" to "Showing %1\$d of %2\$d workouts",
    "library_see_more_exercises" to "See more exercises",
    "library_see_more_workouts" to "See more workouts",
    "library_no_results" to "No results",
    "library_try_filter" to "Try a different search or filter.",
    "library_clear_filters" to "Clear filters",
    "library_filter_button" to "Filter",
    "library_filter_sheet_title" to "Filter library",
    "library_filter_all" to "All",
    "library_filter_lower_body" to "Lower body",
    "library_filter_legs" to "Legs",
    "library_filter_core" to "Core",
    "library_filter_mobility" to "Mobility",
    "library_filter_equipment" to "Equipment",
    "library_filter_chest" to "Chest",
    "library_filter_under_20" to "Under 20 min",
    "library_featured_workout" to "Best for legs",
    "library_load_error" to "Unable to load library content.",
    "train_day_complete" to "Day complete!",
    "train_day_complete_summary" to "%1\$s · Total %2\$s",
    "train_view_day_summary" to "View day summary",
    "train_form_footer_steady" to "Form score %1\$d%% · steady control",
    "train_tomorrow_preview" to "Tomorrow: %1\$s · %2\$d exercises",
    "train_whats_next" to "What\\'s next",
    "train_metric_time" to "Time",
    "train_metric_work" to "Work",
    "train_metric_focus" to "Focus",
    "train_metric_days" to "Days",
    "train_metric_grade" to "Grade",
    "train_section_today_named" to "Today — %1\$s",
    "train_start_training" to "Start training",
    "train_today_label" to "Today",
    "train_next_step" to "Next step",
    "train_section_review_session" to "Review the session before starting.",
    "train_section_pick_program" to "Pick a program and Movit will schedule it.",
    "train_section_optional_light" to "Optional light work only.",
    "train_section_sessions_complete" to "Your sessions are complete.",
    "train_section_journey_review" to "Your journey is ready to review.",
    "train_no_active_plan" to "No active plan",
    "train_no_plan_rhythm" to "Programs turn goals into a weekly training rhythm.",
    "train_flexible" to "Flexible",
    "train_guided_plan_label" to "Guided plan",
    "train_choose_goal" to "Choose goal",
    "train_get_started" to "Get started",
    "train_today_complete" to "Today complete",
    "train_browse_pick_sub" to "Pick a guided plan and we\\'ll schedule it for you.",
    "train_status_plan_ready" to "Your plan is ready.",
    "train_status_pick_plan" to "Pick a guided plan and Movit will schedule it.",
    "train_status_recovery_part" to "Recovery is part of the plan.",
    "train_status_training_complete" to "Training is complete for today.",
    "train_status_program_review" to "Review your journey and choose next steps.",
    "train_rest_day_label" to "Rest day",
    "train_day_complete_short" to "Day complete",
    "train_quick_actions_sub" to "Jump into the next useful training task.",
    "train_form_trend" to "Form score trend",
    "train_last_7_sessions" to "Last 7 sessions",
    "train_form_improving_card" to "Your form is improving!",
    "train_view_full_reports" to "View full reports",
    "train_readiness_sub" to "How prepared you are today",
    "train_program_complete_banner" to "Program complete!",
    "train_program_complete_summary" to "%1\$s · %2\$s · %3\$s",
    "train_start_program" to "Start program",
    "train_view_journey" to "View your journey",
    "train_week_previous" to "Previous week",
    "train_week_next" to "Next week",
    "train_form_trend_scope" to "Last 7 sessions · achievement",
    "train_form_trend_delta" to "+%1\$d%% vs last week",
    "train_a11y_start_workout" to "Start today\\'s workout",
    "train_a11y_explore_light" to "Explore a light workout",
    "train_a11y_view_journey" to "View your program journey",
    "train_a11y_whats_next" to "See what to do next",
    "train_a11y_form_trend_chart" to "Form score trend for last 7 sessions",
    "train_a11y_start_program" to "Start %1\$s program",
    "train_a11y_preferences" to "Open training preferences",
    "report_detail_loading" to "Loading report…",
    "report_detail_back" to "Back",
    "report_detail_share" to "Share",
    "report_detail_page_overview" to "Overview",
    "report_detail_page_form" to "Form",
    "report_detail_page_fatigue" to "Fatigue",
    "report_detail_page_tips" to "Tips",
    "report_detail_form_score" to "FORM SCORE",
    "report_detail_sets" to "Sets",
    "report_detail_reps" to "Reps",
    "report_detail_duration" to "Duration",
    "report_detail_joint_analysis" to "Joint analysis",
    "report_detail_best_vs_worst" to "Best vs worst rep",
    "report_detail_control_fatigue" to "Control &amp; fatigue",
    "report_detail_form_by_set" to "Form by set",
    "report_detail_set_short" to "S%1\$d",
    "report_detail_coaching_tips" to "Coaching tips",
    "report_detail_export" to "Export report",
    "report_detail_session_overview" to "Session overview",
    "report_detail_avg_form" to "Average form score %1\$d%% across tracked sets.",
    "report_detail_fatigue_low" to "Low",
    "report_detail_best_set" to "Best · Set %1\$d",
    "report_detail_worst_set" to "Worst · Set %1\$d",
    "report_detail_fatigue_not_enough" to "Not enough sets to estimate fatigue yet.",
    "report_detail_form_dropped" to "Form dropped %1\$d%% from set 1 to set %2\$d.",
    "report_detail_form_steady" to "Form held steady across sets.",
    "report_detail_not_found" to "Report not found.",
    "report_detail_joints_unavailable" to "Joint breakdown will appear here when your session includes tracked joints.",
    "report_detail_page_a11y" to "%1\$s, page %2\$d of %3\$d",
    "report_detail_form_score_a11y" to "Form score %1\$d out of 100",
    "report_detail_joint_score_a11y" to "%1\$s, score %2\$d percent",
    "report_detail_set_score_a11y" to "%1\$s, form score %2\$d percent",
    "report_detail_fatigue_a11y" to "Fatigue %1\$s, index %2\$d percent",
    "report_detail_rep_compare_a11y" to "%1\$s, score %2\$d",
    "report_detail_form_by_set_a11y" to "Form by set chart",
    "report_detail_preview_personal_best" to "Personal best",
    "report_detail_preview_insight_title" to "Excellent depth consistency",
    "report_detail_preview_insight_message" to "Hip crease stayed below knee line on 95% of reps.",
    "report_detail_preview_joint_knees" to "Knees",
    "report_detail_preview_joint_hips" to "Hips",
    "report_detail_preview_joint_spine" to "Spine",
    "report_detail_preview_tip1_title" to "Brace your core earlier",
    "report_detail_preview_tip1_message" to "On the descent, engage core 0.5s before hip hinge to protect lumbar spine.",
    "report_detail_preview_tip2_title" to "Keep knees tracking toes",
    "report_detail_preview_tip2_message" to "Slight inward drift on set 4 — focus on pushing knees out.",
    "report_detail_preview_fatigue_message" to "Form dropped 6% from set 1 to set 4 — within normal range.",
    "session_back" to "Back",
    "session_edit" to "Edit",
    "session_done" to "Done",
    "session_add_exercise" to "Add exercise",
    "session_rest" to "Rest",
    "session_loading" to "Loading session…",
    "session_exercises" to "Exercises",
    "session_duration" to "Duration",
    "session_sets" to "Sets",
    "session_ready_to_train" to "Ready to train",
    "session_start" to "Start",
    "session_summary" to "%1\$d exercises · %2\$s",
    "session_editing" to "editing",
    "session_saving" to "saving…",
    "session_swap_title" to "Swap exercise",
    "session_swap_subtitle" to "Replacing %1\$s · %2\$s",
    "session_close" to "Close",
    "session_search_placeholder" to "Search exercises…",
    "session_finding_alternatives" to "Finding alternatives…",
    "session_recommended" to "Recommended",
    "session_change_exercise" to "Change exercise →",
    "session_exercise_fallback" to "Exercise",
    "session_sets_title" to "Sets",
    "session_sets_sub" to "Number of sets",
    "session_hold_title" to "Hold",
    "session_hold_sub" to "Seconds per set",
    "session_reps_title" to "Reps",
    "session_reps_sub" to "Target per set",
    "session_weight_title" to "Weight",
    "session_weight_sub" to "Kilograms",
    "session_rest_title" to "Rest",
    "session_rest_sub" to "Between sets (sec)",
    "session_cancel" to "Cancel",
    "session_save" to "Save",
    "session_workout_fallback" to "Workout",
    "session_week_day" to "Week %1\$d · Day %2\$d",
    "session_best_badge" to "Best",
    "session_phase_warmup" to "Warm-up",
    "session_phase_main" to "Main workout",
    "session_phase_cooldown" to "Cool-down",
    "session_phase_other" to "Other",
    "session_bridge_not_installed" to "Session bridge not installed.",
    "session_workout_not_found" to "Workout not found.",
    "session_data_not_installed" to "Workout data layer is not installed.",
    "session_no_enrollment" to "No active program enrollment.",
    "session_workout_not_in_plan" to "Workout not found in your plan.",
    "program_back" to "Explore",
    "program_customize" to "Customize",
    "program_save" to "Save",
    "program_loading" to "Loading program…",
    "program_tab_overview" to "Overview",
    "program_tab_edit" to "Customize copy",
    "program_copy_title" to "Your personal copy",
    "program_copy_body" to "Changes are saved to your program customizations. The original template stays clean and your schedule can sync back.",
    "program_active_plan" to "Active plan",
    "program_custom_edits" to "%1\$d custom edits",
    "program_edit_copy" to "Edit copy",
    "program_resume_week" to "Resume week 1",
    "program_journey_title" to "Program structure",
    "program_journey_sub" to "Journey",
    "program_weekly_report" to "Weekly report",
    "program_current" to "Current",
    "program_preview" to "Preview",
    "program_done" to "Done",
    "program_next" to "Next",
    "program_details_title" to "What you get",
    "program_details_sub" to "Details",
    "program_start" to "Start program",
    "program_start_next" to "Start next session",
    "program_cancel" to "Cancel",
    "program_save_copy" to "Save my copy",
    "program_edit_customize" to "Customize",
    "program_edit_why_title" to "Why change this plan?",
    "program_edit_note" to "Programs are connected objects. Start with the reason, then edit the smallest safe scope.",
    "program_save_toast" to "Saved to your personal program copy.",
    "program_reason_schedule" to "Schedule changed",
    "program_reason_equipment" to "Equipment missing",
    "program_reason_intensity" to "Too easy / hard",
    "program_reason_injury" to "Injury / discomfort",
    "program_scope_title" to "Choose where the edit applies",
    "program_scope_sub" to "Scope",
    "program_scope_plan" to "Plan settings",
    "program_scope_week" to "Week calendar",
    "program_scope_day" to "Day sessions",
    "program_scope_exercise" to "Exercise targets",
    "program_impact_editing" to "Editing",
    "program_impact_plan" to "Effective plan impact",
    "program_impact_user_copy" to "Only this user copy",
    "program_impact_template" to "Original template",
    "program_impact_unchanged" to "Unchanged",
    "program_setting_start_date" to "Start date",
    "program_setting_start_date_sub" to "Used with paused days to resolve current week and day.",
    "program_setting_weekly" to "Weekly session target",
    "program_setting_weekly_sub" to "Affects expectation and calendar pacing, not exercise content.",
    "program_setting_pause" to "Pause calendar",
    "program_setting_pause_sub" to "Keep progress and customizations, stop date-based advancement.",
    "program_paused" to "Paused",
    "program_active" to "Active",
    "program_not_found" to "Program not found.",
    "session_sets_reps" to "%1\$d × %2\$d",
    "session_sets_duration" to "%1\$d × %2\$ds",
    "session_sets_only" to "%1\$d sets",
    "session_rest_between" to "%1\$ds rest",
    "session_weight_kg" to "%1\$s kg",
    "session_rest_block" to "Rest · %1\$s",
    "session_a11y_swap" to "Swap exercise",
    "session_a11y_edit" to "Edit exercise details",
    "session_a11y_delete" to "Delete exercise",
    "session_a11y_reorder" to "Reorder exercise",
    "session_a11y_exercise_thumb" to "%1\$s thumbnail",
    "session_a11y_start_workout" to "Start workout session",
    "session_add_title" to "Add exercise",
    "session_add_subtitle" to "Pick an exercise to append",
    "session_edit_rest_title" to "Edit rest",
    "session_add_rest_confirm" to "Add rest",
    "session_alternatives" to "Alternatives",
    "session_bodyweight" to "Bodyweight",
    "session_weighted" to "Weighted",
    "prepare_back" to "Back",
    "prepare_title" to "Prepare Workout",
    "prepare_rest_title" to "Rest Interval",
    "prepare_loading" to "Loading exercise…",
    "prepare_not_found" to "Exercise not found.",
    "prepare_up_next" to "Up Next Exercise",
    "prepare_looping_preview" to "Looping Preview",
    "prepare_camera_setup" to "Camera Setup Guide",
    "prepare_instructions" to "Instructions",
    "prepare_target_muscles" to "Target Muscles",
    "prepare_stat_sets" to "Sets",
    "prepare_stat_reps" to "Reps",
    "prepare_stat_duration" to "Duration",
    "prepare_stat_rest" to "Rest",
    "prepare_add_rest" to "+15",
    "prepare_skip_rest" to "Skip",
    "prepare_training_bridge_unavailable" to "Camera training is not available on this device yet.",
    "workout_flow_back" to "Back",
    "workout_flow_customize_title" to "Customize workout",
    "workout_flow_run_title" to "Workout run",
    "workout_flow_loading" to "Loading workout…",
    "workout_flow_customize_meta" to "%1\$d exercises · ~%2\$d min estimated",
    "workout_flow_exercises" to "Exercises",
    "workout_flow_rest_between_sets" to "Rest between sets",
    "workout_flow_rest_seconds" to "%1\$ds",
    "workout_flow_dock_summary" to "%1\$d exercises · %2\$ds rest",
    "workout_flow_exercise_of" to "EXERCISE %1\$d OF %2\$d",
    "workout_flow_set_reps" to "Set %1\$d of %2\$d · %3\$d reps",
    "workout_flow_set_hold" to "Set %1\$d of %2\$d · %3\$ds",
    "workout_flow_done" to "Done",
    "workout_flow_now" to "Now",
    "workout_flow_previous_form" to "Previous: %1\$d%% form",
    "workout_flow_start_exercise" to "Start exercise",
    "workout_flow_a11y_sequence" to "%1\$s, %2\$s",
    "workout_flow_a11y_pending" to "Upcoming",
    "workout_flow_a11y_progress" to "Workout progress %1\$d percent",
    "program_flow_list_title" to "Programs",
    "program_flow_loading" to "Loading programs…",
    "program_flow_empty_title" to "No programs yet",
    "program_flow_empty_message" to "Check your connection and try again.",
    "program_flow_weeks_days" to "%1\$d weeks · %2\$d days/week",
    "program_flow_week_title" to "Week %1\$d",
    "program_flow_open_today" to "Open today\\'s session",
    "program_flow_view_week_report" to "View week report",
    "program_flow_week_report_title" to "Week %1\$d report",
    "program_flow_week_report_fallback" to "Weekly report",
    "program_flow_metric_sessions" to "Sessions",
    "program_flow_metric_form" to "Avg form",
    "program_flow_metric_reps" to "Reps",
    "program_flow_daily_form" to "Daily form scores",
    "program_flow_share_report" to "Share report",
    "program_flow_share_coming_soon" to "Share report is coming soon.",
    "program_flow_status_done" to "Completed",
    "program_flow_status_today" to "Today",
    "program_flow_status_planned" to "Planned",
    "program_flow_status_rest" to "Rest day",
    "program_flow_a11y_day" to "Day %1\$d, %2\$s. %3\$s. %4\$s",
    "program_flow_a11y_chart" to "Daily form scores chart",
    "auth_app_name" to "WayToFix",
    "auth_tagline" to "AI-powered form coaching",
    "auth_version" to "Version 1.0.0",
    "auth_intro_title_1" to "Train with confidence",
    "auth_intro_sub_1" to "Real-time pose feedback helps you move safely and effectively.",
    "auth_intro_title_2" to "Track your progress",
    "auth_intro_sub_2" to "Reports, trends, and level insights keep you improving.",
    "auth_intro_title_3" to "Programs that fit you",
    "auth_intro_sub_3" to "Personalized plans based on your body scan and goals.",
    "auth_continue" to "Continue",
    "auth_skip" to "Skip",
    "auth_welcome_back" to "Welcome back",
    "auth_sign_in_sub" to "Sign in to continue your training journey.",
    "auth_email" to "Email",
    "auth_password" to "Password",
    "auth_remember_me" to "Remember me",
    "auth_forgot_password" to "Forgot password?",
    "auth_sign_in" to "Sign in",
    "auth_google" to "Continue with Google",
    "auth_or" to "or",
    "auth_no_account" to "Don\\'t have an account?",
    "auth_sign_up" to "Sign up",
    "auth_create_account" to "Create account",
    "auth_sign_up_sub" to "Join thousands training smarter with AI form analysis.",
    "auth_full_name" to "Full name",
    "auth_have_account" to "Already have an account?",
    "auth_back" to "← Back",
    "auth_reset_password" to "Reset password",
    "auth_reset_sub" to "Enter your email and we\\'ll send a reset link.",
    "auth_send_reset" to "Send reset link",
    "auth_reset_sent" to "Password reset link sent!",
    "auth_reset_sent_sub" to "Check your email for the reset link.",
    "auth_back_to_sign_in" to "Back to Sign In",
    "auth_google_unavailable" to "Google Sign-In is not available in this build yet.",
    "auth_error_email_required" to "Enter your email address.",
    "auth_error_email_invalid" to "Enter a valid email address.",
    "auth_error_password_required" to "Enter your password.",
    "auth_error_name_required" to "Enter your full name.",
    "auth_error_password_short" to "Password must be at least 8 characters.",
    "auth_logo_content_desc" to "WayToFix app logo",
    "auth_intro_icon_desc" to "Intro illustration",
    "auth_forgot_success_icon_desc" to "Email sent",
    "auth_intro_page_indicator" to "Intro page %1\$d of %2\$d",
    "profile_loading" to "Loading profile…",
    "profile_sign_in_sub" to "Sign in to sync workouts, reports, and your training level.",
    "profile_preferences" to "Preferences",
    "profile_appearance" to "Appearance",
    "profile_appearance_sub" to "Light · Dark · System",
    "profile_audio_cues" to "Audio cues",
    "profile_haptic" to "Haptic feedback",
    "profile_training" to "Training",
    "profile_training_profile" to "Training profile",
    "profile_body_assessment" to "Body assessment",
    "profile_body_assessment_sub" to "PAR-Q + body scan history",
    "profile_level_plan" to "Level &amp; plan",
    "profile_level_plan_sub" to "Body score, domains, training path",
    "profile_support" to "Support",
    "profile_sign_out" to "Sign out",
    "profile_pro_badge" to "PRO ACTIVE",
    "profile_manage_subscription" to "Manage subscription",
    "profile_unlock_pro" to "Unlock Pro",
    "profile_unlock_pro_sub" to "Advanced reports, program analytics, and unlimited body scans.",
    "profile_view_plans" to "View plans",
    "profile_back" to "Back",
    "profile_sub_best_value" to "Best value",
    "profile_sub_price" to "\$9.99",
    "profile_sub_per_month" to "per month",
    "profile_sub_feature_reports" to "Full reports &amp; trends",
    "profile_sub_feature_insights" to "Program progression insights",
    "profile_sub_feature_scans" to "Unlimited body scans",
    "profile_sub_feature_support" to "Priority support",
    "profile_subscribe_now" to "Subscribe now",
    "profile_restore_purchases" to "Restore purchases",
    "profile_sub_annual" to "Annual plan",
    "profile_sub_annual_sub" to "\$79.99 / year · save 33%",
    "profile_account" to "Account",
    "profile_edit_profile" to "Edit profile",
    "profile_appearance_light" to "Light",
    "profile_appearance_dark" to "Dark",
    "profile_appearance_system" to "System",
    "profile_cancel" to "Cancel",
    "profile_logout_confirm_title" to "Sign out?",
    "profile_logout_confirm_message" to "You will need to sign in again to sync workouts and reports.",
    "profile_avatar_cd" to "Profile photo",
    "profile_edit_avatar_cd" to "Edit profile photo",
    "onboarding_step_label" to "Step %1\$d of %2\$d",
    "onboarding_back" to "Back",
    "onboarding_continue" to "Continue",
    "onboarding_finish" to "Start journey",
    "onboarding_about_you" to "About you",
    "onboarding_about_you_sub" to "This helps us personalize your training plan.",
    "onboarding_age" to "Age",
    "onboarding_sex_label" to "Biological sex (for norms)",
    "onboarding_sex_male" to "Male",
    "onboarding_sex_female" to "Female",
    "onboarding_sex_other" to "Other",
    "onboarding_metrics" to "Body metrics",
    "onboarding_metrics_sub" to "Used for load recommendations and scan comparison.",
    "onboarding_height" to "Height (cm)",
    "onboarding_weight" to "Weight (kg)",
    "onboarding_metrics_hint_title" to "Optional but helpful",
    "onboarding_metrics_hint_sub" to "Improves recommendations and body scan comparison.",
    "onboarding_experience_eyebrow" to "Experience",
    "onboarding_experience_title" to "How trained are you?",
    "onboarding_experience_sub" to "We\\'ll match volume and progression to your background.",
    "onboarding_exp_beginner" to "Beginner",
    "onboarding_exp_intermediate" to "Intermediate",
    "onboarding_exp_advanced" to "Advanced",
    "onboarding_sessions_per_week" to "Sessions per week",
    "onboarding_goal_title" to "Your goal",
    "onboarding_goal_sub" to "What do you want to focus on?",
    "onboarding_goal_strength" to "Build strength",
    "onboarding_goal_weight" to "Lose weight",
    "onboarding_goal_mobility" to "Improve mobility",
    "onboarding_goal_strength_sub" to "Progressive overload &amp; compound lifts",
    "onboarding_goal_general_health_sub" to "Sustainable fat loss &amp; conditioning",
    "onboarding_goal_hypertrophy_sub" to "Flexibility &amp; joint health",
    "onboarding_days_title" to "Training days",
    "onboarding_days_sub" to "Pick the weekdays you can train.",
    "onboarding_location_title" to "Where do you train?",
    "onboarding_location_sub" to "Home or gym affects equipment defaults.",
    "onboarding_location_home" to "Home",
    "onboarding_location_gym" to "Gym",
    "onboarding_equipment_title" to "Available equipment",
    "onboarding_equipment_dumbbell" to "Dumbbells",
    "onboarding_equipment_bands" to "Bands",
    "onboarding_equipment_kettlebell" to "Kettlebell",
    "onboarding_equipment_pull_up_bar" to "Pull-up bar",
    "onboarding_equipment_bench" to "Bench",
    "onboarding_equipment_mat" to "Mat",
    "onboarding_summary_title" to "Summary",
    "onboarding_summary_sub" to "Review before we build your plan.",
    "onboarding_summary_age" to "Age &amp; sex",
    "onboarding_summary_metrics" to "Metrics",
    "onboarding_summary_experience" to "Experience",
    "onboarding_summary_goal" to "Goal",
    "onboarding_summary_days" to "Training days",
    "onboarding_summary_equipment" to "Location",
    "onboarding_disclaimer" to "I confirm the information is accurate and I\\'m cleared to exercise.",
    "onboarding_saving" to "Saving…",
    "onboarding_retry_save" to "Try again",
    "onboarding_save_failed_title" to "Couldn\\'t save profile",
    "onboarding_progress_a11y" to "Onboarding progress, step %1\$d of %2\$d",
    "onboarding_summary_profile_label" to "Your profile",
    "onboarding_sessions_value" to "%1\$d sessions",
    "onboarding_weekdays_hint" to "%1\$d of %2\$d days",
    "onboarding_location_home_sub" to "Limited equipment",
    "onboarding_location_gym_sub" to "Full access",
    "onboarding_equipment_all" to "Full gym equipment",
    "onboarding_equipment_bodyweight" to "Bodyweight",
    "onboarding_error_age_required" to "Enter your age to continue.",
    "onboarding_error_age_range" to "Age must be between 13 and 90.",
    "onboarding_error_sex_required" to "Select biological sex to continue.",
    "onboarding_error_height_range" to "Height must be between 120 and 220 cm.",
    "onboarding_error_weight_range" to "Weight must be between 30 and 200 kg.",
    "onboarding_error_experience_required" to "Select your experience level.",
    "onboarding_error_sessions_required" to "Select sessions per week.",
    "onboarding_error_goal_required" to "Select a training goal.",
    "onboarding_error_weekdays_required" to "Select at least one training day.",
    "onboarding_error_location_required" to "Select where you train.",
    "onboarding_error_equipment_required" to "Select at least one piece of equipment.",
    "onboarding_error_disclaimer_required" to "Accept the disclaimer to finish.",
    "onboarding_error_step_incomplete" to "Complete this step to continue.",
    "onboarding_weekday_sun" to "Sun",
    "onboarding_weekday_mon" to "Mon",
    "onboarding_weekday_tue" to "Tue",
    "onboarding_weekday_wed" to "Wed",
    "onboarding_weekday_thu" to "Thu",
    "onboarding_weekday_fri" to "Fri",
    "onboarding_weekday_sat" to "Sat",
    "assessment_health_check" to "Health check",
    "assessment_results_title" to "Assessment results",
    "assessment_parq_title" to "PAR-Q+ screening",
    "assessment_parq_sub" to "Answer honestly. If you answer Yes to any question, consult a physician before training.",
    "assessment_parq_physician_warning" to "Consult a physician before training if you answered Yes to any question.",
    "assessment_parq_progress" to "%1\$d of %2\$d answered",
    "assessment_parq_progress_a11y" to "PAR-Q progress, %1\$d of %2\$d answered",
    "assessment_region_score_a11y" to "%1\$s score %2\$d percent",
    "assessment_parq_heart" to "Has a doctor ever said you have a heart condition?",
    "assessment_parq_chest_pain" to "Do you feel pain in your chest during physical activity?",
    "assessment_parq_dizziness" to "Do you lose balance because of dizziness or lose consciousness?",
    "assessment_parq_bone_joint" to "Do you have a bone or joint problem that could be worsened by exercise?",
    "assessment_parq_medication" to "Are you currently prescribed medication for blood pressure or heart condition?",
    "assessment_parq_other_reason" to "Is there any other reason you should not participate in physical activity?",
    "assessment_parq_pregnancy" to "Are you pregnant or have you given birth in the last 6 months?",
    "assessment_no" to "No",
    "assessment_yes" to "Yes",
    "assessment_continue_scan" to "Continue to body scan",
    "assessment_body_scan" to "Body scan",
    "assessment_body_scan_sub" to "Stand in frame · 3 movements · ~5 min",
    "assessment_scan_hint" to "%1\$s · Movement %2\$d of %3\$d",
    "assessment_movement_forward_fold" to "Forward fold",
    "assessment_movement_overhead_squat" to "Overhead squat",
    "assessment_movement_single_leg_balance" to "Single-leg balance",
    "assessment_hold_position" to "Hold position",
    "assessment_camera_active" to "Camera active",
    "assessment_camera_active_sub" to "Analyzing joint angles in real time",
    "assessment_camera_placeholder" to "Camera preview",
    "assessment_camera_placeholder_sub" to "Live pose analysis opens in a later phase.",
    "assessment_view_results" to "View results",
    "assessment_body_score" to "BODY SCORE",
    "assessment_domain_scores" to "Assessment domains",
    "assessment_domain_mobility" to "Mobility",
    "assessment_domain_control" to "Control",
    "assessment_domain_symmetry" to "Symmetry",
    "assessment_domain_safety" to "Safety",
    "assessment_region_scores" to "Region scores",
    "assessment_region_hips" to "Hips",
    "assessment_region_hip" to "Hip",
    "assessment_region_shoulders" to "Shoulders",
    "assessment_region_shoulder" to "Shoulder",
    "assessment_region_spine" to "Spine",
    "assessment_region_knees" to "Knees",
    "assessment_region_knee" to "Knee",
    "assessment_insights" to "Insights",
    "assessment_insight_shoulder_title" to "Limited shoulder flexion",
    "assessment_insight_shoulder_message" to "May affect overhead pressing. Consider mobility work before heavy loads.",
    "assessment_insight_hip_title" to "Good hip hinge pattern",
    "assessment_insight_hip_message" to "Deadlift and squat patterns look solid. Ready for progressive loading.",
    "assessment_insight_limiting_title" to "%1\$s needs attention",
    "assessment_insight_limiting_message" to "Gap of %1\$d levels before progression.",
    "assessment_insight_region_limit_title" to "Limited %1\$s mobility",
    "assessment_insight_region_limit_message" to "Region score %1\$d — consider mobility work.",
    "assessment_browse_programs" to "Browse programs",
    "assessment_go_home" to "Go to Home",
    "level_tab_profile" to "Level profile",
    "level_tab_plan" to "Your plan",
    "level_loading" to "Loading level profile…",
    "level_current" to "CURRENT LEVEL",
    "level_named" to "Level %1\$d · %2\$s",
    "level_progress_sub" to "%1\$d points to Level %2\$d · Reassessment %3\$s",
    "level_domain_breakdown" to "Domain breakdown",
    "level_retake_scan" to "Retake body scan",
    "level_retake_scan_sub" to "Track improvements and unlock progression reassessment.",
    "level_start_scan" to "Start scan",
    "level_body_score" to "Body score",
    "level_plan_title" to "Your training plan",
    "level_plan_sub" to "Personalized path based on your level &amp; goals",
    "level_browse_programs" to "Browse recommended programs",
    "level_plan_empty" to "No active training plan yet. Browse programs to get started.",
    "level_phase_completed" to "Completed",
    "level_phase_in_progress" to "In progress",
    "level_phase_upcoming" to "Upcoming",
    "level_phase_weeks" to "%1\$s · %2\$d weeks",
    "level_phase_week_progress" to "Week %1\$d of %2\$d",
    "level_reassessment_next" to "Next reassessment after Week %1\$d",
    "level_reassessment_scheduled" to "Scheduled for %1\$s",
    "level_reassessment_soon" to "in 2 weeks",
    "level_unlocks_after_progression" to "Unlocks after progression check",
    "level_domain_mobility" to "Mobility",
    "level_domain_stability" to "Stability",
    "level_domain_strength" to "Strength",
    "level_domain_control" to "Control",
    "level_domain_symmetry" to "Symmetry",
    "level_domain_safety" to "Safety",
    "level_body_score_ring_a11y" to "Body score %1\$d out of 100",
    "level_domain_score_a11y" to "%1\$s score %2\$d percent",
    "shell_report_share_coming_soon" to "Share report — coming soon.",
    "shell_report_export_coming_soon" to "Export report — coming soon.",
)
