package com.movit.resources

// Generated from composeResources/values/strings.xml — do not edit manually.
internal val movitEnglishStrings: Map<String, String> = mapOf(
    "nav_home" to "Home",
    "nav_train" to "Train",
    "nav_explore" to "Explore",
    "nav_reports" to "Reports",
    "nav_account" to "Account",
    "profile_title" to "Account",
    "profile_subtitle" to "Account settings and subscription.",
    "profile_signed_in" to "Signed in",
    "profile_sign_in_prompt" to "Sign in to sync your data",
    "profile_language" to "Language",
    "profile_language_en" to "English",
    "profile_language_ar" to "Arabic",
    "profile_subscription" to "Subscription",
    "profile_pro_active" to "Pro — reports unlocked",
    "profile_free_plan" to "Free — upgrade for coach reports",
    "dest_home_subtitle" to "Your daily training dashboard.",
    "dest_train_subtitle" to "Your program and today\\'s plan.",
    "dest_explore_subtitle" to "Browse workouts, exercises and programs.",
    "dest_reports_subtitle" to "Session history and performance insights.",
    "home_loading" to "Loading your dashboard…",
    "home_view_level" to "View level",
    "home_plan_adjusted" to "Training plan adjusted",
    "home_active_program" to "Active program",
    "home_program" to "Program",
    "home_todays_plan" to "Today\\'s plan",
    "home_today" to "Today",
    "home_body_scan" to "Body scan",
    "home_body_scan_subtitle" to "Measure mobility &amp; posture to unlock your personalized level.",
    "home_start_scan" to "Start scan",
    "home_no_program" to "No active program",
    "home_no_program_message" to "Browse guided plans on Train or explore free workouts.",
    "home_browse_programs" to "Browse programs",
    "home_your_journey" to "Your journey",
    "home_progress" to "Progress",
    "home_view_plan" to "View plan",
    "home_recent_activity" to "Recent activity",
    "home_insights" to "Insights",
    "home_all_reports" to "All reports",
    "home_quick_actions" to "Quick actions",
    "home_metric_this_week" to "This week",
    "home_metric_form_avg" to "Form avg",
    "home_metric_streak" to "Day streak",
    "home_your_level" to "Your level",
    "home_level_title" to "Level %1\$d%2\$s",
    "home_level_code_suffix" to " · %1\$s",
    "home_body_score_pts" to "Body score %1\$d · %2\$d pts to next level",
    "home_body_score_only" to "Body score %1\$d",
    "home_current_plan" to "CURRENT PLAN",
    "home_active_program_fallback" to "Active program",
    "home_week_progress" to "Week %1\$d of %2\$d · %3\$d/%4\$d workouts this week",
    "home_view_program" to "View program",
    "home_todays_workout" to "Today\\'s workout",
    "home_exercises_count" to "%1\$d exercises",
    "home_min_est" to "~%1\$d min",
    "home_dash" to "—",
    "home_completed_today" to "Completed today",
    "home_workout_progress" to "Workout %1\$d of %2\$d today",
    "home_ready_to_start" to "Ready to start",
    "home_start_workout" to "Start workout",
    "home_week_day_label" to "WEEK %1\$d · DAY %2\$d",
    "home_active_recovery" to "Active recovery",
    "home_rest_day" to "Rest day",
    "home_recovery_subtitle" to "Recovery keeps your plan on track.",
    "home_rest" to "Rest",
    "home_no_workout" to "No workout",
    "home_take_it_easy" to "Take it easy today",
    "home_view_train" to "View Train",
    "home_your_plan_label" to "YOUR PLAN",
    "home_program_complete" to "Program complete",
    "home_program_complete_subtitle" to "Time to reassess and unlock your next level.",
    "home_complete" to "Complete",
    "home_great_work" to "Great work finishing the program",
    "home_start_reassessment" to "Start reassessment",
    "home_start_body_scan" to "Start with a body scan",
    "home_unlock_level" to "Unlock a personalized training level.",
    "home_assessment" to "Assessment",
    "home_required_before_plan" to "Required before your first plan",
    "home_plan_timeline" to "Plan timeline",
    "home_week_in_progress" to "Week %1\$d of %2\$d in progress",
    "home_reassessment_due" to "Reassessment due",
    "home_soon" to "Soon",
    "home_last_session" to "Last session",
    "home_greeting_morning" to "Good morning",
    "home_greeting_afternoon" to "Good afternoon",
    "home_greeting_evening" to "Good evening",
    "home_greeting_active" to "Ready for today\\'s session?",
    "home_greeting_rest" to "Rest day — recover and come back stronger.",
    "home_greeting_no_plan" to "Let\\'s find your next workout.",
    "home_greeting_no_assessment" to "Start with a body scan to get your plan.",
    "home_greeting_program_complete" to "Program complete — time to reassess.",
    "home_greeting_reassessment" to "Reassessment due — let\\'s recalibrate.",
    "home_greeting_default" to "Let\\'s get moving.",
    "home_quick_explore" to "Explore",
    "home_quick_explore_sub" to "Browse workouts and exercises",
    "home_quick_reports" to "Reports",
    "home_quick_reports_sub" to "Review your progress",
    "home_activity_form" to "%1\$s · %2\$d%% form",
    "home_activity_reps" to "%1\$d reps · %2\$s",
    "home_action_unavailable" to "Action not available yet.",
    "home_program_week_subtitle" to "Week %1\$d of %2\$d · %3\$d/%4\$d workouts this week",
    "home_level_named" to "Level %1\$d · %2\$s",
    "home_body_score_pts_next" to "Body score %1\$d · %2\$d pts to next level",
    "home_min_total" to "%1\$d min",
    "home_report_reps" to "%1\$d reps",
    "home_today_caps" to "TODAY",
    "train_title" to "Train",
    "train_loading" to "Loading your training plan…",
    "train_browse_programs" to "Browse all programs",
    "train_active_program" to "Active program",
    "train_week_day_position" to "Week %1\$d of %2\$d · Day %3\$d",
    "train_active_plan" to "Active plan",
    "train_workouts_this_week" to "%1\$d workouts this week",
    "train_day_streak" to "%1\$d day streak",
    "train_no_active_program" to "No active program",
    "train_zero_exercises" to "0 exercises",
    "train_explore_programs" to "Explore programs",
    "train_program_complete" to "Program complete",
    "train_program_complete_sub" to "Review your journey and choose the next step.",
    "train_view_report" to "View report",
    "train_active_recovery" to "Active recovery",
    "train_recovery_day" to "Recovery day",
    "train_rest_in_program" to "Rest day in %1\$s.",
    "train_recover_today" to "Recover today and come back stronger.",
    "train_no_workout" to "No workout",
    "train_recovery" to "Recovery",
    "train_explore_recovery" to "Explore recovery",
    "train_training" to "Training",
    "train_start_session" to "Start session",
    "train_completed" to "Completed",
    "train_workout_n_of_m" to "Workout %1\$d of %2\$d today",
    "train_ready" to "Ready",
    "train_todays_workout" to "Today\\'s workout",
    "train_view_summary" to "View summary",
    "train_this_week" to "This week",
    "train_week_title" to "Week %1\$d",
    "train_day_short" to "D%1\$d",
    "train_readiness" to "Readiness",
    "train_latest_report" to "Latest report",
    "train_last_workout" to "Last completed workout",
    "train_metric_form" to "Form",
    "train_metric_reps" to "Reps",
    "train_metric_streak" to "Streak",
    "train_metric_minutes" to "Minutes",
    "train_program_fallback" to "Program",
    "train_guided_plan" to "A guided %1\$d-week plan matched to your level.",
    "train_featured" to "Featured",
    "train_weeks" to "%1\$d weeks",
    "train_work_complete" to "Today\\'s work is complete",
    "train_current_day" to "Your current training day",
    "train_week_day_sub" to "Week %1\$d · Day %2\$d",
    "train_status_recovery" to "Recovery",
    "train_find_plan" to "Find your plan",
    "train_subtitle_active" to "Your active program and today\\'s sessions.",
    "train_subtitle_complete_today" to "Today\\'s training is complete.",
    "train_subtitle_rest_named" to "Rest day in %1\$s.",
    "train_subtitle_rest" to "Take it easy today.",
    "train_subtitle_program_complete" to "Review your results and choose the next step.",
    "train_subtitle_no_assessment" to "Complete your assessment to generate a plan.",
    "train_subtitle_reassessment" to "A reassessment is due before the next program.",
    "train_subtitle_no_plan" to "Explore programs that match your level.",
    "train_ready_msg_active" to "Your plan is synced and ready for today\\'s work.",
    "train_ready_msg_rest" to "Recovery is part of the plan. Keep it easy today.",
    "train_ready_msg_complete" to "Today\\'s work is complete. Review your form when ready.",
    "train_ready_msg_program_done" to "Program finished. Your next step is ready.",
    "train_ready_msg_no_plan" to "Start with a plan or assessment to personalize training.",
    "train_guide_active" to "Start with the first incomplete session.",
    "train_guide_rest" to "Light mobility and sleep help recovery.",
    "train_guide_complete" to "Open reports to review form and progress.",
    "train_guide_program_done" to "Reassess or move to the next plan.",
    "train_guide_no_plan" to "Choose a program or finish your assessment.",
    "train_quick_explore_sub" to "Find workouts and programs",
    "train_quick_reports_sub" to "Review form and progress",
    "train_quick_tune" to "Tune",
    "train_quick_tune_sub" to "Adjust training preferences",
    "train_featured_programs" to "Featured programs",
    "train_featured_subtitle" to "Start with a guided plan matched to your level.",
    "train_browse_card_sub" to "Explore guided plans matched to your level and goals.",
    "train_browse_metadata" to "Programs · Workouts · Exercises",
    "train_prefs_later" to "Training preferences arrive in a later phase.",
    "train_exercises_count" to "%1\$d exercises",
    "train_quick_explore" to "Explore",
    "train_quick_reports" to "Reports",
    "train_streak_short" to "%1\$dd",
    "train_focus_program" to "Program",
    "train_focus_progress" to "Progress",
    "train_dest_subtitle" to "Your program and today\\'s plan.",
    "reports_title" to "Reports",
    "reports_subtitle" to "Performance &amp; progress",
    "reports_loading" to "Loading your metrics…",
    "reports_pro_title" to "Reports are a Pro feature",
    "reports_pro_message" to "Upgrade to unlock detailed analytics, trends, and export.",
    "reports_upgrade" to "Upgrade",
    "reports_empty_title" to "No reports yet",
    "reports_empty_message" to "Complete your first workout to unlock performance insights.",
    "reports_start_training" to "Start training",
    "reports_tab_overview" to "Overview",
    "reports_tab_exercises" to "Exercises",
    "reports_tab_trends" to "Trends",
    "reports_key_numbers" to "Key numbers",
    "reports_form_journey" to "Form score journey",
    "reports_weekly_breakdown" to "Weekly breakdown",
    "reports_by_exercise" to "By exercise",
    "reports_volume_trend" to "Volume trend",
    "reports_kpi_days" to "Days trained",
    "reports_kpi_reps" to "Total reps",
    "reports_kpi_volume" to "Volume (kg)",
    "reports_kpi_time" to "Training time",
    "reports_form_improving" to "Form improving",
    "reports_form_avg_message" to "Average form score %1\$d%% across tracked sessions.",
    "reports_sessions" to "%1\$d sessions",
    "reports_fatigue_label" to "FATIGUE INDEX",
    "reports_fatigue_elevated" to "Elevated",
    "reports_fatigue_moderate" to "Moderate",
    "reports_period_default" to "Last 30 days",
    "reports_week_short" to "W%1\$d",
    "reports_athlete_fallback" to "Athlete",
    "explore_title" to "Explore",
    "explore_subtitle" to "Workouts, exercises and programs in one place.",
    "explore_loading" to "Loading Movit library…",
    "explore_no_results" to "No results",
    "explore_try_filter" to "Try a different search or filter.",
    "explore_clear_filters" to "Clear filters",
    "explore_best_start" to "Best place to start",
    "explore_recommended" to "Recommended",
    "explore_see_all" to "See all",
    "explore_smart_pick" to "Smart pick",
    "explore_open_workout" to "Open workout",
    "explore_target_muscle" to "Train a target muscle",
    "explore_workouts" to "Workouts",
    "explore_popular" to "Popular movements",
    "explore_exercises" to "Exercises",
    "explore_guided_paths" to "Guided paths",
    "explore_programs" to "Programs",
    "explore_open" to "Open",
    "explore_search_placeholder" to "Search workouts or exercises…",
    "explore_filter_all" to "All",
    "explore_filter_exercises" to "Exercises",
    "explore_filter_workouts" to "Workouts",
    "explore_filter_programs" to "Programs",
    "explore_item_workout" to "Workout template",
    "explore_item_exercise" to "Exercise",
    "explore_item_program" to "Program",
    "explore_load_error" to "Unable to load explore content.",
    "explore_muscles_count" to "%1\$d muscles",
    "train_day_complete" to "Day complete!",
    "train_day_complete_summary" to "%1\$s · Total %2\$s",
    "train_view_day_summary" to "View day summary",
    "train_form_footer_steady" to "Form score %1\$d%% · steady control",
    "train_tomorrow_preview" to "Tomorrow: %1\$s · %2\$d exercises",
    "train_whats_next" to "What\\'s next",
    "train_metric_time" to "Time",
    "train_metric_work" to "Work",
    "train_metric_focus" to "Focus",
    "train_metric_days" to "Days",
    "train_metric_grade" to "Grade",
    "train_section_today_named" to "Today — %1\$s",
    "train_start_training" to "Start training",
    "train_today_label" to "Today",
    "train_next_step" to "Next step",
    "train_section_review_session" to "Review the session before starting.",
    "train_section_pick_program" to "Pick a program and Movit will schedule it.",
    "train_section_optional_light" to "Optional light work only.",
    "train_section_sessions_complete" to "Your sessions are complete.",
    "train_section_journey_review" to "Your journey is ready to review.",
    "train_no_active_plan" to "No active plan",
    "train_no_plan_rhythm" to "Programs turn goals into a weekly training rhythm.",
    "train_flexible" to "Flexible",
    "train_guided_plan_label" to "Guided plan",
    "train_choose_goal" to "Choose goal",
    "train_get_started" to "Get started",
    "train_today_complete" to "Today complete",
    "train_browse_pick_sub" to "Pick a guided plan and we\\'ll schedule it for you.",
    "train_status_plan_ready" to "Your plan is ready.",
    "train_status_pick_plan" to "Pick a guided plan and Movit will schedule it.",
    "train_status_recovery_part" to "Recovery is part of the plan.",
    "train_status_training_complete" to "Training is complete for today.",
    "train_status_program_review" to "Review your journey and choose next steps.",
    "train_rest_day_label" to "Rest day",
    "train_day_complete_short" to "Day complete",
    "train_quick_actions_sub" to "Jump into the next useful training task.",
    "train_form_trend" to "Form score trend",
    "train_last_7_sessions" to "Last 7 sessions",
    "train_form_improving_card" to "Your form is improving!",
    "train_view_full_reports" to "View full reports",
    "train_readiness_sub" to "How prepared you are today",
    "train_program_complete_banner" to "Program complete!",
    "train_program_complete_summary" to "%1\$s · %2\$s · %3\$s",
    "report_detail_loading" to "Loading report…",
    "report_detail_back" to "Back",
    "report_detail_share" to "Share",
    "report_detail_page_overview" to "Overview",
    "report_detail_page_form" to "Form",
    "report_detail_page_fatigue" to "Fatigue",
    "report_detail_page_tips" to "Tips",
    "report_detail_form_score" to "FORM SCORE",
    "report_detail_sets" to "Sets",
    "report_detail_reps" to "Reps",
    "report_detail_duration" to "Duration",
    "report_detail_joint_analysis" to "Joint analysis",
    "report_detail_best_vs_worst" to "Best vs worst rep",
    "report_detail_control_fatigue" to "Control &amp; fatigue",
    "report_detail_form_by_set" to "Form by set",
    "report_detail_set_short" to "S%1\$d",
    "report_detail_coaching_tips" to "Coaching tips",
    "report_detail_export" to "Export report",
    "report_detail_session_overview" to "Session overview",
    "report_detail_avg_form" to "Average form score %1\$d%% across tracked sets.",
    "report_detail_fatigue_low" to "Low",
    "report_detail_best_set" to "Best · Set %1\$d",
    "report_detail_worst_set" to "Worst · Set %1\$d",
    "report_detail_fatigue_not_enough" to "Not enough sets to estimate fatigue yet.",
    "report_detail_form_dropped" to "Form dropped %1\$d%% from set 1 to set %2\$d.",
    "report_detail_form_steady" to "Form held steady across sets.",
    "report_detail_not_found" to "Report not found.",
    "session_back" to "Back",
    "session_edit" to "Edit",
    "session_done" to "Done",
    "session_add_exercise" to "Add exercise",
    "session_rest" to "Rest",
    "session_loading" to "Loading session…",
    "session_exercises" to "Exercises",
    "session_duration" to "Duration",
    "session_sets" to "Sets",
    "session_ready_to_train" to "Ready to train",
    "session_start" to "Start",
    "session_summary" to "%1\$d exercises · %2\$s",
    "session_editing" to "editing",
    "session_saving" to "saving…",
    "session_swap_title" to "Swap exercise",
    "session_swap_subtitle" to "Replacing %1\$s · %2\$s",
    "session_close" to "Close",
    "session_search_placeholder" to "Search exercises…",
    "session_finding_alternatives" to "Finding alternatives…",
    "session_recommended" to "Recommended",
    "session_change_exercise" to "Change exercise →",
    "session_exercise_fallback" to "Exercise",
    "session_sets_title" to "Sets",
    "session_sets_sub" to "Number of sets",
    "session_hold_title" to "Hold",
    "session_hold_sub" to "Seconds per set",
    "session_reps_title" to "Reps",
    "session_reps_sub" to "Target per set",
    "session_weight_title" to "Weight",
    "session_weight_sub" to "Kilograms",
    "session_rest_title" to "Rest",
    "session_rest_sub" to "Between sets (sec)",
    "session_cancel" to "Cancel",
    "session_save" to "Save",
    "session_workout_fallback" to "Workout",
    "session_week_day" to "Week %1\$d · Day %2\$d",
    "session_best_badge" to "Best",
    "session_phase_warmup" to "Warm-up",
    "session_phase_main" to "Main workout",
    "session_phase_cooldown" to "Cool-down",
    "session_phase_other" to "Other",
    "session_bridge_not_installed" to "Session bridge not installed.",
    "session_workout_not_found" to "Workout not found.",
    "session_data_not_installed" to "Workout data layer is not installed.",
    "session_no_enrollment" to "No active program enrollment.",
    "session_workout_not_in_plan" to "Workout not found in your plan.",
)
