/**
 * Scenario tests for Progression Engine V2
 *
 * These tests verify the scientific progression logic for each archetype
 * using deterministic mock data.
 */

import {
  getArchetypeDefaults,
  buildDefaultProfile,
  ARCHETYPE_DEFAULTS,
} from '../archetype-defaults';
import type { AxisConfig, QualityGate, PromotionPolicy, RegressionPolicy } from '../archetype-defaults';

// ── Unit: archetype-defaults ──

describe('Archetype Defaults', () => {
  it('should have exactly 5 archetypes', () => {
    expect(Object.keys(ARCHETYPE_DEFAULTS)).toHaveLength(5);
  });

  it('should return correct defaults for weighted_strength', () => {
    const ws = getArchetypeDefaults('weighted_strength');
    expect(ws).not.toBeNull();
    expect(ws!.allowedAxes).toEqual(['reps', 'load', 'sets']);
    expect(ws!.priorityOrder).toEqual(['reps', 'load', 'sets']);
    expect(ws!.repAxis!.default).toBe(8);
    expect(ws!.repAxis!.cap).toBe(12);
    expect(ws!.loadAxis!.step).toBe(2.5);
    expect(ws!.qualityGate.minFormScore).toBe(70);
    expect(ws!.promotionPolicy.requiredStreakSessions).toBe(2);
    expect(ws!.regressionPolicy.maxFormScore).toBe(55);
  });

  it('should return correct defaults for bodyweight_dynamic', () => {
    const bd = getArchetypeDefaults('bodyweight_dynamic');
    expect(bd).not.toBeNull();
    expect(bd!.allowedAxes).toContain('difficulty');
    expect(bd!.difficultyLadder).toBeDefined();
    expect(bd!.loadAxis).toBeUndefined();
    expect(bd!.qualityGate.minFormScore).toBe(75);
  });

  it('should return correct defaults for isometric_hold', () => {
    const ih = getArchetypeDefaults('isometric_hold');
    expect(ih).not.toBeNull();
    expect(ih!.allowedAxes).toEqual(['duration', 'difficulty']);
    expect(ih!.durationAxis!.default).toBe(15);
    expect(ih!.durationAxis!.cap).toBe(45);
    expect(ih!.repAxis).toBeUndefined();
  });

  it('should return correct defaults for mobility_rom', () => {
    const mr = getArchetypeDefaults('mobility_rom');
    expect(mr).not.toBeNull();
    expect(mr!.qualityGate.minROM).toBe(70);
    expect(mr!.promotionPolicy.requiredStreakSessions).toBe(3);
  });

  it('should return correct defaults for motor_control', () => {
    const mc = getArchetypeDefaults('motor_control');
    expect(mc).not.toBeNull();
    expect(mc!.qualityGate.minFormScore).toBe(80);
    expect(mc!.qualityGate.minStability).toBe(70);
    expect(mc!.repAxis!.cap).toBe(12);
  });

  it('should return null for unknown archetype', () => {
    expect(getArchetypeDefaults('nonexistent')).toBeNull();
  });

  it('should build a complete profile from archetype', () => {
    const profile = buildDefaultProfile('weighted_strength');
    expect(profile).not.toBeNull();
    expect(profile!.archetype).toBe('weighted_strength');
    expect(profile!.allowedAxes).toEqual(['reps', 'load', 'sets']);
    expect(profile!.isAutoGenerated).toBe(true);
    expect(profile!.qualityGate.minFormScore).toBe(70);
  });

  it('should return null for unknown archetype profile', () => {
    expect(buildDefaultProfile('nonexistent')).toBeNull();
  });
});

// ── Unit: eligibility evaluation ──

function evaluateEligibility(
  avgFormScore: number | null,
  completionRate: number | null,
  qualityGate: QualityGate,
  regressionPolicy: RegressionPolicy,
  extras?: { avgROM?: number | null; avgStability?: number | null },
): 'promotion' | 'regression' | 'hold' {
  if (avgFormScore === null) return 'hold';
  if (avgFormScore < regressionPolicy.maxFormScore) return 'regression';

  let eligible = true;
  if (avgFormScore < qualityGate.minFormScore) eligible = false;
  if (completionRate !== null && completionRate < qualityGate.minCompletionRate) eligible = false;
  if (qualityGate.minROM && extras?.avgROM !== null && extras?.avgROM !== undefined && extras.avgROM < qualityGate.minROM) eligible = false;
  if (qualityGate.minStability && extras?.avgStability !== null && extras?.avgStability !== undefined && extras.avgStability < qualityGate.minStability) eligible = false;

  return eligible ? 'promotion' : 'hold';
}

describe('Eligibility Evaluation', () => {
  const wsDefaults = getArchetypeDefaults('weighted_strength')!;

  it('should return promotion when all gates are met', () => {
    const result = evaluateEligibility(85, 95, wsDefaults.qualityGate, wsDefaults.regressionPolicy);
    expect(result).toBe('promotion');
  });

  it('should return hold when form score is borderline', () => {
    const result = evaluateEligibility(65, 95, wsDefaults.qualityGate, wsDefaults.regressionPolicy);
    expect(result).toBe('hold');
  });

  it('should return regression when form is poor', () => {
    const result = evaluateEligibility(40, 50, wsDefaults.qualityGate, wsDefaults.regressionPolicy);
    expect(result).toBe('regression');
  });

  it('should return hold when no metrics available', () => {
    const result = evaluateEligibility(null, null, wsDefaults.qualityGate, wsDefaults.regressionPolicy);
    expect(result).toBe('hold');
  });

  it('should return hold when completion rate is low despite good form', () => {
    const result = evaluateEligibility(80, 60, wsDefaults.qualityGate, wsDefaults.regressionPolicy);
    expect(result).toBe('hold');
  });

  describe('Mobility ROM extra gate', () => {
    const mrDefaults = getArchetypeDefaults('mobility_rom')!;

    it('should require ROM for mobility exercises', () => {
      const result = evaluateEligibility(85, 90, mrDefaults.qualityGate, mrDefaults.regressionPolicy, { avgROM: 50 });
      expect(result).toBe('hold');
    });

    it('should promote when ROM gate is met', () => {
      const result = evaluateEligibility(85, 90, mrDefaults.qualityGate, mrDefaults.regressionPolicy, { avgROM: 80 });
      expect(result).toBe('promotion');
    });
  });

  describe('Motor Control stability gate', () => {
    const mcDefaults = getArchetypeDefaults('motor_control')!;

    it('should require stability for motor control exercises', () => {
      const result = evaluateEligibility(85, 95, mcDefaults.qualityGate, mcDefaults.regressionPolicy, { avgStability: 50 });
      expect(result).toBe('hold');
    });

    it('should promote when stability is sufficient', () => {
      const result = evaluateEligibility(85, 95, mcDefaults.qualityGate, mcDefaults.regressionPolicy, { avgStability: 80 });
      expect(result).toBe('promotion');
    });
  });
});

// ── Unit: axis step calculation ──

function applyAxisStep(
  currentValue: number,
  config: AxisConfig,
  direction: 'up' | 'down',
): { newValue: number; atLimit: boolean } {
  if (direction === 'up') {
    const newValue = Math.min(currentValue + config.step, config.cap);
    return { newValue, atLimit: newValue >= config.cap };
  }
  const newValue = Math.max(currentValue - config.step, config.floor);
  return { newValue, atLimit: newValue <= config.floor };
}

describe('Axis Step Calculation', () => {
  const repConfig: AxisConfig = { default: 8, floor: 5, cap: 12, step: 1 };
  const loadConfig: AxisConfig = { default: 0, floor: 0, cap: 200, step: 2.5 };

  it('should increment reps by step', () => {
    const result = applyAxisStep(8, repConfig, 'up');
    expect(result.newValue).toBe(9);
    expect(result.atLimit).toBe(false);
  });

  it('should cap reps at max', () => {
    const result = applyAxisStep(12, repConfig, 'up');
    expect(result.newValue).toBe(12);
    expect(result.atLimit).toBe(true);
  });

  it('should decrement reps by step', () => {
    const result = applyAxisStep(8, repConfig, 'down');
    expect(result.newValue).toBe(7);
    expect(result.atLimit).toBe(false);
  });

  it('should not go below floor', () => {
    const result = applyAxisStep(5, repConfig, 'down');
    expect(result.newValue).toBe(5);
    expect(result.atLimit).toBe(true);
  });

  it('should increment load by 2.5kg', () => {
    const result = applyAxisStep(20, loadConfig, 'up');
    expect(result.newValue).toBe(22.5);
    expect(result.atLimit).toBe(false);
  });
});

// ── Scenario: weighted_strength progression journey ──

describe('Scenario: Weighted Strength full journey', () => {
  const defaults = getArchetypeDefaults('weighted_strength')!;
  const repAxis = defaults.repAxis!;
  const loadAxis = defaults.loadAxis!;

  it('Phase 1: reps should increase from 8 to 12 before load progresses', () => {
    let currentReps = repAxis.default; // 8

    for (let session = 0; session < 4; session++) {
      const result = applyAxisStep(currentReps, repAxis, 'up');
      currentReps = result.newValue;
    }

    expect(currentReps).toBe(12);
  });

  it('Phase 2: when reps hit cap, load should increase and reps reset to floor', () => {
    let currentReps = repAxis.cap; // 12
    let currentLoad = 10; // starting weight

    const repsAtLimit = applyAxisStep(currentReps, repAxis, 'up').atLimit;
    expect(repsAtLimit).toBe(true);

    const loadResult = applyAxisStep(currentLoad, loadAxis, 'up');
    currentLoad = loadResult.newValue;
    currentReps = repAxis.floor;

    expect(currentLoad).toBe(12.5);
    expect(currentReps).toBe(5);
  });

  it('regression should decrease the current axis value', () => {
    const loadResult = applyAxisStep(15, loadAxis, 'down');
    expect(loadResult.newValue).toBe(12.5);
  });
});

// ── Scenario: bodyweight_dynamic with difficulty ladder ──

describe('Scenario: Bodyweight Dynamic difficulty progression', () => {
  const defaults = getArchetypeDefaults('bodyweight_dynamic')!;
  const repAxis = defaults.repAxis!;
  const ladder = defaults.difficultyLadder!;

  it('should advance through difficulty ladder when reps are at cap', () => {
    let currentReps = repAxis.cap; // 15
    let currentDiffIdx = 0;

    const repsAtLimit = applyAxisStep(currentReps, repAxis, 'up').atLimit;
    expect(repsAtLimit).toBe(true);

    currentDiffIdx++;
    currentReps = repAxis.floor;

    expect(ladder[currentDiffIdx]).toBe('intermediate');
    expect(currentReps).toBe(4);
  });

  it('should not go beyond last difficulty level', () => {
    const lastIdx = ladder.length - 1;
    const nextIdx = lastIdx + 1;
    expect(nextIdx).toBeGreaterThan(lastIdx);
    expect(ladder[lastIdx]).toBe('advanced');
  });
});

// ── Scenario: isometric_hold duration progression ──

describe('Scenario: Isometric Hold duration progression', () => {
  const defaults = getArchetypeDefaults('isometric_hold')!;
  const durationAxis = defaults.durationAxis!;

  it('should increase hold duration by step', () => {
    let currentDuration = durationAxis.default; // 15s
    const result = applyAxisStep(currentDuration, durationAxis, 'up');
    expect(result.newValue).toBe(20); // step = 5
    expect(result.atLimit).toBe(false);
  });

  it('should cap at maximum duration', () => {
    let currentDuration = 40;
    const result = applyAxisStep(currentDuration, durationAxis, 'up');
    expect(result.newValue).toBe(45); // cap
    expect(result.atLimit).toBe(true);
  });

  it('should fall back to difficulty ladder when duration at cap', () => {
    const ladder = defaults.difficultyLadder!;
    expect(ladder).toBeDefined();
    expect(ladder.length).toBeGreaterThan(1);
  });
});

// ── Scenario: mobility_rom requires 3 sessions ──

describe('Scenario: Mobility ROM requires longer streak', () => {
  const defaults = getArchetypeDefaults('mobility_rom')!;

  it('should require 3 consecutive qualifying sessions', () => {
    expect(defaults.promotionPolicy.requiredStreakSessions).toBe(3);
  });

  it('should have ROM quality gate', () => {
    expect(defaults.qualityGate.minROM).toBe(70);
  });
});
