/**
 * Curated library exercise rows for seeding (slug + blueprint fields).
 * Tuple: slug, en, ar, categoryCode, countingMethod, movementPattern, loadCapability,
 * familyKey, familyOrder, muscles[], equipment[], tags[], opts?
 */
export type CuratedRowOpts = { sw?: boolean; bi?: boolean; minW?: number; maxW?: number; defW?: number };

export type CuratedRow = readonly [
  string,
  string,
  string,
  string,
  'up_down' | 'hold',
  string,
  string,
  string,
  number,
  readonly string[],
  readonly string[],
  readonly string[],
  CuratedRowOpts?,
];

export const CURATED_EXTENSION_ROWS: CuratedRow[] = [
  ['lib_goblet_squat', 'Goblet squat', 'سكوات جوبلت', 'legs', 'up_down', 'SQUAT', 'EXTERNAL_LOAD_OPTIONAL', 'squat_pattern_family', 35, ['quadriceps', 'glutes'], ['dumbbell', 'kettlebell', 'mat'], ['compound', 'lower_body'], { sw: true }],
  ['lib_front_squat', 'Front squat', 'سكوات أمامي', 'legs', 'up_down', 'SQUAT', 'EXTERNAL_LOAD_REQUIRED', 'squat_pattern_family', 55, ['quadriceps', 'glutes'], ['barbell', 'mat'], ['compound', 'strength'], { sw: true }],
  ['lib_split_squat', 'Split squat', 'سكوات مقسم', 'legs', 'up_down', 'LUNGE', 'EXTERNAL_LOAD_OPTIONAL', 'lunge_pattern_family', 35, ['quadriceps', 'glutes'], ['dumbbell', 'mat'], ['unilateral', 'lower_body'], { sw: true }],
  ['lib_reverse_lunge', 'Reverse lunge', 'اندفاع خلفي', 'legs', 'up_down', 'LUNGE', 'BODYWEIGHT_ONLY', 'lunge_pattern_family', 30, ['quadriceps', 'glutes'], ['bodyweight', 'mat'], ['unilateral', 'beginner_friendly']],
  ['lib_walking_lunge', 'Walking lunge', 'اندفاع مشي', 'legs', 'up_down', 'LUNGE', 'EXTERNAL_LOAD_OPTIONAL', 'lunge_pattern_family', 45, ['quadriceps', 'glutes'], ['dumbbell', 'mat'], ['functional', 'lower_body'], { sw: true }],
  ['lib_romanian_deadlift', 'Romanian deadlift', 'رفعة رومانية', 'legs', 'up_down', 'HINGE', 'EXTERNAL_LOAD_REQUIRED', 'hinge_pattern_family', 45, ['hamstrings', 'glutes'], ['barbell', 'mat'], ['compound', 'strength'], { sw: true }],
  ['lib_sumo_deadlift', 'Sumo deadlift', 'رفعة سومو', 'legs', 'up_down', 'HINGE', 'EXTERNAL_LOAD_REQUIRED', 'hinge_pattern_family', 50, ['hamstrings', 'glutes', 'quadriceps'], ['barbell', 'mat'], ['compound']],
  ['lib_hip_hinge_drill', 'Hip hinge drill', 'تمرين مفصل الورك', 'legs', 'up_down', 'HINGE', 'BODYWEIGHT_ONLY', 'hinge_pattern_family', 10, ['hamstrings', 'glutes'], ['bodyweight', 'mat'], ['beginner_friendly', 'mobility']],
  ['lib_box_squat', 'Box squat', 'سكوات صندوق', 'legs', 'up_down', 'SQUAT', 'EXTERNAL_LOAD_OPTIONAL', 'squat_pattern_family', 32, ['quadriceps', 'glutes'], ['bench', 'dumbbell', 'mat'], ['beginner_friendly'], { sw: true }],
  ['lib_tempo_squat', 'Tempo squat', 'سكوات إيقاع', 'legs', 'up_down', 'SQUAT', 'BODYWEIGHT_ONLY', 'squat_pattern_family', 28, ['quadriceps', 'glutes'], ['bodyweight', 'mat'], ['control', 'eccentric']],
  ['lib_incline_pushup', 'Incline push-up', 'ضغط ترابيسي', 'chest', 'up_down', 'PUSH_HORIZONTAL', 'BODYWEIGHT_ONLY', 'push_horizontal_family', 15, ['chest_muscle', 'triceps'], ['bodyweight', 'bench'], ['beginner_friendly']],
  ['lib_decline_pushup', 'Decline push-up', 'ضغط مائل لأسفل', 'chest', 'up_down', 'PUSH_HORIZONTAL', 'BODYWEIGHT_ONLY', 'push_horizontal_family', 42, ['chest_muscle', 'triceps'], ['bodyweight', 'bench'], ['upper_body']],
  ['lib_dumbbell_press', 'Dumbbell bench press', 'ضغط دمبل مستلقي', 'chest', 'up_down', 'PUSH_HORIZONTAL', 'EXTERNAL_LOAD_OPTIONAL', 'push_horizontal_family', 48, ['chest_muscle', 'triceps'], ['dumbbell', 'bench'], ['compound'], { sw: true }],
  ['lib_barbell_bench', 'Barbell bench press', 'ضغط بار مستلقي', 'chest', 'up_down', 'PUSH_HORIZONTAL', 'EXTERNAL_LOAD_REQUIRED', 'push_horizontal_family', 55, ['chest_muscle', 'triceps'], ['barbell', 'bench'], ['strength'], { sw: true }],
  ['lib_dumbbell_row', 'Single-arm dumbbell row', 'تجديف دمبل أحادي', 'back', 'up_down', 'PULL_HORIZONTAL', 'EXTERNAL_LOAD_OPTIONAL', 'pull_horizontal_family', 40, ['lats', 'biceps'], ['dumbbell', 'bench'], ['unilateral'], { sw: true }],
  ['lib_barbell_row', 'Bent-over barbell row', 'تجديف بار منحني', 'back', 'up_down', 'PULL_HORIZONTAL', 'EXTERNAL_LOAD_REQUIRED', 'pull_horizontal_family', 50, ['lats', 'traps'], ['barbell', 'mat'], ['compound'], { sw: true }],
  ['lib_pullup_assisted', 'Assisted pull-up', 'علوي مساعد', 'back', 'up_down', 'PULL_VERTICAL', 'BODYWEIGHT_ONLY', 'pull_vertical_family', 18, ['lats', 'biceps'], ['pull_up_bar', 'mat'], ['beginner_friendly']],
  ['lib_chinup', 'Chin-up', 'شين أب', 'back', 'up_down', 'PULL_VERTICAL', 'BODYWEIGHT_ONLY', 'pull_vertical_family', 45, ['lats', 'biceps'], ['pull_up_bar', 'mat'], ['compound']],
  ['lib_lat_pulldown', 'Lat pulldown (band)', 'سحب لاتس بحبل', 'back', 'up_down', 'PULL_VERTICAL', 'EXTERNAL_LOAD_OPTIONAL', 'pull_vertical_family', 35, ['lats', 'biceps'], ['resistance_band', 'mat'], ['home_gym']],
  ['lib_face_pull', 'Face pull (band)', 'سحب وجهي بحبل', 'shoulders', 'up_down', 'PULL_HORIZONTAL', 'EXTERNAL_LOAD_OPTIONAL', 'pull_horizontal_family', 22, ['rear_delts', 'traps'], ['resistance_band', 'mat'], ['shoulders', 'posture']],
  ['lib_arnold_press', 'Arnold press', 'ضغط أرنولد', 'shoulders', 'up_down', 'PUSH_VERTICAL', 'EXTERNAL_LOAD_OPTIONAL', 'push_vertical_family', 42, ['front_delts', 'side_delts'], ['dumbbell', 'mat'], ['shoulders'], { sw: true }],
  ['lib_pike_pushup', 'Pike push-up', 'ضغط بايك', 'shoulders', 'up_down', 'PUSH_VERTICAL', 'BODYWEIGHT_ONLY', 'push_vertical_family', 28, ['front_delts', 'triceps'], ['bodyweight', 'mat'], ['shoulders']],
  ['lib_wall_slides', 'Wall slides', 'انزلاق على الحائط', 'shoulders', 'up_down', 'MOBILITY_DRILL', 'BODYWEIGHT_ONLY', 'shoulder_mobility_family', 18, ['front_delts'], ['bodyweight', 'mat'], ['mobility', 'shoulder']],
  ['lib_kettlebell_swing', 'Kettlebell swing', 'أرجوحة كيتل بيل', 'legs', 'up_down', 'HINGE', 'EXTERNAL_LOAD_REQUIRED', 'hinge_pattern_family', 55, ['glutes', 'hamstrings'], ['kettlebell', 'mat'], ['power', 'hip_hinge'], { sw: true }],
  ['lib_box_jump', 'Box jump (low)', 'قفز صندوق منخفض', 'legs', 'up_down', 'JUMP_LAND', 'BODYWEIGHT_ONLY', 'jump_land_family', 30, ['quadriceps', 'glutes'], ['bodyweight', 'bench'], ['power', 'plyometric']],
  ['lib_skater_hop', 'Skater hop', 'قفز متزلج', 'legs', 'up_down', 'JUMP_LAND', 'BODYWEIGHT_ONLY', 'jump_land_family', 25, ['calves', 'glutes'], ['bodyweight', 'mat'], ['balance', 'power']],
  ['lib_worlds_greatest_stretch', 'World’s greatest stretch', 'أعظم تمدد', 'full_body', 'up_down', 'MOBILITY_DRILL', 'BODYWEIGHT_ONLY', 'hip_mobility_family', 20, ['quadriceps', 'glutes'], ['bodyweight', 'mat'], ['mobility', 'warmup']],
  ['lib_nordic_curl_eccentric', 'Nordic hamstring (eccentric)', 'نورديك خلفي', 'legs', 'up_down', 'HINGE', 'BODYWEIGHT_ONLY', 'hinge_pattern_family', 38, ['hamstrings', 'glutes'], ['bodyweight', 'mat'], ['corrective']],
  ['lib_hamstring_slide', 'Hamstring slide curl', 'منزلق خلفي', 'legs', 'up_down', 'HINGE', 'BODYWEIGHT_ONLY', 'hinge_pattern_family', 32, ['hamstrings', 'glutes'], ['bodyweight', 'mat'], ['corrective']],
  ['lib_copenhagen_side', 'Copenhagen side plank adduction', 'بلانك كوبنهاغن', 'legs', 'hold', 'CORE_BRACE', 'BODYWEIGHT_ONLY', 'anti_lateral_flexion_family', 26, ['obliques', 'quadriceps'], ['bodyweight', 'mat'], ['corrective']],
  ['lib_pallof_press', 'Pallof press (band)', 'ضغط بالوف', 'abs', 'up_down', 'CORE_BRACE', 'EXTERNAL_LOAD_OPTIONAL', 'anti_rotation_family', 24, ['obliques'], ['resistance_band', 'mat'], ['core']],
  ['lib_farmer_carry', 'Farmer carry', 'حمل مزارع', 'full_body', 'hold', 'CARRY', 'EXTERNAL_LOAD_OPTIONAL', 'conditioning_family', 40, ['forearms', 'traps'], ['dumbbell', 'mat'], ['conditioning'], { sw: true }],
  ['lib_waiter_walk', 'Waiter walk', 'مشي نادل', 'shoulders', 'hold', 'CARRY', 'EXTERNAL_LOAD_OPTIONAL', 'overhead_stability_family', 35, ['front_delts', 'obliques'], ['dumbbell', 'mat'], ['stability'], { sw: true }],
  ['lib_cat_camel', 'Cat-camel', 'قطّ جمل', 'back', 'up_down', 'MOBILITY_DRILL', 'BODYWEIGHT_ONLY', 'spine_mobility_family', 10, ['lower_back'], ['bodyweight', 'mat'], ['mobility', 'spine']],
  ['lib_hip_9090', '90/90 hip switch', 'تبديل ورك 90/90', 'legs', 'up_down', 'MOBILITY_DRILL', 'BODYWEIGHT_ONLY', 'hip_mobility_family', 22, ['glutes', 'quadriceps'], ['bodyweight', 'mat'], ['mobility', 'hip']],
  ['lib_single_leg_rdl', 'Single-leg RDL', 'رفعة رومانية أحادية', 'legs', 'up_down', 'HINGE', 'EXTERNAL_LOAD_OPTIONAL', 'hinge_pattern_family', 48, ['hamstrings', 'glutes'], ['dumbbell', 'mat'], ['unilateral'], { sw: true }],
  ['lib_trap_bar_deadlift', 'Trap bar deadlift', 'رفعة ميتة فخذ', 'legs', 'up_down', 'HINGE', 'EXTERNAL_LOAD_REQUIRED', 'hinge_pattern_family', 58, ['quadriceps', 'glutes'], ['barbell', 'mat'], ['compound'], { sw: true }],
  ['lib_pause_deadlift', 'Pause deadlift', 'رفعة ميتة مع توقف', 'legs', 'up_down', 'HINGE', 'EXTERNAL_LOAD_REQUIRED', 'hinge_pattern_family', 56, ['hamstrings', 'glutes'], ['barbell', 'mat'], ['strength'], { sw: true }],
  ['lib_bench_hip_thrust', 'Bench-supported hip thrust', 'دفع ورك بدعم مقعد', 'legs', 'up_down', 'HINGE', 'EXTERNAL_LOAD_OPTIONAL', 'hinge_pattern_family', 36, ['glutes', 'hamstrings'], ['dumbbell', 'bench', 'mat'], ['compound'], { sw: true }],
  ['lib_cable_rotation_anti', 'Anti-rotation press (band)', 'ضد دوران بحبل', 'abs', 'hold', 'ROTATION', 'EXTERNAL_LOAD_OPTIONAL', 'anti_rotation_family', 28, ['obliques'], ['resistance_band', 'mat'], ['core']],
  ['lib_prone_plank_row', 'Renegade row', 'تجديف متقلب', 'back', 'up_down', 'PULL_HORIZONTAL', 'EXTERNAL_LOAD_OPTIONAL', 'pull_horizontal_family', 46, ['lats', 'obliques'], ['dumbbell', 'mat'], ['compound'], { sw: true }],
  ['lib_half_kneeling_lift', 'Half-kneeling chop (light)', 'قطع نصف ركبة', 'abs', 'up_down', 'ROTATION', 'EXTERNAL_LOAD_OPTIONAL', 'rotation_power_family', 30, ['obliques'], ['dumbbell', 'mat'], ['core'], { sw: true }],
  ['lib_wall_sit_overhead_press', 'Wall sit + overhead press', 'جلوس حائط وضغط', 'full_body', 'up_down', 'PUSH_VERTICAL', 'EXTERNAL_LOAD_OPTIONAL', 'conditioning_family', 31, ['quadriceps', 'front_delts'], ['dumbbell', 'mat'], ['conditioning'], { sw: true }],
  ['lib_sled_push_walk', 'Heavy walk (sled substitute)', 'مشي ثقيل', 'legs', 'up_down', 'GAIT', 'EXTERNAL_LOAD_OPTIONAL', 'conditioning_family', 35, ['quadriceps', 'glutes'], ['dumbbell', 'mat'], ['conditioning'], { sw: true }],
  ['lib_shadow_squat', 'Air squat with tempo', 'سكوات هواء بإيقاع', 'legs', 'up_down', 'SQUAT', 'BODYWEIGHT_ONLY', 'squat_pattern_family', 16, ['quadriceps'], ['bodyweight', 'mat'], ['warmup']],
  ['lib_band_face_pull_external', 'Face pull with external rotation', 'سحب وجهي مع دوران خارجي', 'shoulders', 'up_down', 'PULL_HORIZONTAL', 'EXTERNAL_LOAD_OPTIONAL', 'pull_horizontal_family', 21, ['rear_delts', 'traps'], ['resistance_band', 'mat'], ['corrective']],
  ['lib_yoga_down_dog', 'Downward dog', 'كلب مقلوب', 'full_body', 'hold', 'MOBILITY_DRILL', 'BODYWEIGHT_ONLY', 'posterior_chain_mobility_family', 18, ['hamstrings', 'front_delts'], ['bodyweight', 'mat'], ['mobility']],
  ['lib_yoga_up_dog', 'Upward dog', 'كلب صاعد', 'back', 'hold', 'MOBILITY_DRILL', 'BODYWEIGHT_ONLY', 'spine_mobility_family', 14, ['abs_muscle', 'chest_muscle'], ['bodyweight', 'mat'], ['mobility']],
  ['lib_seated_neck_rotation', 'Seated neck rotation', 'دوران رقبة جالس', 'shoulders', 'up_down', 'MOBILITY_DRILL', 'BODYWEIGHT_ONLY', 'neck_control_family', 7, ['traps'], ['bodyweight', 'mat'], ['mobility']],
  ['lib_elbow_out_rotations', 'Elbow-out rotations', 'دوران مرفق خارجي', 'shoulders', 'up_down', 'MOBILITY_DRILL', 'BODYWEIGHT_ONLY', 'shoulder_mobility_family', 17, ['rear_delts'], ['bodyweight', 'mat'], ['mobility']],
  ['lib_squat_jump', 'Squat jump (progression)', 'قفز سكوات', 'legs', 'up_down', 'JUMP_LAND', 'BODYWEIGHT_ONLY', 'jump_land_family', 36, ['quadriceps', 'glutes'], ['bodyweight', 'mat'], ['power']],
  ['lib_lateral_bound', 'Lateral bound', 'قفز جانبي', 'legs', 'up_down', 'JUMP_LAND', 'BODYWEIGHT_ONLY', 'jump_land_family', 34, ['glutes', 'calves'], ['bodyweight', 'mat'], ['power', 'balance']],
  ['lib_one_arm_snatch_balance', 'Single-arm KB snatch to rack', 'سناتش كيتل أحادي', 'full_body', 'up_down', 'JUMP_LAND', 'EXTERNAL_LOAD_REQUIRED', 'power_family', 48, ['glutes', 'front_delts'], ['kettlebell', 'mat'], ['power', 'advanced'], { sw: true }],
  ['lib_windmill_stretch', 'Standing windmill (mobility)', 'مطحنة واقفة', 'full_body', 'up_down', 'MOBILITY_DRILL', 'BODYWEIGHT_ONLY', 'rotation_mobility_family', 17, ['obliques', 'hamstrings'], ['bodyweight', 'mat'], ['mobility']],
  ['lib_heel_taps', 'Heel taps (dead bug variant)', 'لمس كعبين', 'abs', 'up_down', 'CORE_BRACE', 'BODYWEIGHT_ONLY', 'anti_extension_family', 16, ['abs_muscle'], ['bodyweight', 'mat'], ['beginner_friendly']],
  ['lib_v_up', 'V-up', 'قمة V', 'abs', 'up_down', 'CORE_BRACE', 'BODYWEIGHT_ONLY', 'trunk_flexion_family', 28, ['abs_muscle', 'quadriceps'], ['bodyweight', 'mat'], ['advanced']],
  ['lib_bicycle_crunch', 'Bicycle crunch', 'دراجة بطن', 'abs', 'up_down', 'CORE_BRACE', 'BODYWEIGHT_ONLY', 'trunk_flexion_family', 24, ['obliques', 'abs_muscle'], ['bodyweight', 'mat'], ['conditioning']],
  ['lib_mountain_climber_slow', 'Slow mountain climber', 'متسلق جبال بطيء', 'abs', 'up_down', 'CORE_BRACE', 'BODYWEIGHT_ONLY', 'anti_extension_family', 22, ['abs_muscle', 'quadriceps'], ['bodyweight', 'mat'], ['conditioning']],
  ['lib_side_lunge', 'Side lunge', 'اندفاع جانبي', 'legs', 'up_down', 'LUNGE', 'BODYWEIGHT_ONLY', 'lunge_pattern_family', 28, ['glutes', 'quadriceps'], ['bodyweight', 'mat'], ['mobility']],
  ['lib_curtsy_lunge', 'Curtsy lunge', 'اندفاع كورتسي', 'legs', 'up_down', 'LUNGE', 'EXTERNAL_LOAD_OPTIONAL', 'lunge_pattern_family', 33, ['glutes', 'quadriceps'], ['dumbbell', 'mat'], ['unilateral'], { sw: true }],
  ['lib_quadruped_rocking', 'Quadruped rocking', 'صخ رباعي', 'legs', 'up_down', 'MOBILITY_DRILL', 'BODYWEIGHT_ONLY', 'hip_mobility_family', 11, ['quadriceps'], ['bodyweight', 'mat'], ['warmup']],
  ['lib_adductor_rockback', 'Adductor rock-back', 'صخ مقرب', 'legs', 'up_down', 'MOBILITY_DRILL', 'BODYWEIGHT_ONLY', 'hip_mobility_family', 19, ['glutes'], ['bodyweight', 'mat'], ['mobility']],
  ['lib_cossack_squat_bw', 'Cossack squat (bodyweight)', 'سكوات قوزاق وزن جسم', 'legs', 'up_down', 'SQUAT', 'BODYWEIGHT_ONLY', 'squat_pattern_family', 26, ['glutes', 'quadriceps'], ['bodyweight', 'mat'], ['mobility']],
  ['lib_elevated_pigeon', 'Elevated pigeon', 'حمامة مرتفعة', 'legs', 'hold', 'MOBILITY_DRILL', 'BODYWEIGHT_ONLY', 'hip_mobility_family', 29, ['glutes'], ['bodyweight', 'bench'], ['mobility']],
  ['lib_scapular_depression', 'Scapular depression hang', 'تعليق خفض لوح', 'back', 'hold', 'PULL_VERTICAL', 'BODYWEIGHT_ONLY', 'pull_vertical_family', 12, ['lats', 'traps'], ['pull_up_bar', 'mat'], ['mobility']],
  ['lib_tibialis_raise', 'Tibialis raise', 'رفع قصبة', 'legs', 'up_down', 'GAIT', 'BODYWEIGHT_ONLY', 'ankle_plantarflexion_family', 17, ['calves'], ['bodyweight', 'mat'], ['corrective']],
  ['lib_jefferson_curl_light', 'Jefferson curl (light)', 'جيفرسون خفيف', 'back', 'up_down', 'HINGE', 'EXTERNAL_LOAD_OPTIONAL', 'hinge_pattern_family', 25, ['hamstrings', 'lower_back'], ['dumbbell', 'mat'], ['mobility'], { sw: true }],
  ['lib_sleeper_stretch', 'Sleeper stretch', 'تمديد نائم كتف', 'shoulders', 'hold', 'MOBILITY_DRILL', 'BODYWEIGHT_ONLY', 'shoulder_mobility_family', 24, ['rear_delts'], ['bodyweight', 'mat'], ['mobility']],
  ['lib_cross_body_stretch', 'Cross-body shoulder stretch', 'تمديد كتف عبر الجسم', 'shoulders', 'hold', 'MOBILITY_DRILL', 'BODYWEIGHT_ONLY', 'shoulder_mobility_family', 23, ['rear_delts'], ['bodyweight', 'mat'], ['mobility']],
  ['lib_pec_doorway_stretch', 'Doorway pec stretch', 'تمديد صدري بباب', 'chest', 'hold', 'MOBILITY_DRILL', 'BODYWEIGHT_ONLY', 'shoulder_mobility_family', 21, ['chest_muscle'], ['bodyweight', 'mat'], ['mobility']],
  ['lib_wall_angels', 'Wall angels', 'ملائكة الحائط', 'shoulders', 'up_down', 'MOBILITY_DRILL', 'BODYWEIGHT_ONLY', 'shoulder_mobility_family', 16, ['front_delts', 'traps'], ['bodyweight', 'mat'], ['posture']],
  ['lib_shoulder_dislocates_band', 'Shoulder dislocates (band)', 'تدوير كتف بحبل', 'shoulders', 'up_down', 'MOBILITY_DRILL', 'EXTERNAL_LOAD_OPTIONAL', 'shoulder_mobility_family', 20, ['front_delts', 'chest_muscle'], ['resistance_band', 'mat'], ['warmup']],
  ['lib_neck_retraction', 'Chin tuck / cervical retraction', 'سحب ذقن', 'shoulders', 'up_down', 'MOBILITY_DRILL', 'BODYWEIGHT_ONLY', 'neck_control_family', 5, ['traps'], ['bodyweight', 'mat'], ['corrective']],
  ['lib_jumping_jack_low_impact', 'Low-impact jack', 'قفز جانبي منخفض', 'full_body', 'up_down', 'GAIT', 'BODYWEIGHT_ONLY', 'conditioning_family', 12, ['calves', 'front_delts'], ['bodyweight', 'mat'], ['conditioning', 'beginner_friendly']],
  ['lib_overhead_squat_pvc', 'Overhead squat (PVC)', 'سكوات علوي PVC', 'legs', 'up_down', 'SQUAT', 'EXTERNAL_LOAD_OPTIONAL', 'squat_pattern_family', 33, ['quadriceps', 'front_delts'], ['resistance_band', 'mat'], ['mobility', 'technique']],
  ['lib_z_press', 'Z-press', 'ضغط Z', 'shoulders', 'up_down', 'PUSH_VERTICAL', 'EXTERNAL_LOAD_OPTIONAL', 'push_vertical_family', 46, ['front_delts', 'triceps'], ['dumbbell', 'mat'], ['strength'], { sw: true }],
  ['lib_push_press', 'Push press', 'ضغط دفع', 'shoulders', 'up_down', 'PUSH_VERTICAL', 'EXTERNAL_LOAD_REQUIRED', 'push_vertical_family', 52, ['front_delts', 'triceps'], ['barbell', 'mat'], ['power'], { sw: true }],
  ['lib_bear_crawl', 'Bear crawl', 'زحف الدب', 'full_body', 'up_down', 'GAIT', 'BODYWEIGHT_ONLY', 'gait_family', 22, ['front_delts', 'quadriceps'], ['bodyweight', 'mat'], ['conditioning']],
  ['lib_turkish_getup_half', 'Half Turkish get-up', 'نصف قومة تركية', 'full_body', 'up_down', 'OTHER', 'EXTERNAL_LOAD_OPTIONAL', 'getup_family', 40, ['front_delts', 'glutes', 'abs_muscle'], ['kettlebell', 'mat'], ['stability', 'advanced'], { sw: true }],
  ['lib_wrist_flex_ext', 'Wrist flexion/extension', 'ثني/مد رسغ', 'arms', 'up_down', 'MOBILITY_DRILL', 'BODYWEIGHT_ONLY', 'wrist_mobility_family', 8, ['forearms'], ['bodyweight', 'mat'], ['mobility']],
  ['lib_ankle_inversion_eversion', 'Ankle inversion/eversion', 'قلب كاحل', 'legs', 'up_down', 'MOBILITY_DRILL', 'BODYWEIGHT_ONLY', 'ankle_mobility_family', 13, ['calves'], ['bodyweight', 'mat'], ['mobility']],
  ['lib_hollow_body_hold', 'Hollow body hold', 'جسم مجوف', 'abs', 'hold', 'CORE_BRACE', 'BODYWEIGHT_ONLY', 'anti_extension_family', 21, ['abs_muscle'], ['bodyweight', 'mat'], ['core']],
  ['lib_dead_bug', 'Dead bug', 'حشرة ميتة', 'abs', 'up_down', 'CORE_BRACE', 'BODYWEIGHT_ONLY', 'anti_extension_family', 14, ['abs_muscle'], ['bodyweight', 'mat'], ['beginner_friendly']],
  ['lib_bird_dog', 'Bird dog', 'كلب طائر', 'back', 'up_down', 'CORE_BRACE', 'BODYWEIGHT_ONLY', 'anti_extension_family', 18, ['lower_back', 'glutes'], ['bodyweight', 'mat'], ['stability']],
  ['lib_glute_bridge_march', 'Glute bridge march', 'سير جسر الألوية', 'legs', 'up_down', 'HINGE', 'BODYWEIGHT_ONLY', 'hinge_pattern_family', 24, ['glutes', 'hamstrings'], ['bodyweight', 'mat'], ['activation']],
  ['lib_clamshell', 'Clamshell (band)', 'صدفة', 'legs', 'up_down', 'MOBILITY_DRILL', 'EXTERNAL_LOAD_OPTIONAL', 'hip_mobility_family', 15, ['glutes'], ['resistance_band', 'mat'], ['corrective']],
  ['lib_terminal_knee_extension', 'Terminal knee extension (band)', 'تمديد ركبة طرفي', 'legs', 'up_down', 'MOBILITY_DRILL', 'EXTERNAL_LOAD_OPTIONAL', 'hip_mobility_family', 12, ['quadriceps'], ['resistance_band', 'mat'], ['therapeutic']],
  ['lib_wall_posture_reset', 'Wall posture reset', 'إعادة وضعية حائط', 'full_body', 'hold', 'MOBILITY_DRILL', 'BODYWEIGHT_ONLY', 'posture_screen_family', 8, ['traps', 'abs_muscle'], ['bodyweight', 'mat'], ['corrective']],
  ['lib_seated_good_morning', 'Seated good morning (light)', 'صباح خير جالس', 'back', 'up_down', 'HINGE', 'EXTERNAL_LOAD_OPTIONAL', 'hinge_pattern_family', 22, ['hamstrings', 'lower_back'], ['dumbbell', 'mat'], ['mobility'], { sw: true }],
  ['lib_goblet_cossack', 'Goblet Cossack squat', 'سكوات قوزاق جوبلت', 'legs', 'up_down', 'SQUAT', 'EXTERNAL_LOAD_OPTIONAL', 'squat_pattern_family', 38, ['glutes', 'quadriceps'], ['dumbbell', 'mat'], ['mobility'], { sw: true }],
  ['lib_landmine_press', 'Half-kneeling landmine press', 'ضغط لاندمين', 'shoulders', 'up_down', 'PUSH_VERTICAL', 'EXTERNAL_LOAD_OPTIONAL', 'push_vertical_family', 44, ['front_delts', 'chest_muscle'], ['barbell', 'mat'], ['strength'], { sw: true }],
  ['lib_db_thruster', 'Dumbbell thruster', 'ثرستر دمبل', 'full_body', 'up_down', 'SQUAT', 'EXTERNAL_LOAD_OPTIONAL', 'conditioning_family', 52, ['quadriceps', 'front_delts'], ['dumbbell', 'mat'], ['conditioning'], { sw: true }],
  ['lib_roman_chair_back_ext', 'Back extension (bodyweight)', 'تمديد ظهر', 'back', 'up_down', 'CORE_BRACE', 'BODYWEIGHT_ONLY', 'back_extension_family', 22, ['lower_back', 'glutes'], ['bodyweight', 'bench'], ['accessory']],
  ['lib_calf_raise_seated', 'Seated calf raise', 'سمانة جالس', 'legs', 'up_down', 'GAIT', 'EXTERNAL_LOAD_OPTIONAL', 'ankle_plantarflexion_family', 26, ['calves'], ['dumbbell', 'mat'], ['accessory'], { sw: true }],
  ['lib_hammer_curl', 'Hammer curl', 'طرق مطرقة', 'arms', 'up_down', 'PULL_HORIZONTAL', 'EXTERNAL_LOAD_OPTIONAL', 'elbow_flexion_family', 24, ['biceps', 'forearms'], ['dumbbell', 'mat'], ['arms'], { sw: true }],
  ['lib_tricep_pushdown_band', 'Tricep pushdown (band)', 'دفع ثلاثي بحبل', 'arms', 'up_down', 'PUSH_HORIZONTAL', 'EXTERNAL_LOAD_OPTIONAL', 'push_horizontal_family', 26, ['triceps'], ['resistance_band', 'mat'], ['arms']],
  ['lib_spiderman_lunge', 'Spiderman lunge with reach', 'اندفاع سبايدرمان', 'legs', 'up_down', 'LUNGE', 'BODYWEIGHT_ONLY', 'hip_mobility_family', 27, ['quadriceps', 'glutes'], ['bodyweight', 'mat'], ['mobility']],
  ['lib_inchworm', 'Inchworm', 'دودة بوصة', 'full_body', 'up_down', 'MOBILITY_DRILL', 'BODYWEIGHT_ONLY', 'posterior_chain_mobility_family', 19, ['hamstrings', 'abs_muscle'], ['bodyweight', 'mat'], ['warmup']],
  ['lib_side_plank_hip_abduction', 'Side plank hip abduction', 'بلانك جانبي مع خطف', 'abs', 'hold', 'CORE_BRACE', 'BODYWEIGHT_ONLY', 'anti_lateral_flexion_family', 24, ['obliques', 'glutes'], ['bodyweight', 'mat'], ['core']],
  ['lib_reverse_crunch', 'Reverse crunch', 'كرانش عكسي', 'abs', 'up_down', 'CORE_BRACE', 'BODYWEIGHT_ONLY', 'trunk_flexion_family', 22, ['abs_muscle'], ['bodyweight', 'mat'], ['core']],
  ['lib_standing_calf_mobility', 'Standing calf mobility', 'تحريك سمانة واقف', 'legs', 'up_down', 'MOBILITY_DRILL', 'BODYWEIGHT_ONLY', 'ankle_mobility_family', 11, ['calves'], ['bodyweight', 'mat'], ['mobility']],
  ['lib_forearm_wall_slide', 'Forearm wall slide', 'انزلاق ساعد على حائط', 'shoulders', 'up_down', 'MOBILITY_DRILL', 'BODYWEIGHT_ONLY', 'shoulder_mobility_family', 19, ['rear_delts', 'traps'], ['bodyweight', 'mat'], ['mobility']],
  ['lib_prone_y_raise', 'Prone Y raise', 'رفع Y', 'back', 'up_down', 'PULL_VERTICAL', 'BODYWEIGHT_ONLY', 'pull_vertical_family', 20, ['rear_delts', 'traps'], ['bodyweight', 'mat'], ['corrective']],
  ['lib_prone_t_raise', 'Prone T raise', 'رفع T', 'back', 'up_down', 'PULL_HORIZONTAL', 'BODYWEIGHT_ONLY', 'pull_horizontal_family', 23, ['rear_delts', 'traps'], ['bodyweight', 'mat'], ['corrective']],
  ['lib_standing_hip_circle', 'Standing hip circles', 'دوائر ورك واقف', 'legs', 'up_down', 'MOBILITY_DRILL', 'BODYWEIGHT_ONLY', 'hip_mobility_family', 14, ['glutes'], ['bodyweight', 'mat'], ['warmup']],
  ['lib_deep_squat_hold', 'Deep squat hold', 'جلوس عميق ثابت', 'legs', 'hold', 'SQUAT', 'BODYWEIGHT_ONLY', 'squat_pattern_family', 18, ['quadriceps', 'glutes'], ['bodyweight', 'mat'], ['mobility']],
  ['lib_split_stance_rotation', 'Split stance rotation', 'دوران وضع مقسم', 'abs', 'up_down', 'ROTATION', 'BODYWEIGHT_ONLY', 'rotation_mobility_family', 23, ['obliques'], ['bodyweight', 'mat'], ['mobility']],
  ['lib_isometric_split_squat', 'Isometric split squat', 'اندفاع مقسم ثابت', 'legs', 'hold', 'LUNGE', 'BODYWEIGHT_ONLY', 'lunge_pattern_family', 32, ['quadriceps', 'glutes'], ['bodyweight', 'mat'], ['strength']],
  ['lib_tempo_pushup', 'Tempo push-up', 'ضغط إيقاع', 'chest', 'up_down', 'PUSH_HORIZONTAL', 'BODYWEIGHT_ONLY', 'push_horizontal_family', 20, ['chest_muscle', 'triceps'], ['bodyweight', 'mat'], ['control']],
  ['lib_band_pull_apart', 'Band pull-apart', 'سحب أفقي بحبل', 'back', 'up_down', 'PULL_HORIZONTAL', 'EXTERNAL_LOAD_OPTIONAL', 'pull_horizontal_family', 19, ['rear_delts'], ['resistance_band', 'mat'], ['warmup']],
  ['lib_kb_goblet_clean', 'Kettlebell goblet clean', 'تنظيف جوبلت كيتل', 'full_body', 'up_down', 'HINGE', 'EXTERNAL_LOAD_REQUIRED', 'hinge_pattern_family', 52, ['glutes', 'front_delts'], ['kettlebell', 'mat'], ['power'], { sw: true }],
  ['lib_staggered_rdl', 'Staggered stance RDL', 'رفعة رومانية متدرجة', 'legs', 'up_down', 'HINGE', 'EXTERNAL_LOAD_OPTIONAL', 'hinge_pattern_family', 44, ['hamstrings', 'glutes'], ['dumbbell', 'mat'], ['unilateral'], { sw: true }],
  ['lib_ez_bar_curl', 'EZ-bar curl', 'طحن EZ', 'arms', 'up_down', 'PULL_HORIZONTAL', 'EXTERNAL_LOAD_OPTIONAL', 'elbow_flexion_family', 26, ['biceps'], ['barbell', 'mat'], ['arms'], { sw: true }],
  ['lib_overhead_tricep_ext', 'Overhead tricep extension', 'تمديد ثلاثي علوي', 'arms', 'up_down', 'PUSH_VERTICAL', 'EXTERNAL_LOAD_OPTIONAL', 'push_vertical_family', 30, ['triceps'], ['dumbbell', 'mat'], ['arms'], { sw: true }],
  ['lib_seated_row_band', 'Seated row (band)', 'تجديف جالس بحبل', 'back', 'up_down', 'PULL_HORIZONTAL', 'EXTERNAL_LOAD_OPTIONAL', 'pull_horizontal_family', 28, ['lats', 'biceps'], ['resistance_band', 'mat'], ['home_gym']],
  ['lib_glute_activation_bridge', 'Glute activation bridge', 'جسر تفعيل ألوية', 'legs', 'up_down', 'HINGE', 'BODYWEIGHT_ONLY', 'hinge_pattern_family', 21, ['glutes'], ['bodyweight', 'mat'], ['activation']],
  ['lib_mini_band_walk', 'Mini-band lateral walk', 'مشي جانبي بحلقة', 'legs', 'up_down', 'GAIT', 'EXTERNAL_LOAD_OPTIONAL', 'hip_mobility_family', 16, ['glutes'], ['resistance_band', 'mat'], ['activation']],
  ['lib_scap_pushup', 'Scapular push-up', 'ضغط لوح كتف', 'chest', 'up_down', 'PUSH_HORIZONTAL', 'BODYWEIGHT_ONLY', 'push_horizontal_family', 12, ['chest_muscle', 'traps'], ['bodyweight', 'mat'], ['warmup']],
  ['lib_copenhagen_short', 'Copenhagen short lever', 'كوبنهاغن رافعة قصيرة', 'legs', 'hold', 'CORE_BRACE', 'BODYWEIGHT_ONLY', 'anti_lateral_flexion_family', 22, ['obliques', 'quadriceps'], ['bodyweight', 'mat'], ['therapeutic']],
  ['lib_heel_elevated_squat', 'Heel-elevated squat', 'سكوات كعب مرتفع', 'legs', 'up_down', 'SQUAT', 'BODYWEIGHT_ONLY', 'squat_pattern_family', 24, ['quadriceps', 'glutes'], ['bodyweight', 'mat'], ['mobility']],
  ['lib_prone_hip_internal_rotation', 'Prone hip IR mobilization', 'دوران داخلي للورك', 'legs', 'up_down', 'MOBILITY_DRILL', 'BODYWEIGHT_ONLY', 'hip_mobility_family', 13, ['glutes'], ['bodyweight', 'mat'], ['mobility']],
  ['lib_supine_shoulder_flexion', 'Supine shoulder flexion slide', 'انزلاق كتف', 'shoulders', 'up_down', 'MOBILITY_DRILL', 'BODYWEIGHT_ONLY', 'shoulder_mobility_family', 15, ['front_delts'], ['bodyweight', 'mat'], ['mobility']],
  ['lib_thoracic_open_book', 'Open book thoracic rotation', 'كتاب مفتوح صدري', 'back', 'up_down', 'ROTATION', 'BODYWEIGHT_ONLY', 'spine_mobility_family', 16, ['obliques'], ['bodyweight', 'mat'], ['mobility']],
  ['lib_ankle_df_knee_wall', 'Ankle dorsiflexion knee-to-wall', 'ثني ظهر الكاحل', 'legs', 'up_down', 'MOBILITY_DRILL', 'BODYWEIGHT_ONLY', 'ankle_mobility_family', 10, ['calves', 'quadriceps'], ['bodyweight', 'mat'], ['mobility']],
];
