/**
 * Canonical family ladders (easiest → harder) for seed validators.
 * Comments in English per project convention.
 */

export const FAMILY_LADDERS: Record<string, readonly string[]> = {
  squat_pattern_family: [
    'lib_shadow_squat',
    'assessment_overhead_squat',
    'wall_sit',
    'lib_tempo_squat',
    'lib_box_squat',
    'squat',
    'lib_goblet_squat',
    'lib_front_squat',
    'lib_wall_sit_overhead_press',
  ],
  lunge_pattern_family: [
    'assessment_lunge',
    'lib_reverse_lunge',
    'lib_side_lunge',
    'lunge',
    'lib_split_squat',
    'lib_walking_lunge',
    'lib_curtsy_lunge',
  ],
  hinge_pattern_family: [
    'lib_hip_hinge_drill',
    'glute_bridge',
    'lib_romanian_deadlift',
    'deadlift',
    'lib_sumo_deadlift',
    'lib_trap_bar_deadlift',
    'lib_pause_deadlift',
  ],
  push_horizontal_family: [
    'lib_incline_pushup',
    'pushup',
    'lib_decline_pushup',
    'lib_dumbbell_press',
    'lib_barbell_bench',
    'tricep_dips',
  ],
  push_vertical_family: [
    'lib_pike_pushup',
    'shoulder_press',
    'lateral_raises',
    'lib_arnold_press',
    'lib_z_press',
    'lib_push_press',
  ],
  pull_horizontal_family: [
    'lib_face_pull',
    'bicep_curl',
    'lib_dumbbell_row',
    'lib_barbell_row',
    'lib_prone_plank_row',
    'lib_band_face_pull_external',
  ],
  pull_vertical_family: [
    'lib_lat_pulldown',
    'lib_pullup_assisted',
    'lib_chinup',
    'lib_scapular_depression',
  ],
  anti_extension_family: [
    'forearm_rest',
    'lib_heel_taps',
    'plank',
    'lib_mountain_climber_slow',
    'arm_hold',
  ],
  trunk_flexion_family: ['crunch', 'lib_bicycle_crunch', 'lib_v_up'],
  anti_lateral_flexion_family: ['side_plank'],
  back_extension_family: ['superman'],
  anti_rotation_family: ['lib_cable_rotation_anti'],
  ankle_plantarflexion_family: ['calf_raises', 'lib_tibialis_raise', 'lib_ankle_inversion_eversion'],
  shoulder_mobility_family: [
    'assessment_shoulder_mobility',
    'lib_wall_slides',
    'lib_wall_angels',
    'lib_elbow_out_rotations',
    'lib_cross_body_stretch',
    'lib_sleeper_stretch',
    'lib_shoulder_dislocates_band',
  ],
  posterior_chain_mobility_family: [
    'assessment_forward_fold',
    'lib_cat_camel',
    'lib_yoga_down_dog',
    'lib_jefferson_curl_light',
  ],
  spine_mobility_family: ['lib_cat_camel', 'lib_yoga_up_dog', 'lib_windmill_stretch'],
  single_leg_balance_family: ['assessment_single_leg_balance', 'lib_skater_hop', 'lib_single_leg_rdl'],
  hip_mobility_family: [
    'lib_quadruped_rocking',
    'lib_hip_9090',
    'lib_adductor_rockback',
    'lib_cossack_squat_bw',
    'lib_elevated_pigeon',
  ],
  neck_control_family: ['lib_neck_retraction', 'lib_seated_neck_rotation'],
  wrist_mobility_family: ['lib_wrist_flex_ext'],
  gait_family: ['lib_bear_crawl', 'lib_jumping_jack_low_impact'],
  conditioning_family: ['lib_jumping_jack_low_impact', 'lib_sled_push_walk'],
  rotation_mobility_family: ['lib_worlds_greatest_stretch', 'lib_windmill_stretch'],
  rotation_power_family: ['lib_half_kneeling_lift'],
  elbow_flexion_family: ['bicep_curl_left', 'bicep_curl_right', 'bicep_curl'],
  overhead_stability_family: ['arm_hold'],
  posture_screen_family: ['desk_test'],
  getup_family: ['lib_turkish_getup_half'],
  jump_land_family: ['lib_box_jump', 'lib_squat_jump', 'lib_lateral_bound'],
  power_family: ['lib_box_jump', 'lib_kettlebell_swing', 'lib_one_arm_snatch_balance'],
};
