import type { PrismaClient, ExerciseArchetype } from '@prisma/client';
import { ARCHETYPE_DEFAULTS, buildDefaultProfile } from '../../src/modules/progression/archetype-defaults';

/**
 * Seed legacy progression rules (now deactivated).
 */
export async function seedProgressionRules(prisma: PrismaClient) {
  console.log('📈 Seeding progression rules (legacy)...');

  const rules = [
    {
      name: 'Weight Increase (Positive)',
      scope: 'global',
      trigger: 'session_completed',
      conditions: [
        { metric: 'avgFormScore', operator: '>=', value: 75, window: 'last_2_sessions' },
        { metric: 'completionRate', operator: '>=', value: 90, window: 'last_2_sessions' },
      ],
      action: {
        type: 'increase_weight',
        amount: 2.5,
        notification: {
          ar: 'أداء ممتاز! تم زيادة الوزن 2.5 كجم للجلسة القادمة.',
          en: 'Great performance! Weight increased by 2.5kg for next session.',
        },
      },
      priority: 10,
      isActive: false,
    },
    {
      name: 'Rep Increase (Weekly)',
      scope: 'global',
      trigger: 'session_completed',
      conditions: [
        { metric: 'avgFormScore', operator: '>=', value: 80, window: 'last_week' },
        { metric: 'avgROM', operator: '>=', value: 85, window: 'last_week' },
      ],
      action: {
        type: 'increase_reps',
        amount: 2,
        notification: {
          ar: 'تقدم رائع! تم زيادة التكرارات بمقدار 2.',
          en: 'Amazing progress! Reps increased by 2.',
        },
      },
      priority: 5,
      isActive: false,
    },
    {
      name: 'Deload Safety',
      scope: 'global',
      trigger: 'session_completed',
      conditions: [
        { metric: 'avgFormScore', operator: '<', value: 60, window: 'last_2_sessions' },
      ],
      action: {
        type: 'decrease_weight',
        amount: 2.5,
        notification: {
          ar: 'تم تخفيف الوزن 2.5 كجم للحفاظ على سلامتك. ركز على الأداء الصحيح.',
          en: 'Weight reduced by 2.5kg for your safety. Focus on proper form.',
        },
      },
      priority: 20,
      isActive: false,
    },
  ];

  for (const rule of rules) {
    const existing = await prisma.progressionRule.findFirst({
      where: { name: rule.name },
    });
    if (!existing) {
      await prisma.progressionRule.create({ data: rule });
    }
  }

  await prisma.progressionRule.updateMany({
    where: { isActive: true },
    data: { isActive: false },
  });

  console.log(`  ✅ Seeded ${rules.length} progression rules (deactivated)`);
}

/**
 * Classify exercises into archetypes and generate progression profiles.
 */
export async function assignArchetypesAndGenerateProfiles(prisma: PrismaClient) {
  console.log('📈 Assigning archetypes and generating progression profiles...');

  const exercises = await prisma.exercise.findMany({
    where: { status: 'published', deletedAt: null, archetype: null },
    include: { countingMethod: { select: { code: true } } },
  });

  let assigned = 0;
  let profilesCreated = 0;

  for (const exercise of exercises) {
    let archetype: ExerciseArchetype;
    const countingCode = exercise.countingMethod?.code || '';

    if (exercise.supportsWeight) {
      archetype = 'weighted_strength';
    } else if (countingCode.includes('hold') || countingCode.includes('duration') || countingCode.includes('time')) {
      archetype = 'isometric_hold';
    } else if (countingCode.includes('rom') || countingCode.includes('mobility') || countingCode.includes('stretch')) {
      archetype = 'mobility_rom';
    } else {
      archetype = 'bodyweight_dynamic';
    }

    await prisma.exercise.update({
      where: { id: exercise.id },
      data: { archetype },
    });
    assigned++;

    const defaults = buildDefaultProfile(archetype);
    if (defaults) {
      const existing = await prisma.exerciseProgressionProfile.findUnique({
        where: { exerciseId: exercise.id },
      });

      if (!existing) {
        const toJson = (v: unknown) => v != null ? JSON.parse(JSON.stringify(v)) : undefined;
        await prisma.exerciseProgressionProfile.create({
          data: {
            exerciseId: exercise.id,
            archetype,
            allowedAxes: defaults.allowedAxes,
            priorityOrder: defaults.priorityOrder,
            repAxis: toJson(defaults.repAxis),
            loadAxis: toJson(defaults.loadAxis),
            durationAxis: toJson(defaults.durationAxis),
            setAxis: toJson(defaults.setAxis),
            difficultyLadder: defaults.difficultyLadder ?? undefined,
            qualityGate: toJson(defaults.qualityGate),
            promotionPolicy: toJson(defaults.promotionPolicy),
            regressionPolicy: toJson(defaults.regressionPolicy),
            isAutoGenerated: true,
          },
        });
        profilesCreated++;
      }
    }
  }

  console.log(`  ✅ Assigned archetypes to ${assigned} exercises`);
  console.log(`  ✅ Created ${profilesCreated} progression profiles`);
}

/**
 * Backfill progression state for users with active programs.
 */
export async function backfillProgressionState(prisma: PrismaClient) {
  console.log('📈 Backfilling progression state for active programs...');

  const activePrograms = await prisma.userProgram.findMany({
    where: { isActive: true, programId: { not: null } },
    include: {
      program: {
        include: {
          weeks: {
            include: {
              days: {
                include: {
                  sessions: {
                    include: {
                      items: {
                        where: { exerciseId: { not: null } },
                        select: {
                          exerciseId: true,
                          targetReps: true,
                          weightKg: true,
                          targetDuration: true,
                          sets: true,
                        },
                      },
                    },
                  },
                },
              },
            },
          },
        },
      },
    },
  });

  let created = 0;

  for (const up of activePrograms) {
    const exerciseItems = new Map<string, any>();

    for (const week of up.program?.weeks ?? []) {
      for (const day of week.days) {
        for (const session of day.sessions) {
          for (const item of session.items) {
            if (item.exerciseId && !exerciseItems.has(item.exerciseId)) {
              exerciseItems.set(item.exerciseId, item);
            }
          }
        }
      }
    }

    for (const [exerciseId, item] of exerciseItems) {
      const profile = await prisma.exerciseProgressionProfile.findUnique({
        where: { exerciseId },
      });
      if (!profile) continue;

      const existing = await prisma.userProgramExerciseProgressionState.findUnique({
        where: { userProgramId_exerciseId: { userProgramId: up.id, exerciseId } },
      });
      if (existing) continue;

      const priorityOrder = profile.priorityOrder as string[];
      const ladder = profile.difficultyLadder as string[] | null;
      const initialDifficultyCode = ladder?.[0] ?? null;

      await prisma.userProgramExerciseProgressionState.create({
        data: {
          userProgramId: up.id,
          exerciseId,
          currentAxis: priorityOrder[0] || 'reps',
          currentWeightKg: item.weightKg ?? null,
          currentTargetReps: item.targetReps ?? null,
          currentTargetDuration: item.targetDuration ?? null,
          currentTargetSets: item.sets ?? null,
          currentDifficultyCode: initialDifficultyCode,
          successStreak: 0,
          regressionStreak: 0,
        },
      });
      created++;
    }
  }

  console.log(`  ✅ Created ${created} progression states for active programs`);
}
