import type { PrismaClient, ExerciseArchetype } from '@prisma/client';
import { ARCHETYPE_DEFAULTS } from '../../src/modules/progression/archetype-defaults';

/**
 * Seed the 3 initial progression rules + assign archetypes + generate profiles.
 */
export async function seedProgressionRules(prisma: PrismaClient) {
  console.log('📈 Seeding progression rules...');

  const rules = [
    {
      name: 'Weight Increase (Positive)',
      scope: 'global',
      trigger: 'session_completed',
      conditions: [
        { metric: 'avgFormScore', operator: '>=', value: 75, window: 'last_2_sessions' },
        { metric: 'completionRate', operator: '>=', value: 90, window: 'last_2_sessions' },
      ],
      action: {
        type: 'increase_weight',
        amount: 2.5,
        notification: {
          ar: 'أداء ممتاز! تم زيادة الوزن 2.5 كجم للجلسة القادمة.',
          en: 'Great performance! Weight increased by 2.5kg for next session.',
        },
      },
      priority: 10,
      isActive: true,
    },
    {
      name: 'Rep Increase (Weekly)',
      scope: 'global',
      trigger: 'session_completed',
      conditions: [
        { metric: 'avgFormScore', operator: '>=', value: 80, window: 'last_week' },
        { metric: 'avgROM', operator: '>=', value: 85, window: 'last_week' },
      ],
      action: {
        type: 'increase_reps',
        amount: 2,
        notification: {
          ar: 'تقدم رائع! تم زيادة التكرارات بمقدار 2.',
          en: 'Amazing progress! Reps increased by 2.',
        },
      },
      priority: 5,
      isActive: true,
    },
    {
      name: 'Deload Safety',
      scope: 'global',
      trigger: 'session_completed',
      conditions: [
        { metric: 'avgFormScore', operator: '<', value: 60, window: 'last_2_sessions' },
      ],
      action: {
        type: 'decrease_weight',
        amount: 2.5,
        notification: {
          ar: 'تم تخفيف الوزن 2.5 كجم للحفاظ على سلامتك. ركز على الأداء الصحيح.',
          en: 'Weight reduced by 2.5kg for your safety. Focus on proper form.',
        },
      },
      priority: 20,
      isActive: true,
    },
  ];

  for (const rule of rules) {
    const existing = await prisma.progressionRule.findFirst({
      where: { name: rule.name },
    });

    if (!existing) {
      await prisma.progressionRule.create({ data: rule });
    }
  }

  console.log(`  ✅ Seeded ${rules.length} progression rules`);

  // Assign archetypes to published exercises that don't have one yet
  await assignArchetypes(prisma);
  await generateDefaultProfiles(prisma);
}

async function assignArchetypes(prisma: PrismaClient) {
  console.log('📊 Assigning archetypes to exercises...');

  const exercises = await prisma.exercise.findMany({
    where: { archetype: null, status: 'published', deletedAt: null },
    select: {
      id: true,
      supportsWeight: true,
      countingMethod: { select: { code: true } },
    },
  });

  let updated = 0;
  for (const ex of exercises) {
    let archetype: ExerciseArchetype;

    if (ex.supportsWeight) {
      archetype = 'weighted_strength';
    } else if (ex.countingMethod?.code === 'hold' || ex.countingMethod?.code === 'duration') {
      archetype = 'isometric_hold';
    } else if (ex.countingMethod?.code === 'reps' || ex.countingMethod?.code === 'rep') {
      archetype = 'bodyweight_dynamic';
    } else {
      archetype = 'motor_control';
    }

    await prisma.exercise.update({
      where: { id: ex.id },
      data: { archetype },
    });
    updated++;
  }

  console.log(`  ✅ Assigned archetypes to ${updated} exercises`);
}

async function generateDefaultProfiles(prisma: PrismaClient) {
  console.log('📋 Generating default progression profiles...');

  const exercises = await prisma.exercise.findMany({
    where: {
      archetype: { not: null },
      status: 'published',
      deletedAt: null,
      progressionProfile: null,
    },
    select: { id: true, archetype: true },
  });

  let created = 0;
  for (const ex of exercises) {
    if (!ex.archetype) continue;
    const defaults = ARCHETYPE_DEFAULTS[ex.archetype];
    if (!defaults) continue;

    const existing = await prisma.exerciseProgressionProfile.findUnique({
      where: { exerciseId: ex.id },
    });
    if (existing) continue;

    await prisma.exerciseProgressionProfile.create({
      data: {
        exerciseId: ex.id,
        archetype: ex.archetype,
        repRange: defaults.repRange ?? undefined,
        weightBounds: defaults.weightBounds ?? undefined,
        durationBounds: defaults.durationBounds ?? undefined,
        qualityGate: defaults.qualityGate,
        promotionRule: defaults.promotionRule as any,
        regressionRule: defaults.regressionRule as any,
        difficultyLadder: defaults.difficultyLadder ?? undefined,
        isAutoGenerated: true,
      },
    });
    created++;
  }

  console.log(`  ✅ Generated ${created} default progression profiles`);
}
