import { getPrisma } from '@/lib/prisma/client';
import { buildExerciseSearchWhere } from '@/modules/exercises/exercise-search.util';
import { buildDefaultProfile, ARCHETYPE_DEFAULTS } from './archetype-defaults';

export const exerciseProgressionProfileService = {
  async getProfile(exerciseId: string) {
    const prisma = await getPrisma();
    return prisma.exerciseProgressionProfile.findUnique({
      where: { exerciseId },
      include: { exercise: { select: { id: true, name: true, slug: true } } },
    });
  },

  async listProfiles(filters?: { archetype?: string }) {
    const prisma = await getPrisma();
    return prisma.exerciseProgressionProfile.findMany({
      where: filters?.archetype ? { archetype: filters.archetype as any } : {},
      include: { exercise: { select: { id: true, name: true, slug: true, status: true } } },
      orderBy: { updatedAt: 'desc' },
    });
  },

  async listExercisesWithProfileStatus(search?: string) {
    const prisma = await getPrisma();
    const searchWhere = buildExerciseSearchWhere(search);
    const exercises = await prisma.exercise.findMany({
      where: {
        status: 'published',
        deletedAt: null,
        ...(searchWhere ? { AND: [searchWhere] } : {}),
      },
      select: {
        id: true,
        name: true,
        slug: true,
        archetype: true,
        progressionProfile: {
          select: { id: true, archetype: true, isAutoGenerated: true, allowedAxes: true },
        },
      },
      orderBy: { slug: 'asc' },
    });

    return exercises.map((ex) => ({
      id: ex.id,
      name: ex.name,
      slug: ex.slug,
      archetype: ex.archetype,
      hasProfile: !!ex.progressionProfile,
      profile: ex.progressionProfile
        ? {
            id: ex.progressionProfile.id,
            archetype: ex.progressionProfile.archetype,
            isAutoGenerated: ex.progressionProfile.isAutoGenerated,
            allowedAxes: ex.progressionProfile.allowedAxes,
          }
        : null,
    }));
  },

  async generateDefaultProfile(exerciseId: string, archetype: string) {
    const prisma = await getPrisma();
    const defaults = buildDefaultProfile(archetype);
    if (!defaults) throw new Error(`Unknown archetype: ${archetype}`);

    await prisma.exercise.update({
      where: { id: exerciseId },
      data: { archetype: archetype as any },
    });

    const toJson = (v: unknown) => v != null ? JSON.parse(JSON.stringify(v)) : undefined;

    return prisma.exerciseProgressionProfile.upsert({
      where: { exerciseId },
      create: {
        exerciseId,
        archetype: archetype as any,
        allowedAxes: defaults.allowedAxes,
        priorityOrder: defaults.priorityOrder,
        repAxis: toJson(defaults.repAxis),
        loadAxis: toJson(defaults.loadAxis),
        durationAxis: toJson(defaults.durationAxis),
        setAxis: toJson(defaults.setAxis),
        difficultyLadder: defaults.difficultyLadder ?? undefined,
        qualityGate: toJson(defaults.qualityGate),
        promotionPolicy: toJson(defaults.promotionPolicy),
        regressionPolicy: toJson(defaults.regressionPolicy),
        isAutoGenerated: true,
      },
      update: {
        archetype: archetype as any,
        allowedAxes: defaults.allowedAxes,
        priorityOrder: defaults.priorityOrder,
        repAxis: toJson(defaults.repAxis),
        loadAxis: toJson(defaults.loadAxis),
        durationAxis: toJson(defaults.durationAxis),
        setAxis: toJson(defaults.setAxis),
        difficultyLadder: defaults.difficultyLadder ?? undefined,
        qualityGate: toJson(defaults.qualityGate),
        promotionPolicy: toJson(defaults.promotionPolicy),
        regressionPolicy: toJson(defaults.regressionPolicy),
        isAutoGenerated: true,
      },
    });
  },

  async updateProfile(exerciseId: string, data: Record<string, unknown>) {
    const prisma = await getPrisma();

    const existing = await prisma.exerciseProgressionProfile.findUnique({
      where: { exerciseId },
    });
    if (!existing) throw new Error('Profile not found. Generate defaults first.');

    return prisma.exerciseProgressionProfile.update({
      where: { exerciseId },
      data: {
        ...(data.allowedAxes !== undefined ? { allowedAxes: data.allowedAxes as any } : {}),
        ...(data.priorityOrder !== undefined ? { priorityOrder: data.priorityOrder as any } : {}),
        ...(data.repAxis !== undefined ? { repAxis: data.repAxis as any } : {}),
        ...(data.loadAxis !== undefined ? { loadAxis: data.loadAxis as any } : {}),
        ...(data.durationAxis !== undefined ? { durationAxis: data.durationAxis as any } : {}),
        ...(data.setAxis !== undefined ? { setAxis: data.setAxis as any } : {}),
        ...(data.difficultyLadder !== undefined ? { difficultyLadder: data.difficultyLadder as any } : {}),
        ...(data.qualityGate !== undefined ? { qualityGate: data.qualityGate as any } : {}),
        ...(data.promotionPolicy !== undefined ? { promotionPolicy: data.promotionPolicy as any } : {}),
        ...(data.regressionPolicy !== undefined ? { regressionPolicy: data.regressionPolicy as any } : {}),
        isAutoGenerated: false,
      },
    });
  },

  async setArchetype(exerciseId: string, archetype: string) {
    const prisma = await getPrisma();
    if (!ARCHETYPE_DEFAULTS[archetype]) throw new Error(`Unknown archetype: ${archetype}`);

    await prisma.exercise.update({
      where: { id: exerciseId },
      data: { archetype: archetype as any },
    });

    return this.generateDefaultProfile(exerciseId, archetype);
  },

  async bulkGenerateProfiles(exerciseIds: string[], archetype: string) {
    const results: unknown[] = [];
    for (const exerciseId of exerciseIds) {
      const profile = await this.generateDefaultProfile(exerciseId, archetype);
      results.push(profile);
    }
    return results;
  },

  getAvailableArchetypes() {
    return Object.entries(ARCHETYPE_DEFAULTS).map(([key, value]) => ({
      code: key,
      allowedAxes: value.allowedAxes,
      priorityOrder: value.priorityOrder,
    }));
  },

  async validateProfile(exerciseId: string): Promise<{ valid: boolean; errors: string[] }> {
    const prisma = await getPrisma();
    const profile = await prisma.exerciseProgressionProfile.findUnique({
      where: { exerciseId },
    });

    if (!profile) return { valid: false, errors: ['No profile exists'] };

    const errors: string[] = [];
    const allowedAxes = profile.allowedAxes as string[];
    const priorityOrder = profile.priorityOrder as string[];

    if (!allowedAxes || allowedAxes.length === 0) errors.push('No axes defined in allowedAxes');
    if (!priorityOrder || priorityOrder.length === 0) errors.push('No priorityOrder defined');

    for (const axis of allowedAxes) {
      if (axis === 'reps' && !profile.repAxis) errors.push('repAxis config missing but reps in allowedAxes');
      if (axis === 'load' && !profile.loadAxis) errors.push('loadAxis config missing but load in allowedAxes');
      if (axis === 'duration' && !profile.durationAxis) errors.push('durationAxis config missing but duration in allowedAxes');
      if (axis === 'sets' && !profile.setAxis) errors.push('setAxis config missing but sets in allowedAxes');
      if (axis === 'difficulty' && !profile.difficultyLadder) errors.push('difficultyLadder missing but difficulty in allowedAxes');
    }

    if (!profile.qualityGate) errors.push('qualityGate missing');
    if (!profile.promotionPolicy) errors.push('promotionPolicy missing');
    if (!profile.regressionPolicy) errors.push('regressionPolicy missing');

    return { valid: errors.length === 0, errors };
  },
};
