import { getPrisma } from '@/lib/prisma/client';
import type { ExerciseArchetype } from '@prisma/client';
import { ARCHETYPE_DEFAULTS } from './archetype-defaults';

export const exerciseProgressionProfileService = {
  async getProfile(exerciseId: string) {
    const prisma = await getPrisma();
    return prisma.exerciseProgressionProfile.findUnique({
      where: { exerciseId },
      include: { exercise: { select: { id: true, name: true, slug: true, archetype: true } } },
    });
  },

  async listProfiles(filters?: { archetype?: ExerciseArchetype; isAutoGenerated?: boolean }) {
    const prisma = await getPrisma();

    const profiles = await prisma.exerciseProgressionProfile.findMany({
      where: {
        ...(filters?.archetype ? { archetype: filters.archetype } : {}),
        ...(filters?.isAutoGenerated !== undefined ? { isAutoGenerated: filters.isAutoGenerated } : {}),
      },
      include: {
        exercise: { select: { id: true, name: true, slug: true, archetype: true, supportsWeight: true } },
      },
      orderBy: { updatedAt: 'desc' },
    });

    return profiles;
  },

  async listExercisesWithProfileStatus() {
    const prisma = await getPrisma();

    const exercises = await prisma.exercise.findMany({
      where: { status: 'published', deletedAt: null },
      select: {
        id: true,
        name: true,
        slug: true,
        archetype: true,
        supportsWeight: true,
        progressionProfile: {
          select: { id: true, archetype: true, isAutoGenerated: true, updatedAt: true },
        },
      },
      orderBy: { name: 'asc' },
    });

    return exercises.map((ex) => ({
      id: ex.id,
      name: ex.name,
      slug: ex.slug,
      archetype: ex.archetype,
      supportsWeight: ex.supportsWeight,
      profileStatus: ex.progressionProfile
        ? (ex.progressionProfile.isAutoGenerated ? 'auto' : 'custom')
        : 'none',
      profileId: ex.progressionProfile?.id ?? null,
      profileUpdatedAt: ex.progressionProfile?.updatedAt?.toISOString() ?? null,
    }));
  },

  async generateDefaultProfile(exerciseId: string, archetype: ExerciseArchetype) {
    const prisma = await getPrisma();
    const defaults = ARCHETYPE_DEFAULTS[archetype];

    if (!defaults) {
      throw new Error(`Unknown archetype: ${archetype}`);
    }

    const existing = await prisma.exerciseProgressionProfile.findUnique({
      where: { exerciseId },
    });

    if (existing) {
      return prisma.exerciseProgressionProfile.update({
        where: { exerciseId },
        data: {
          archetype,
          repRange: defaults.repRange ?? undefined,
          weightBounds: defaults.weightBounds ?? undefined,
          durationBounds: defaults.durationBounds ?? undefined,
          qualityGate: defaults.qualityGate,
          promotionRule: defaults.promotionRule as any,
          regressionRule: defaults.regressionRule as any,
          difficultyLadder: defaults.difficultyLadder ?? undefined,
          isAutoGenerated: true,
        },
        include: { exercise: { select: { id: true, name: true, slug: true } } },
      });
    }

    return prisma.exerciseProgressionProfile.create({
      data: {
        exerciseId,
        archetype,
        repRange: defaults.repRange ?? undefined,
        weightBounds: defaults.weightBounds ?? undefined,
        durationBounds: defaults.durationBounds ?? undefined,
        qualityGate: defaults.qualityGate,
        promotionRule: defaults.promotionRule as any,
        regressionRule: defaults.regressionRule as any,
        difficultyLadder: defaults.difficultyLadder ?? undefined,
        isAutoGenerated: true,
      },
      include: { exercise: { select: { id: true, name: true, slug: true } } },
    });
  },

  async updateProfile(exerciseId: string, data: {
    repRange?: unknown;
    weightBounds?: unknown;
    durationBounds?: unknown;
    qualityGate?: unknown;
    promotionRule?: unknown;
    regressionRule?: unknown;
    difficultyLadder?: unknown;
  }) {
    const prisma = await getPrisma();

    const existing = await prisma.exerciseProgressionProfile.findUnique({
      where: { exerciseId },
    });

    if (!existing) {
      throw new Error(`No profile found for exercise ${exerciseId}`);
    }

    return prisma.exerciseProgressionProfile.update({
      where: { exerciseId },
      data: {
        ...(data.repRange !== undefined && { repRange: data.repRange as any }),
        ...(data.weightBounds !== undefined && { weightBounds: data.weightBounds as any }),
        ...(data.durationBounds !== undefined && { durationBounds: data.durationBounds as any }),
        ...(data.qualityGate !== undefined && { qualityGate: data.qualityGate as any }),
        ...(data.promotionRule !== undefined && { promotionRule: data.promotionRule as any }),
        ...(data.regressionRule !== undefined && { regressionRule: data.regressionRule as any }),
        ...(data.difficultyLadder !== undefined && { difficultyLadder: data.difficultyLadder as any }),
        isAutoGenerated: false,
      },
      include: { exercise: { select: { id: true, name: true, slug: true } } },
    });
  },

  async setArchetype(exerciseId: string, archetype: ExerciseArchetype) {
    const prisma = await getPrisma();

    await prisma.exercise.update({
      where: { id: exerciseId },
      data: { archetype },
    });

    return this.generateDefaultProfile(exerciseId, archetype);
  },

  async bulkGenerateProfiles(archetype?: ExerciseArchetype) {
    const prisma = await getPrisma();

    const where: any = {
      status: 'published',
      deletedAt: null,
      archetype: { not: null },
    };
    if (archetype) where.archetype = archetype;

    const exercises = await prisma.exercise.findMany({
      where,
      select: { id: true, archetype: true },
    });

    let created = 0;
    for (const ex of exercises) {
      if (!ex.archetype) continue;
      try {
        await this.generateDefaultProfile(ex.id, ex.archetype);
        created++;
      } catch (e) {
        console.warn(`[ProfileService] Failed to generate profile for ${ex.id}:`, e);
      }
    }

    return { total: exercises.length, created };
  },
};
