-- CreateEnum
DO $$ BEGIN
    CREATE TYPE "ExerciseArchetype" AS ENUM ('weighted_strength', 'bodyweight_dynamic', 'isometric_hold', 'mobility_rom', 'motor_control');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- AlterTable: exercises — add archetype column
ALTER TABLE "exercises" ADD COLUMN IF NOT EXISTS "archetype" "ExerciseArchetype";

-- CreateTable: exercise_progression_profiles
CREATE TABLE IF NOT EXISTS "exercise_progression_profiles" (
    "id" TEXT NOT NULL,
    "exerciseId" TEXT NOT NULL,
    "archetype" "ExerciseArchetype" NOT NULL,
    "allowedAxes" JSONB NOT NULL,
    "priorityOrder" JSONB NOT NULL,
    "repAxis" JSONB,
    "loadAxis" JSONB,
    "durationAxis" JSONB,
    "setAxis" JSONB,
    "difficultyLadder" JSONB,
    "qualityGate" JSONB NOT NULL,
    "promotionPolicy" JSONB NOT NULL,
    "regressionPolicy" JSONB NOT NULL,
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "exercise_progression_profiles_pkey" PRIMARY KEY ("id")
);

-- CreateTable: user_program_exercise_progression_state
CREATE TABLE IF NOT EXISTS "user_program_exercise_progression_state" (
    "id" TEXT NOT NULL,
    "userProgramId" TEXT NOT NULL,
    "exerciseId" TEXT NOT NULL,
    "currentAxis" TEXT NOT NULL,
    "currentDifficultyCode" TEXT,
    "currentWeightKg" DOUBLE PRECISION,
    "currentTargetReps" INTEGER,
    "currentTargetDuration" INTEGER,
    "currentTargetSets" INTEGER,
    "successStreak" INTEGER NOT NULL DEFAULT 0,
    "regressionStreak" INTEGER NOT NULL DEFAULT 0,
    "lastProgressedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "user_program_exercise_progression_state_pkey" PRIMARY KEY ("id")
);

-- AlterTable: progression_history — add new columns + make ruleId optional
ALTER TABLE "progression_history" ADD COLUMN IF NOT EXISTS "decisionType" TEXT;
ALTER TABLE "progression_history" ADD COLUMN IF NOT EXISTS "axis" TEXT;
ALTER TABLE "progression_history" ADD COLUMN IF NOT EXISTS "eligibilitySnapshot" JSONB;
ALTER TABLE "progression_history" ADD COLUMN IF NOT EXISTS "stateBefore" JSONB;
ALTER TABLE "progression_history" ADD COLUMN IF NOT EXISTS "stateAfter" JSONB;
ALTER TABLE "progression_history" ADD COLUMN IF NOT EXISTS "seen" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "progression_history" ADD COLUMN IF NOT EXISTS "seenAt" TIMESTAMP(3);
ALTER TABLE "progression_history" ALTER COLUMN "ruleId" DROP NOT NULL;

-- CreateIndexes: exercise_progression_profiles
CREATE UNIQUE INDEX IF NOT EXISTS "exercise_progression_profiles_exerciseId_key" ON "exercise_progression_profiles"("exerciseId");
CREATE INDEX IF NOT EXISTS "exercise_progression_profiles_archetype_idx" ON "exercise_progression_profiles"("archetype");

-- CreateIndexes: user_program_exercise_progression_state
CREATE UNIQUE INDEX IF NOT EXISTS "user_program_exercise_progression_state_userProgramId_exer_key" ON "user_program_exercise_progression_state"("userProgramId", "exerciseId");
CREATE INDEX IF NOT EXISTS "user_program_exercise_progression_state_userProgramId_idx" ON "user_program_exercise_progression_state"("userProgramId");
CREATE INDEX IF NOT EXISTS "user_program_exercise_progression_state_exerciseId_idx" ON "user_program_exercise_progression_state"("exerciseId");

-- CreateIndex: progression_history (seen)
CREATE INDEX IF NOT EXISTS "progression_history_userId_seen_idx" ON "progression_history"("userId", "seen");

-- AddForeignKeys
DO $$ BEGIN
    ALTER TABLE "exercise_progression_profiles" ADD CONSTRAINT "exercise_progression_profiles_exerciseId_fkey" FOREIGN KEY ("exerciseId") REFERENCES "exercises"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE "user_program_exercise_progression_state" ADD CONSTRAINT "user_program_exercise_progression_state_userProgramId_fkey" FOREIGN KEY ("userProgramId") REFERENCES "user_programs"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE "user_program_exercise_progression_state" ADD CONSTRAINT "user_program_exercise_progression_state_exerciseId_fkey" FOREIGN KEY ("exerciseId") REFERENCES "exercises"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
